#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Every command, what it is for, and the same job in the window.

    python tools/docs/commands.py           # write docs/COMMANDS.md
    python tools/docs/commands.py --check   # verify it is current

# The gap this fills

`docs/USER_GUIDE.md` is the long walk through the application, and section 4 of
it shows twelve commands. `veilvoice` has thirty-two. The other twenty were
reachable only by running `--help` and knowing they were there: `sentry`,
`appctl`, `input`, `privilege`, `mandate`, `decoy`, `failsafe`, `volumes`,
`capture`, `import`, `video` and the rest. Every one of them is documented
inside the program, in its own `--help`, and nowhere a reader browsing the
documentation would meet it.

So this is the list, in full, with three things per command that the help text
does not say:

* **what you would actually use it for**, in plain words;
* **where the same job is in the window**, or that there is no such place and
  why, because the two halves of VeilVoice do not match one to one and a reader
  should not have to work out which;
* **one line to copy**, where a command takes arguments worth showing.

# What is derived and what is written

The command list and each command's own one-line summary are read from
`assets/screenshots/cli-help.txt`, which is captured from the program by
`tools/shots/terminal.py` and checked against it in CI. So the *set* of
commands here cannot drift from the program.

The three things above are written, because an explanation is writing. They are
held to the program a different way: a command with nothing written about it
**fails this generator**, and a named window location that is not a tab the
window has fails it too. A command added tomorrow therefore stops a build until
somebody has said what it is for, which is the only arrangement that keeps a
list of thirty-two things honest.

`veilvoice-cli` also checks, in its own test suite, that every subcommand clap
knows about appears in this document, from the other direction: clap's tree
rather than a captured file.

Pure standard library.
"""

from __future__ import annotations

import argparse
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))

OUT = "docs/COMMANDS.md"
HELP = "assets/screenshots/cli-help.txt"

BANNER = (
    "<!-- SPDX-License-Identifier: GPL-3.0-or-later -->\n"
    "<!-- GENERATED by tools/docs/commands.py. Do not edit: the list comes\n"
    "     from the program's own `--help`, and the prose from the tables in\n"
    "     that file. CI verifies it with\n"
    "         python tools/docs/commands.py --check\n"
    "-->")

# A row of clap's command list: two spaces, the name, then its summary.
ROW = re.compile(r"^  (?P<name>[a-z][a-z-]*)\s{2,}(?P<summary>\S.*)$")

# `Tab::key` in the window's own source, so a location named below is a
# location that exists.
TAB_KEY = re.compile(r'Self::(?P<variant>\w+) => "(?P<key>[a-z]+)",')

# What each command is for, where the same job is in the window, and a line to
# copy.
#
# `window` is a pair: the tab key, or `None` when the window has no equivalent,
# and the sentence that goes with it. A `None` always carries a reason. "There
# is no button for this" is information, and the reason is usually the
# interesting part: `shred` is irreversible, `decoy` stops being a decoy the
# moment it is visible, and `policy` would not be a policy if the interface
# could switch it off.
NOTES = {
    "anonymise": {
        "use": "The main event, for a recording you already have. It reads "
               "almost any audio format, destroys the voiceprint, keeps every "
               "word, and seals the result so a veiled recording is not left "
               "lying about in the clear.",
        "window": ("file", "the **Anonymise file** tab, which is the same "
                   "engine with the same defaults"),
        "example": "veilvoice anonymise interview.m4a -o clean.wav",
    },
    "live": {
        "use": "Your microphone, veiled as you speak, into a virtual cable "
               "that other programs can use as their microphone. This is the "
               "one for a call, an interview or a stream.",
        "window": ("studio", "the top half of the **Studio**, which starts the "
                   "same session and draws the levels while it runs"),
        "example": "veilvoice live --output \"CABLE Input (VB-Audio Virtual Cable)\"",
    },
    "record": {
        "use": "Record yourself already veiled, straight into an encrypted "
               "file. The third case beside the two above: `live` keeps "
               "nothing and `anonymise` needs a recording that already "
               "exists in the clear. This never creates the original.",
        "window": ("studio", "the bottom half of the **Studio**, which puts "
                   "the take in the vault"),
        "example": "veilvoice record --seconds 120",
    },
    "devices": {
        "use": "What this machine offers as inputs and outputs, and which of "
               "them look like a virtual cable. Run it first when `live` "
               "cannot find the device you meant.",
        "window": ("studio", "the two device pickers at the top of the "
                   "**Studio**"),
        "example": "veilvoice devices",
    },
    "clean": {
        "use": "Strips identifying metadata out of an audio file or a "
               "photograph, in place: tags, timestamps, camera model, GPS. "
               "Veiling a voice and then sending a file that names your "
               "phone helps nobody.",
        "window": ("file", "the **strip metadata from the result** tick on "
                   "the **Anonymise file** tab, which covers what VeilVoice "
                   "writes; a photograph is this command"),
        "example": "veilvoice clean photo.jpg",
    },
    "encrypt": {
        "use": "Seals any file into a `.veil` container, under a passphrase "
               "or to somebody's public key. `anonymise` already seals what "
               "it writes, so this is for everything else: a note, an older "
               "recording, a key you want to move.",
        "window": (None, "the window seals what it writes rather than "
                   "offering a general encrypt button, so there is nothing "
                   "here that this command does not do better"),
        "example": "veilvoice encrypt notes.wav --to friend.pub",
    },
    "decrypt": {
        "use": "Opens a `.veil` container again, with the passphrase or the "
               "private key it was sealed to. This is how you get your WAV "
               "back after `anonymise`.",
        "window": ("browser", "the **Browser**, which plays and exports what "
                   "is in the vault without writing anything in the clear"),
        "example": "veilvoice decrypt clean.wav.veil -o clean.wav",
    },
    "keygen": {
        "use": "Makes a hybrid post-quantum key pair, so somebody can seal a "
               "recording to you without either of you sharing a passphrase. "
               "The private half is itself stored encrypted.",
        "window": (None, "the window accepts a `.pub` file and does not make "
                   "one: a key pair is made once, deliberately, and belongs "
                   "in the place you keep keys rather than behind a button"),
        "example": "veilvoice keygen",
    },
    "guard": {
        "use": "Writes down what VeilVoice's own files should look like, then "
               "checks later that they still do. It notices changes and does "
               "not prevent them, and says so on every path through it.",
        "window": ("lock", "the **Lock** tab, and the window does this for "
                   "itself: a record is taken at the first launch that finds "
                   "none, checked at every launch after, and sealed under the "
                   "app-lock passphrase when there is one, which is the one "
                   "moment that passphrase exists. With no app lock the record "
                   "is written in the clear and the tab says so, because "
                   "sealing it under a key kept beside it would be a "
                   "decoration rather than a protection. This command is how "
                   "you take one deliberately, seal it with a passphrase of "
                   "its own, and check it from a script"),
        "example": "veilvoice guard init --sealed",
    },
    "lock": {
        "use": "The password for VeilVoice itself: set it, change it, remove "
               "it, or ask whether one is set and whether it is rate limited "
               "right now.",
        "window": ("lock", "the **Lock** tab, which has the same four "
                   "actions and the same account of what the lock is worth"),
        "example": "veilvoice lock set",
    },
    "watch": {
        "use": "Which programs are holding your microphone and camera, with "
               "a log of starts and stops. The question this answers is "
               "whether something else is listening while you work.",
        "window": ("monitor", "the **Monitor** tab, plus the indicator that "
                   "rides the header on every other tab"),
        "example": "veilvoice watch",
    },
    "shred": {
        "use": "Overwrites a file's contents and then deletes it. For a "
               "recording that must not survive, with the honest limit "
               "printed every time: on flash storage the old blocks can "
               "survive every overwrite, and full-disk encryption is the "
               "real answer.",
        "window": (None, "there is no button for this on purpose. It cannot "
                   "be undone, and a one-click irreversible delete beside a "
                   "list of recordings is an accident waiting to be made"),
        "example": "veilvoice shred secret.wav",
    },
    "info": {
        "use": "Version, build and what this copy can do on this machine. "
               "The first thing to paste into a bug report.",
        "window": ("about", "the **About** tab, which shows the same "
                   "information and the paths in use"),
        "example": "veilvoice info",
    },
    "accel": {
        "use": "What graphics hardware is here and what it is good for, "
               "which decides how fast a render goes and whether the window "
               "draws on the GPU.",
        "window": ("about", "the graphics line on the **About** tab, taken "
                   "from the driver that actually drew the window"),
        "example": "veilvoice accel",
    },
    "gui": {
        "use": "Opens the desktop application. Exactly the same as running "
               "`veilvoice-gui`, and it exists so that somebody who has only "
               "met the command line does not have to know there are two "
               "programs.",
        "window": (None, "this command *is* the window"),
        "example": "veilvoice gui",
    },
    "install": {
        "use": "Copies VeilVoice somewhere the system can find it and adds it "
               "to your PATH, so `veilvoice` works from any directory. "
               "Running from the folder you unpacked is a supported choice, "
               "not a lesser one.",
        "window": ("install", "the **Install** tab, which an installed copy "
                   "does not show, because a program offering to install "
                   "itself when it already is tells you something untrue"),
        "example": "veilvoice install",
    },
    "update": {
        "use": "Fetches the newest release, checks it, and puts it in place. "
               "Nothing here happens on its own: there is no timer, nothing at "
               "startup and nothing in the background. Everything downloaded is "
               "checked against the signature made with the key already inside "
               "the copy you are running, before the archive is opened and long "
               "before anything of yours is replaced, and an update that fails "
               "any part of that replaces nothing. It updates the copy you are "
               "running, which for a folder you unpacked is that folder, and it "
               "asks for your app lock if you have one, because the integrity "
               "record is sealed with it and has to be rewritten. "
               "`--check` reports the published version and changes nothing.",
        "window": ("about", "the **Check for updates** button on the About tab, "
                   "which asks the same question the same way"),
        "example": "veilvoice update --check",
    },
    "uninstall": {
        "use": "Undoes exactly what `install` did: the copy, the PATH entry "
               "and the uninstall entry. It does not touch your settings, "
               "your app lock or your recordings.",
        "window": (None, "the window has no uninstall button: a program's own "
                   "interface is the wrong place to remove it from, and on "
                   "Windows the platform's own entry is where people look"),
        "example": "veilvoice uninstall",
    },
    "policy": {
        "use": "Settings fixed so the interface cannot turn them off, for a "
               "machine somebody else is responsible for. Every setting a "
               "policy can reach makes VeilVoice stricter; there is no room "
               "in the format for one that loosens it.",
        "window": (None, "a policy the interface could switch off would not "
                   "be a policy. The window shows what is in force and "
                   "greys out what the policy has decided"),
        "example": "veilvoice policy status",
    },
    "mandate": {
        "use": "The two things VeilVoice insists on unless you say otherwise: "
               "a password for itself, and encryption for every recording. "
               "This is the one place that can make it less strict, for your "
               "own machine, and every change is written down with its date.",
        "window": (None, "relaxing a requirement is a decision with a date "
                   "on it rather than a tick box, so it is asked for "
                   "deliberately at a terminal"),
        "example": "veilvoice mandate status",
    },
    "conversation": {
        "use": "A recording with several people in it: a voice each, "
               "subtitles, and every voiceprint destroyed just as "
               "thoroughly. You say who is talking, in a plan file, because "
               "guessing would merge two people or invent a third.",
        "window": ("group", "the **Group** tab, which is the same plan built "
                   "by pointing and clicking"),
        "example": "veilvoice conversation render plan.toml -o out.wav",
    },
    "capture": {
        "use": "Which screen recorders are running, and where to point "
               "Discord, Signal, Telegram and the rest so your voice goes "
               "through VeilVoice first. It tells you once and then stops "
               "telling you if you say you meant it.",
        "window": ("monitor", "the recorder list on the **Monitor** tab"),
        "example": "veilvoice capture status",
    },
    "decoy": {
        "use": "A second passphrase that opens an empty VeilVoice, for "
               "complying with somebody standing over you. It does not give "
               "you deniability, since this feature is documented and the "
               "program is open source, and no passphrase destroys anything.",
        "window": (None, "a decoy passphrase offered by the interface is not "
                   "a decoy. The **Browser** can fill the folder with decoy "
                   "vaults, which is the other half of the same idea"),
        "example": "veilvoice decoy",
    },
    "failsafe": {
        "use": "The safety catch: it notices when another program picks up a "
               "real microphone while you are being veiled, which is the "
               "accident where a headset is plugged in and the call quietly "
               "switches over. It notices within about a second and cannot "
               "prevent it, and prints the difference every time.",
        "window": ("studio", "always on while the **Studio** is veiling, and "
                   "reported there"),
        "example": "veilvoice failsafe",
    },
    "privilege": {
        "use": "What VeilVoice is running with and what that lets it see. "
               "The monitoring features see further as an administrator; it "
               "never raises its own privileges or asks for a password, and "
               "prints the command to run it the other way.",
        "window": (None, "the window reports what it can and cannot see on "
                   "the **Monitor** tab rather than asking to be trusted "
                   "with more"),
        "example": "veilvoice privilege",
    },
    "appctl": {
        "use": "Learn what normally runs on this machine, then notice what "
               "does not. Run `learn` for a few days of ordinary work, close "
               "the baseline, and `check` afterwards. It blocks nothing and "
               "cannot: it is a way of noticing.",
        "window": (None, "a baseline is built over days from a terminal, and "
                   "a window that had to stay open for it would be the wrong "
                   "shape for the job"),
        "example": "veilvoice appctl check",
    },
    "input": {
        "use": "Which running programs are *able* to see your keyboard and "
               "mouse: remote-support tools, macro recorders, password "
               "managers, screen readers. It cannot tell you whether "
               "anything is logging you, and nothing can, and it says that "
               "with every result.",
        "window": (None, "the same list would need the same paragraph beside "
                   "it, and the honest place for a result that cannot be a "
                   "verdict is a terminal somebody asked"),
        "example": "veilvoice input look",
    },
    "sentry": {
        "use": "Two early warnings that something is going through your "
               "files: a canary file nothing should ever touch, and a "
               "baseline that says how fast a folder is changing. Neither "
               "stops anything and neither names the program responsible.",
        "window": (None, "planting a canary is a change to a folder you own, "
                   "asked for once from a terminal rather than offered in a "
                   "panel"),
        "example": "veilvoice sentry plant ~/Recordings",
    },
    "companions": {
        "use": "The optional third-party software VeilVoice works with, "
               "whether this machine already has it, and how to get it. "
               "Nothing proprietary is ever installed without you agreeing "
               "to its licence.",
        "window": ("about", "the companion list on the **About** tab, which "
                   "installs with the same confirmation, cancel and resume"),
        "example": "veilvoice companions",
    },
    "verify": {
        "use": "Checks a download against the signed hash list, and says "
               "what did the checking. The signing key is compiled into this "
               "binary, so a download that brings its own key and its own "
               "signature cannot vouch for itself.",
        "window": ("verify", "the **Verify** tab, which takes the files by "
                   "drag and drop and can ask your own GnuPG the same "
                   "question"),
        "example": "veilvoice verify file veilvoice.tar.gz --sums SHA256SUMS --sig SHA256SUMS.asc",
    },
    "video": {
        "use": "Turns a veiled recording into a video with a black picture, "
               "for posting somewhere that will not accept an audio file. "
               "Needs ffmpeg, which VeilVoice does not ship and will not "
               "install: it prints the exact command when the tool is "
               "missing.",
        "window": ("browser", "the export button in the **Browser**, which "
                   "writes the same file from the vault"),
        "example": "veilvoice video clean.wav -o clean.mp4",
    },
    "import": {
        "use": "Pulls the audio out of a recording made somewhere else, such "
               "as anything OBS writes, into a WAV that `anonymise` can "
               "take. Needs ffmpeg, with the same refusal as above.",
        "window": ("file", "the **Anonymise file** tab reads audio formats "
                   "directly; a video container is this command first"),
        "example": "veilvoice import stream.mkv -o stream.wav",
    },
    "volumes": {
        "use": "Which encrypted volumes this machine has, Cryptomator and "
               "VeraCrypt, and which are mounted right now. It never opens, "
               "closes or unlocks anything and never asks for a volume "
               "password: mounting your storage is your act, in the tool you "
               "chose.",
        "window": (None, "the window writes into whatever folder you give it, "
                   "mounted volume or not, and deliberately does not learn "
                   "how to mount things"),
        "example": "veilvoice volumes",
    },
}


def read(relative):
    with io.open(os.path.join(ROOT, relative), encoding="utf-8") as handle:
        return handle.read()


def commands():
    """Every subcommand and its own one-line summary, from the captured help."""
    text = read(HELP).replace("\r\n", "\n")
    try:
        block = text.split("\nCommands:\n", 1)[1].split("\n\nOptions:", 1)[0]
    except IndexError:
        raise SystemExit(
            "%s does not have a `Commands:` block, so the list of commands\n"
            "  cannot be read from it. Re-capture it with\n"
            "      python tools/shots/terminal.py --capture" % HELP)
    found = []
    for line in block.split("\n"):
        match = ROW.match(line)
        if not match:
            continue
        name = match.group("name")
        # `help` is clap's own, printed in the list and absent from the
        # command tree the program is built from, which is what
        # `veilvoice-cli`'s own guard compares the documentation against. A
        # section for it would therefore be a section for a command that
        # does not exist by that guard's reckoning, and the guard is right:
        # there is nothing here to describe that `--help` does not. The
        # introduction says so in a sentence instead.
        if name == "help":
            continue
        found.append((name, match.group("summary").strip()))
    if len(found) < 10:
        raise SystemExit(
            "only %d commands were found in %s, which cannot be right."
            % (len(found), HELP))
    return found


def tabs():
    """Every tab key the window has, so a named location is one that exists."""
    source = read("crates/veilvoice-gui/src/app.rs")
    keys = {m.group("key") for m in TAB_KEY.finditer(source)}
    if not keys:
        raise SystemExit(
            "no tab keys were found in crates/veilvoice-gui/src/app.rs, so a\n"
            "  window location named here cannot be checked against the window.")
    return keys


def checked_notes(found, known_tabs):
    """The notes, with every gap and every wrong tab reported at once."""
    problems = []
    for name, _summary in found:
        note = NOTES.get(name)
        if note is None:
            problems.append(
                "`veilvoice %s` exists and nothing here says what it is for. "
                "Add it to NOTES in tools/docs/commands.py." % name)
            continue
        for field in ("use", "window"):
            if not note.get(field):
                problems.append("`veilvoice %s` has no %s." % (name, field))
        tab, sentence = note.get("window", (None, ""))
        if tab is not None and tab not in known_tabs:
            problems.append(
                "`veilvoice %s` says its place in the window is the %r tab, "
                "and the window has no such tab." % (name, tab))
        if tab is None and not sentence:
            problems.append(
                "`veilvoice %s` has no window equivalent and no reason given. "
                "The reason is the useful half." % name)
    extra = sorted(set(NOTES) - {name for name, _ in found})
    for name in extra:
        problems.append(
            "NOTES describes `veilvoice %s`, which the program does not have. "
            "Either it was renamed or the capture is stale." % name)
    if problems:
        print("docs/COMMANDS.md cannot be written:")
        for problem in problems:
            print("  %s" % problem)
        raise SystemExit(1)
    return NOTES


# Where a tab is, in words a reader can find on screen. Read from the window's
# own tab strip rather than written here: the labels are what a reader sees.
TAB_ROW = re.compile(r'\(Tab::(?P<variant>\w+),\s*"(?P<label>[^"]+)"\)')


def tab_labels():
    source = read("crates/veilvoice-gui/src/app.rs")
    keys = {m.group("variant"): m.group("key") for m in TAB_KEY.finditer(source)}
    out = {}
    for match in TAB_ROW.finditer(source):
        key = keys.get(match.group("variant"))
        if key:
            out[key] = match.group("label")
    return out


def document():
    found = commands()
    known = tabs()
    notes = checked_notes(found, known)
    labels = tab_labels()

    out = [BANNER, ""]
    out.append("# Every command, and the same job in the window")
    out.append("")
    out.append("VeilVoice is two programs over one engine. `veilvoice` is the "
               "command line and `veilvoice-gui` is the window, and they are "
               "not a menu bar and a wrapper around it: each has things the "
               "other does not, for reasons that are given below rather than "
               "left to be discovered.")
    out.append("")
    out.append("This page is the whole of the command line, in the program's "
               "own order, with what each command is for in plain words and "
               "where the same job lives in the window. Every command also "
               "takes `--help`, which is the reference for its flags; this is "
               "the part that says what to reach for. The program's own "
               "`help` command prints those same pages, and is the one entry "
               "in its list with no section below, because there is nothing "
               "to say about it that this sentence has not.")
    out.append("")
    out.append("**Nothing here reaches the network.** The one thing in "
               "VeilVoice that does is the window's check-for-updates button, "
               "and it is not a command.")
    out.append("")
    out.append("## The whole list")
    out.append("")
    out.append("| Command | What it does | In the window |")
    out.append("|---|---|---|")
    for name, summary in found:
        tab, sentence = notes[name]["window"]
        where = "**%s** tab" % labels.get(tab, tab) if tab else "command line only"
        out.append("| [`veilvoice %s`](#veilvoice-%s) | %s | %s |"
                   % (name, name, summary.rstrip("."), where))
    out.append("")
    out.append("---")
    out.append("")

    for name, summary in found:
        note = notes[name]
        tab, sentence = note["window"]
        out.append("## `veilvoice %s`" % name)
        out.append("")
        out.append("> %s" % summary)
        out.append("")
        out.append(note["use"])
        out.append("")
        if tab:
            out.append("**In the window:** %s." % sentence)
        else:
            out.append("**In the window:** nothing, and that is deliberate: "
                       "%s." % sentence)
        out.append("")
        if note.get("example"):
            out.append("```bash")
            out.append(note["example"])
            out.append("```")
            out.append("")

    out.append("---")
    out.append("")
    out.append("## Where to read next")
    out.append("")
    out.append("- [`docs/USER_GUIDE.md`](USER_GUIDE.md) walks through the "
               "window screen by screen and the command line in order.")
    out.append("- [`docs/GUIDE_CLI.md`](GUIDE_CLI.md) is the same guide with "
               "the window's half left out, for somebody at a terminal.")
    out.append("- [`docs/GUIDE_GUI.md`](GUIDE_GUI.md) is the other half.")
    out.append("- [`docs/DEVELOPERS.md`](DEVELOPERS.md) is where the code "
               "that answers each of these commands lives.")
    out.append("")
    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="verify the document is current, write nothing")
    args = parser.parse_args()

    text = document()
    path = os.path.join(ROOT, OUT)
    if args.check:
        current = read(OUT) if os.path.exists(path) else None
        if current != text:
            print("%s is out of date." % OUT)
            print("  Run: python tools/docs/commands.py")
            return 1
        print("  every command is documented (%d)" % len(commands()))
        return 0
    with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    print("  wrote %s (%d commands)" % (OUT, len(commands())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
