#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""The developer's way in: what is where, what is enforced, and where to start.

    python tools/docs/developers.py           # write docs/DEVELOPERS.md
    python tools/docs/developers.py --check   # verify it is current

# What was missing

There is a great deal of documentation about the *program* and, until this,
almost none about the *repository*. `docs/CONTRIBUTING.md` says how to build it
and what a change has to pass. The reference under `website/reference/` and in
the wiki is a page for every crate and every source file, generated from the
doc comments, which is the right place to read about one file and the wrong
place to find out which file to open.

What somebody new needs first is the shape: two binaries over thirteen crates,
which crate answers which question, what the build refuses to let them do, and
where to start reading for the change they came to make. That is this
document, and every list in it is read from the tree rather than typed, so it
describes the repository as it is rather than as it was.

# What is derived

* the crates, their descriptions and their sizes, from the workspace manifest
  and each crate's own `Cargo.toml`;
* the rules a build enforces, from the docstring of each guard in
  `tools/audit/`, so a guard added tomorrow appears here;
* every check and every generator, from `tools/verify.py`'s own lists, which
  is the tool that runs them;
* the tabs and the commands, from the window's tab list and the program's help.

The orientation prose is written, and the files it names are checked to exist.
A recipe that tells somebody to edit a file that has moved is worse than no
recipe, and this repository has published one of those before.

Pure standard library.
"""

from __future__ import annotations

import argparse
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))

sys.path.insert(0, HERE)
import generate as docs  # noqa: E402  (the path has to be set first)

sys.path.insert(0, os.path.join(ROOT, "tools"))
import verify as verifier  # noqa: E402  (same; its lists are read, not run)

OUT = "docs/DEVELOPERS.md"

BANNER = (
    "<!-- SPDX-License-Identifier: GPL-3.0-or-later -->\n"
    "<!-- GENERATED by tools/docs/developers.py. Do not edit: the lists are\n"
    "     read from the workspace, from tools/audit/ and from\n"
    "     tools/verify.py, and the prose lives in that generator. CI\n"
    "     verifies it with\n"
    "         python tools/docs/developers.py --check\n"
    "-->")

# Where to start reading, by what somebody came to change.
#
# Written, because it is a judgement about which of thirteen crates a question
# belongs to, and checked: every path named here must exist. A guide that sends
# a reader to a file that has moved wastes exactly the time it was written to
# save.
STARTING_POINTS = [
    ("Change what the veiling does to a voice",
     ["crates/veilvoice-core/src/chain.rs"],
     "The engine. `Deidentifier::process` is the whole of it: one block in, "
     "one block out, no allocation and no locking. Read the module comment "
     "before changing a number in it, because several of them are load "
     "bearing for the claim that the result cannot be inverted."),
    ("Add or change a command",
     ["crates/veilvoice-cli/src/main.rs"],
     "The `Command` enum is clap's tree and the program's own list in one "
     "place. A new variant needs a module beside it, a section in "
     "`docs/COMMANDS.md` through `tools/docs/commands.py`, and nothing else: "
     "two tests will tell you the rest."),
    ("Add or change a tab in the window",
     ["crates/veilvoice-gui/src/app.rs"],
     "`enum Tab` and `Tab::ALL` decide what the strip shows, and `Tab::key` "
     "names the screenshot and the anchor. Everything that counts the tabs, "
     "photographs them or documents them reads those three, so adding one is "
     "one edit and a capture run."),
    ("Change what a recording is sealed with",
     ["crates/veilvoice-crypto/src/container.rs",
      "crates/veilvoice-crypto/src/hybrid.rs"],
     "The container format and the X25519 plus ML-KEM combiner. Any change "
     "here changes files people already have, so the format carries a "
     "version and the readers accept the old one."),
    ("Change the app lock",
     ["crates/veilvoice-crypto/src/lock.rs",
      "crates/veilvoice-gui/src/security.rs"],
     "The stored verifier and the rate limit are in the first; the screen "
     "and the session passphrase are in the second. Both carry the same "
     "paragraph about what the lock is worth, and it is printed to the user "
     "rather than only written here."),
    ("Change the Studio, the vault or a take",
     ["crates/veilvoice-gui/src/studio.rs",
      "crates/veilvoice-gui/src/vault_store.rs"],
     "Veiling and recording are one session with two halves; the vault is "
     "sealed with both passphrases and opens with neither alone."),
    ("Change what the monitor can see",
     ["crates/veilvoice-watch/src/lib.rs"],
     "Six observers behind one interface, each of which says what it cannot "
     "see on the platform it is running on. An empty list from a blind "
     "observer is never presented as good news, and that rule is the reason "
     "this crate exists rather than a function."),
    ("Change the website or the documentation",
     ["docs/WEBSITE.md", "tools/verify.py"],
     "Nothing in `website/` or `docs/files/` is written by hand. The first "
     "says which script owns which page; the second runs all of them in "
     "dependency order and then checks the result."),
    ("Work out why a build is red",
     ["tools/verify.py", ".github/workflows/ci.yml"],
     "`python tools/verify.py --quick` runs everything except the three "
     "cargo steps, which is where nearly all the surprises are: a generated "
     "file left behind by a commit that added a source file."),
]

# The house rules, each with the file that holds the detail. The detail is not
# repeated here: `docs/CONTRIBUTING.md` is the source for it, and a second copy
# would be the thing that goes stale.
RULES = [
    ("No `unsafe`, anywhere",
     "Every crate carries `#![forbid(unsafe_code)]`. It is a publicly stated "
     "promise and it is load bearing: it is why a memory-safety claim about "
     "this program is checkable rather than a matter of trust. A feature that "
     "needs `unsafe` is a feature this project does not have, and two of them "
     "are named on the roadmap for exactly that reason."),
    ("Nothing in a realtime path allocates, locks or prints",
     "An audio callback runs on the operating system's audio thread with a "
     "deadline of a few milliseconds. Every buffer is sized before the stream "
     "starts, and `try_lock` and `try_push` are the only forms used. A test "
     "reads the callbacks themselves and fails naming the line."),
    ("A dependency says what it is for, on the line that declares it",
     "One sentence, at the moment the decision is made. If there is no "
     "sentence to write, that is the answer: it does not go in."),
    ("Where a fact exists twice, one copy is derived or checked",
     "A version number comes from `Cargo.toml`, a line count from the tool "
     "that counts, a list of binaries from the job that publishes them. "
     "Anything that cannot be derived is checked in CI, so drift fails a "
     "build rather than being found by a reader."),
    ("A change is not finished until everything describing it has changed",
     "The source, the doc comments, the generated documentation, the wiki, "
     "the website, the README, the guides, the roadmap, the packaging, the "
     "recorded sessions and the search index. The one exception is a record "
     "of the past: `CHANGELOG.md` and `docs/AUDIT.md` say what happened."),
    ("Every behavioural change carries a regression test",
     "And a fix carries its write-up in `docs/AUDIT.md`, which is where the "
     "reasoning behind a guard is kept so that the next person does not "
     "remove it as unnecessary."),
]

# What the doc comments are, and why they are not to be tidied away. This is
# addressed at a reader who is about to reformat a file.
COMMENTS = (
    "**The comments are the documentation, literally.** "
    "`tools/docs/generate.py` reads every `//!` and `///` in the workspace and "
    "writes a page per crate and per file from them, into `docs/files/`, into "
    "the GitHub wiki and into `website/reference/`. A module comment is the "
    "top of a published page; a function comment is an entry on it.\n"
    "\n"
    "So a comment removed is a page that loses a paragraph, and a comment "
    "rewritten to be shorter is a page that says less. The ratio of comment "
    "to code here is deliberately high and is not a defect to be cleaned up. "
    "Where a comment explains *why* a number is what it is, or why an obvious "
    "alternative was refused, it is usually recording a defect that was found "
    "the hard way and is written up in `docs/AUDIT.md` under a finding number.\n"
    "\n"
    "Add to them rather than replacing them. If a comment has become wrong, "
    "the fix is to say what is true now, in the same detail, in the same "
    "commit as the change that made it wrong.")


def read(relative):
    with io.open(os.path.join(ROOT, relative), encoding="utf-8") as handle:
        return handle.read()


def guards():
    """Every guard in `tools/audit/`, with the line it introduces itself by."""
    folder = os.path.join(ROOT, "tools", "audit")
    out = []
    for name in sorted(os.listdir(folder)):
        if not name.endswith(".py") or name.startswith("_"):
            continue
        text = read("tools/audit/%s" % name)
        match = re.search(r'^"""(.+?)(?:\n|""")', text, re.M | re.S)
        first = match.group(1).strip() if match else ""
        if not first:
            raise SystemExit(
                "tools/audit/%s has no docstring, so there is nothing to say\n"
                "  about what it enforces. Every guard in this repository "
                "explains itself\n  on its first line." % name)
        out.append(("tools/audit/%s" % name, first))
    if len(out) < 5:
        raise SystemExit("only %d guards were found, which cannot be right"
                         % len(out))
    return out


def crate_rows():
    """Every crate, its description and its size, from the workspace itself."""
    lines = docs.functional_lines_by_crate()
    rows = []
    for crate in docs.workspace_crates(ROOT):
        description = docs.crate_description(ROOT, crate) or ""
        count = lines.get(crate)
        rows.append((crate, description, count))
    return rows


def missing_paths():
    """Any file this document tells somebody to open that is not there."""
    wanted = []
    for _title, paths, _note in STARTING_POINTS:
        wanted.extend(paths)
    return [path for path in wanted
            if not os.path.exists(os.path.join(ROOT, path))]


def steps(argv):
    """A command from `tools/verify.py`'s lists, as a reader would type it."""
    out = []
    for part in argv:
        out.append("python" if part == sys.executable else part)
    return " ".join(out)


def document():
    gone = missing_paths()
    if gone:
        raise SystemExit(
            "docs/DEVELOPERS.md sends a reader to files that do not exist:\n"
            "  %s\n"
            "  Fix STARTING_POINTS in tools/docs/developers.py."
            % "\n  ".join(gone))

    rows = crate_rows()
    out = [BANNER, ""]
    out.append("# Working on VeilVoice: the shape of the repository")
    out.append("")
    out.append("This is the developer's way in. It is not the user guide "
               "([`docs/USER_GUIDE.md`](USER_GUIDE.md)) and not the reference "
               "(a page for every crate and every file, in the wiki and on "
               "the website). It is the part in between: what is where, what "
               "the build will refuse to let you do, and which file to open "
               "for the change you came to make.")
    out.append("")
    out.append("If you are reading this to work out whether you can "
               "understand this codebase without asking anybody: that is "
               "what it is for, and so is the rest of the documentation. "
               "Every claim below is generated from the tree, so it cannot "
               "describe a repository that no longer exists.")
    out.append("")

    out.append("## Two programs, one engine")
    out.append("")
    out.append("`veilvoice` is the command line and `veilvoice-gui` is the "
               "window. They are the only two binaries, and both are built "
               "from the same crates: the window is not a wrapper around the "
               "command line, and neither shells out to the other. What each "
               "one has that the other does not, and why, is "
               "[`docs/COMMANDS.md`](COMMANDS.md).")
    out.append("")
    out.append("The verifier is folded into both rather than shipped as a "
               "third binary, so a release is checked by the program it "
               "ships beside. `crates/veilvoice-verify/src/lib.rs` says what "
               "that cost and why it was worth it.")
    out.append("")

    out.append("## The crates")
    out.append("")
    out.append("Read from `Cargo.toml` and each crate's own manifest, with "
               "the functional line count from the tool that measures it. "
               "**Each crate's own `README.md` is the expansive version**: "
               "what it is for, what depends on it, and what depending on it "
               "commits you to.")
    out.append("")
    out.append("| Crate | What it is | Lines | Detail |")
    out.append("|---|---|---:|---|")
    for crate, description, count in rows:
        where = "fuzz" if crate == "fuzz" else "crates/%s" % crate
        readme = "[`%s/README.md`](../%s/README.md)" % (where, where)
        out.append("| `%s` | %s | %s | %s |"
                   % (crate, description or "-",
                      "{:,}".format(count) if count else "-", readme))
    out.append("")
    out.append("The same crates, drawn as a graph of what calls what, are on "
               "each crate's page in the reference. Those pages are generated "
               "from the doc comments, so they are as current as the code.")
    out.append("")

    out.append("## Where to start, by what you came to change")
    out.append("")
    for title, paths, note in STARTING_POINTS:
        listed = ", ".join("[`%s`](../%s)" % (path, path) for path in paths)
        out.append("### %s" % title)
        out.append("")
        out.append("%s" % listed)
        out.append("")
        out.append(note)
        out.append("")

    out.append("## The rules, and why they are rules")
    out.append("")
    out.append("The long version is [`docs/CONTRIBUTING.md`](CONTRIBUTING.md). "
               "These are the ones that will stop a change getting in.")
    out.append("")
    for title, detail in RULES:
        out.append("**%s.** %s" % (title, detail))
        out.append("")

    out.append("## What a build enforces, and which file enforces it")
    out.append("")
    out.append("Each of these is a script that fails a build and names the "
               "line. They are listed from the scripts themselves, so a guard "
               "added to `tools/audit/` appears here without anybody "
               "remembering to write it down.")
    out.append("")
    out.append("| Guard | What it will not let you do |")
    out.append("|---|---|")
    for path, first in guards():
        out.append("| [`%s`](../%s) | %s |" % (path, path, first.rstrip(".")))
    out.append("")
    out.append("Every one of them was written after something got through. "
               "The reasoning is in [`docs/AUDIT.md`](AUDIT.md) under a "
               "finding number, which is worth reading before deciding a "
               "guard is unnecessary.")
    out.append("")

    out.append("## Running the checks")
    out.append("")
    out.append("One command runs the lot, in dependency order, and then "
               "verifies its own output:")
    out.append("")
    out.append("```bash")
    out.append("python tools/verify.py            # everything")
    out.append("python tools/verify.py --quick    # everything but the three "
               "cargo steps")
    out.append("python tools/verify.py --check    # verify, regenerate "
               "nothing")
    out.append("```")
    out.append("")
    out.append("`--quick` is the one to run before a push that touches no "
               "Rust. The three it skips are the slowest and almost never the "
               "failures:")
    out.append("")
    for label, argv in verifier.CARGO:
        out.append("- **%s**: `%s`" % (label, steps(argv)))
    out.append("")
    out.append("What it regenerates, in the order it has to:")
    out.append("")
    for label, argv in verifier.GENERATORS:
        out.append("- **%s**: `%s`" % (label, steps(argv)))
    out.append("")
    out.append("And what it then checks:")
    out.append("")
    for label, argv in verifier.CHECKS:
        out.append("- **%s**: `%s`" % (label, steps(argv)))
    out.append("")

    out.append("## The comments")
    out.append("")
    out.append(COMMENTS)
    out.append("")

    out.append("## Where to read next")
    out.append("")
    out.append("- [`docs/CONTRIBUTING.md`](CONTRIBUTING.md): building, the "
               "house style, and what a change has to pass.")
    out.append("- [`docs/COMMANDS.md`](COMMANDS.md): every command, and the "
               "same job in the window.")
    out.append("- [`docs/WEBSITE.md`](WEBSITE.md): both editions of the site "
               "and the script that writes each page.")
    out.append("- [`docs/AUDIT.md`](AUDIT.md): every defect found and fixed, "
               "in order, which is the fastest way to learn what this code is "
               "careful about.")
    out.append("- [`docs/USING_THE_CRATES.md`](USING_THE_CRATES.md): "
               "depending on one of these crates from your own project.")
    out.append("- [`ROADMAP.md`](../ROADMAP.md): what is done, what is next, "
               "and what is deliberately not being done.")
    out.append("")
    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="verify the document is current, write nothing")
    args = parser.parse_args()

    text = document()
    path = os.path.join(ROOT, OUT)
    if args.check:
        current = read(OUT) if os.path.exists(path) else None
        if current != text:
            print("%s is out of date." % OUT)
            print("  Run: python tools/docs/developers.py")
            return 1
        print("  the developer guide matches the tree")
        return 0
    with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    print("  wrote %s (%d crates, %d guards)" % (OUT, len(crate_rows()),
                                                 len(guards())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
