#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""One guide per program, assembled from the one guide that describes them all.

    python tools/docs/guides.py           # write them
    python tools/docs/guides.py --check   # verify they are current

# Why three files, and why they are not written three times

A release ships three programs and somebody arriving with one of them in front
of them should not have to read about the other two to find their part.
`docs/USER_GUIDE.md` is the whole story and stays the whole story; these are
views of it, one per program, for the wiki and for the archive.

**They are assembled, never copied.** Three hand-maintained descriptions of one
application is the shape of half the findings in this repository: a document
that describes the program, with nothing comparing the two, quietly going stale
in one place and not the others. Here there is one source, and `--check`
regenerates into memory and compares, so CI fails if a guide and its source
have parted company.

# What each one is for

The split is by *what the reader has*, not by subject:

- somebody at a terminal wants the command line and the walkthrough;
- somebody looking at a window wants the tabs, the lock and the vaults;
- somebody who has just downloaded an archive and has not run anything yet
  wants the verifier, and wants it before they trust either of the others.

Pure standard library, like the rest of the documentation tooling.
"""

import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SOURCE = os.path.join(ROOT, "docs", "USER_GUIDE.md")

# Each guide: the file to write, the wiki page, a title, an opening, and the
# sections of the user guide it is made of, by the words in their headings.
GUIDES = [
    {
        "file": "docs/GUIDE_CLI.md",
        "wiki": "wiki/Guide-command-line.md",
        "title": "VeilVoice: the command line",
        "program": "`veilvoice`",
        "opening":
            "Everything the application does, over SSH, in a container, in a "
            "script, or on a machine with no graphics toolkit at all. If you "
            "have a terminal and nothing else, this is your half of VeilVoice.\n"
            "\n"
            "Every command takes `--help`, and the help is the reference; this "
            "is the part that says what to reach for and why.",
        "sections": [
            "Installing",
            "The three programs, and which one you want",
            "The command line",
            "An interview, start to finish",
            "Things VeilVoice will not do",
        ],
    },
    {
        "file": "docs/GUIDE_GUI.md",
        "wiki": "wiki/Guide-desktop-app.md",
        "title": "VeilVoice: the desktop application",
        "program": "`veilvoice-gui`",
        "opening":
            "The window. The same engine as the command line with somewhere to "
            "click, plus the things that only make sense with a screen: live "
            "level meters, the app lock, and the microphone monitor.\n"
            "\n"
            "One tab for each thing it does. Every one of them is below, and "
            "`veilvoice-gui --tab <name>` opens the window on one directly.",
        "sections": [
            "Installing",
            "The three programs, and which one you want",
            "The desktop app",
            "The app lock",
            "Locking the window when you walk away",
            "VeilVoice checking its own files",
            "Saving into a Cryptomator vault or a VeraCrypt volume",
            "Things VeilVoice will not do",
        ],
    },
    {
        "file": "docs/GUIDE_VERIFY.md",
        "wiki": "wiki/Guide-verifier.md",
        "title": "VeilVoice: checking a download",
        "program": "`veilvoice-verify`",
        "opening":
            "Read this one first. It is about deciding whether the archive you "
            "just downloaded is the one that was published, and it is a "
            "separate program so that it is usable *before* you trust the "
            "other two.\n"
            "\n"
            "The short version: unpack the archive, run `veilvoice-verify` "
            "inside the folder, read the verdict.",
        "sections": [
            "The three programs, and which one you want",
            "The verifier, `veilvoice-verify`",
            "Getting help, and checking for yourself",
        ],
    },
]

BANNER = (
    "<!-- SPDX-License-Identifier: GPL-3.0-or-later -->\n"
    "<!-- GENERATED by tools/docs/guides.py from docs/USER_GUIDE.md.\n"
    "     Do not edit: edit the section in the user guide and run the tool.\n"
    "     Verified in CI with `python tools/docs/guides.py --check`. -->\n"
)


def read(path):
    with io.open(path, encoding="utf-8") as handle:
        return handle.read().replace("\r\n", "\n")


def sections(text):
    """Every `## ` section of the guide, keyed by its heading without a number.

    A section runs to the next `## `, so its `### ` subsections come with it,
    which is the whole point: the tabs belong with the tab section.
    """
    found = {}
    order = []
    current = None
    body = []
    for line in text.split("\n"):
        if line.startswith("## "):
            if current is not None:
                found[current] = "\n".join(body).strip("\n")
            # "## 5.7 Saving into a vault" -> "Saving into a vault"
            current = re.sub(r"^\d+(?:\.\d+)*\.?\s*", "", line[3:].strip())
            order.append(current)
            body = [line]
            continue
        if current is not None:
            body.append(line)
    if current is not None:
        found[current] = "\n".join(body).strip("\n")
    return found, order


def renumber(body, number):
    """The section heading, with the guide's own numbering replaced."""
    lines = body.split("\n")
    if lines and lines[0].startswith("## "):
        title = re.sub(r"^\d+(?:\.\d+)*\.?\s*", "", lines[0][3:].strip())
        lines[0] = "## %d. %s" % (number, title)
    return "\n".join(lines)


# A link to another file in `docs/`, written as a bare file name because that
# is what resolves when the guide is sitting in `docs/`.
NEIGHBOUR = re.compile(r"\]\((?!https?:|#|/)([A-Za-z0-9_.-]+\.md)(#[^)]*)?\)")


def for_the_wiki(page):
    """The same page, with its links rewritten for a flat namespace.

    The wiki has no directories: every page is a name. A guide written for
    `docs/` links to its neighbours as `REPRODUCIBLE_BUILDS.md`, which is
    right there and wrong in the wiki, where it resolves to a page that does
    not exist.

    Rewritten to absolute URLs into the repository rather than to wiki pages,
    because most of those neighbours have no wiki page: the reader is sent to
    the real document instead of to a dead end.
    """
    return NEIGHBOUR.sub(
        lambda m: "](https://github.com/tilas01/veilvoice/blob/main/docs/%s%s)"
                  % (m.group(1), m.group(2) or ""),
        page)


def build():
    text = read(SOURCE)
    found, _order = sections(text)

    out = {}
    for guide in GUIDES:
        missing = [name for name in guide["sections"] if name not in found]
        if missing:
            raise SystemExit(
                "docs/USER_GUIDE.md no longer has these sections, which %s is\n"
                "assembled from: %s\n"
                "Either they were renamed, in which case update GUIDES in\n"
                "tools/docs/guides.py, or the parser needs fixing."
                % (guide["file"], ", ".join(repr(m) for m in missing)))

        parts = [
            BANNER,
            "# %s" % guide["title"],
            "",
            "**%s.** %s" % (guide["program"], guide["opening"]),
            "",
            "The whole story, including the parts about the other two programs, "
            "is in [`USER_GUIDE.md`](USER_GUIDE.md). This is the same text, "
            "narrowed to one program.",
            "",
            "---",
            "",
        ]
        for number, name in enumerate(guide["sections"], start=1):
            parts.append(renumber(found[name], number))
            parts.append("")
            parts.append("---")
            parts.append("")
        # The last rule is a separator with nothing after it.
        while parts and parts[-1] in ("", "---"):
            parts.pop()
        parts.append("")

        page = "\n".join(parts)
        out[guide["file"]] = page
        out[guide["wiki"]] = for_the_wiki(page)
    return out


def main():
    check = "--check" in sys.argv
    files = build()

    problems = []
    for rel, text in sorted(files.items()):
        path = os.path.join(ROOT, rel.replace("/", os.sep))
        if check:
            try:
                with io.open(path, encoding="utf-8", newline="") as handle:
                    actual = handle.read()
            except OSError:
                problems.append("%s: missing" % rel)
                continue
            if actual.replace("\r\n", "\n") != text:
                problems.append("%s: differs from docs/USER_GUIDE.md" % rel)
        else:
            with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
                handle.write(text)

    if check:
        if problems:
            for line in problems:
                print("  MISMATCH %s" % line)
            print()
            print("Run 'python tools/docs/guides.py' and commit the result.")
            return 1
        print("  %d per-program guides match the user guide" % len(files))
        return 0

    print("  wrote %d per-program guides from docs/USER_GUIDE.md" % len(files))
    return 0


if __name__ == "__main__":
    sys.exit(main())
