#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""A page, a banner and a workchart for every file the website is made of.

    python tools/docs/sources.py           # write the pages
    python tools/docs/sources.py --check   # verify they are current

`tools/docs/generate.py` does this for every crate and every `.rs` file. The
website's own source had nothing: ten files that the site explicitly invites
people to open and read, with no page, no picture and no index. This is the
same treatment for them.

# Two explanations, and only one of them can be generated

Every page here says what a file does **technically**, and then says the same
thing **in plain words**. The technical half is derived: the functions, what
calls what, how long it is. The plain half cannot be: a generator that wrote
"this file handles theme switching" from a filename would be padding, and a
reader can tell.

So the plain-words paragraph is **written in the file itself**, under an
`In plain words` heading in its header comment, and this tool **refuses to
generate a page without one**. That keeps the explanation beside the code it
explains, makes it reviewable in a diff of that code, and means it cannot
quietly rot into describing something the file stopped doing.

# The workchart is syntactic, and says so

Functions are found by their declarations and edges by looking for a callee's
name inside a caller's body. That is a *reading* of the text, not a resolved
call graph: a call made through a variable, or built at run time, will not
appear. `generate.py` documents the same limit for Rust and for the same
reason, because a diagram derived from source is worth having precisely because
nobody hand-maintained it, and worth doubting for exactly this.

CSS has no functions. Its chart is the file's own section comments, in order,
which is the structure a stylesheet actually has.

Pure standard library.
"""

import argparse
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))

MARKER = "GENERATED by tools/docs/sources.py"

# What is covered. The website's own source, which is what was asked for: the
# scripts the pages run and the stylesheets they are drawn with.
ROOTS = ["website/js", "website/css"]

# The heading a file's plain-words paragraph lives under.
PLAIN_HEADING = "In plain words"

sys.path.insert(0, HERE)
import generate as docs  # noqa: E402  (the path has to be set first)


# --- reading a file ---------------------------------------------------------

def header_comment(text, kind):
    """The comment block at the top of a file, as lines of prose.

    Stops at the first line that is not part of it, so a file's header is
    whatever the author wrote before the code starts and nothing else.
    """
    lines = []
    if kind == "css":
        start = text.find("/*")
        if start != 0:
            return []
        end = text.find("*/")
        if end < 0:
            return []
        for raw in text[2:end].split("\n"):
            raw = raw.strip()
            if raw.startswith("*"):
                raw = raw[1:]
            lines.append(raw.strip())
    else:
        for raw in text.split("\n"):
            stripped = raw.strip()
            if not stripped.startswith("//"):
                if stripped == "":
                    # A blank line inside the header is part of it; a blank
                    # line after the header has already ended the block.
                    if lines:
                        break
                    continue
                break
            lines.append(stripped[2:].strip())
    # The licence line is machinery, not prose.
    while lines and lines[0].startswith("SPDX-License-Identifier"):
        lines.pop(0)
    while lines and not lines[0]:
        lines.pop(0)
    while lines and not lines[-1]:
        lines.pop()
    return lines


def split_plain(lines):
    """Separate the technical header from the plain-words paragraph.

    Returns `(technical, plain)`. `plain` is empty when the file has not been
    given one, which is what `--check` refuses.
    """
    for index, line in enumerate(lines):
        if line.rstrip(":").strip().lower() == PLAIN_HEADING.lower():
            technical = lines[:index]
            plain = lines[index + 1 :]
            while technical and not technical[-1]:
                technical.pop()
            while plain and not plain[0]:
                plain.pop(0)
            return technical, plain
    return lines, []


JS_DECLARATIONS = [
    # `function name(`
    re.compile(r"^\s*function\s+([A-Za-z_$][\w$]*)\s*\("),
    # `var name = function(` and `const name = (a) =>`
    re.compile(r"^\s*(?:var|let|const)\s+([A-Za-z_$][\w$]*)\s*=\s*(?:function|\()"),
    # `name: function(` inside an object
    re.compile(r"^\s*([A-Za-z_$][\w$]*)\s*:\s*function\s*\("),
]

PY_DECLARATION = re.compile(r"^\s*def\s+([A-Za-z_][\w]*)\s*\(")

# `/* ---------- name ---------- */`, which is how this project's stylesheets
# mark their sections.
CSS_SECTION = re.compile(r"/\*\s*-{3,}\s*(.+?)\s*-{3,}\s*\*/")


def functions_in(text, kind):
    """Every function this file declares, with the line it starts on."""
    if kind == "css":
        found = []
        for number, line in enumerate(text.split("\n"), start=1):
            match = CSS_SECTION.search(line)
            if match:
                found.append((match.group(1), number))
        return found

    patterns = [PY_DECLARATION] if kind == "py" else JS_DECLARATIONS
    found = []
    seen = set()
    for number, line in enumerate(text.split("\n"), start=1):
        for pattern in patterns:
            match = pattern.match(line)
            if match:
                name = match.group(1)
                if name not in seen:
                    seen.add(name)
                    found.append((name, number))
                break
    return found


def bodies(text, names):
    """Roughly, the text belonging to each function.

    From one declaration to the next. Crude, and honest about being crude: a
    nested function's body is counted as part of its parent's, which can only
    ever *add* an edge that a reader can see is there. It never removes one.
    """
    lines = text.split("\n")
    starts = sorted((line, name) for name, line in names)
    out = {}
    for index, (line, name) in enumerate(starts):
        end = starts[index + 1][0] - 1 if index + 1 < len(starts) else len(lines)
        out[name] = "\n".join(lines[line - 1 : end])
    return out


def call_graph(text, kind):
    """Nodes and edges, in the shape `generate.py`'s drawing code wants."""
    declared = functions_in(text, kind)
    if kind == "css" or not declared:
        return [], []

    names = [name for name, _ in declared]
    where = dict(declared)
    inside = bodies(text, declared)
    nodes = []
    for name in names[: docs.MAX_DIAGRAM_NODES]:
        nodes.append(
            {
                "id": "n_%s" % re.sub(r"\W", "_", name),
                "label": [name, "line %d" % where[name]],
                "role": "function",
            }
        )
    drawn = {node["label"][0] for node in nodes}

    edges = []
    for caller in names:
        if caller not in drawn:
            continue
        body = inside.get(caller, "")
        for callee in names:
            if callee == caller or callee not in drawn:
                continue
            if re.search(r"\b%s\s*\(" % re.escape(callee), body):
                edges.append(
                    (
                        "n_%s" % re.sub(r"\W", "_", caller),
                        "n_%s" % re.sub(r"\W", "_", callee),
                    )
                )
    return nodes, edges


def kind_of(path):
    if path.endswith(".css"):
        return "css"
    if path.endswith(".py"):
        return "py"
    return "js"


def slug_of(rel):
    return rel.replace("/", "-").replace(".", "-")


def covered():
    """Every file this tool documents, as repo-relative paths, sorted."""
    found = []
    for root in ROOTS:
        directory = os.path.join(ROOT, root.replace("/", os.sep))
        if not os.path.isdir(directory):
            continue
        for name in sorted(os.listdir(directory)):
            if name.endswith((".js", ".css", ".py")):
                found.append("%s/%s" % (root, name))
    return found


# --- writing ----------------------------------------------------------------

NOTE = (
    "<!-- SPDX-License-Identifier: GPL-3.0-or-later -->\n"
    "<!-- GENERATED by tools/docs/sources.py from the header comment in the\n"
    "     source. Do not edit this file: edit the comment at the top of the\n"
    "     source file and run the generator again. CI verifies it with\n"
    "         python tools/docs/sources.py --check\n"
    "-->\n"
)


def paragraphs(lines):
    """Comment lines as Markdown paragraphs, keeping blank-line breaks."""
    out = []
    block = []
    for line in lines:
        if line:
            block.append(line)
        elif block:
            out.append(" ".join(block))
            block = []
    if block:
        out.append(" ".join(block))
    return out


def markdown_page(colours, rel, text):
    kind = kind_of(rel)
    header = header_comment(text, kind)
    technical, plain = split_plain(header)
    declared = functions_in(text, kind)
    nodes, edges = call_graph(text, kind)
    slug = slug_of(rel)
    lines = text.count("\n") + 1

    out = [NOTE]
    out.append(
        '<p align="center">\n'
        '  <img src="../../assets/sources/%s.svg" alt="%s" width="100%%">\n'
        "</p>\n" % (slug, rel)
    )
    out.append("# `%s`\n" % rel)
    out.append(
        "[the source](https://github.com/%s/blob/%s/%s) &middot; %d lines\n"
        % (docs.REPO, docs.REF, rel, lines)
    )

    out.append("## What it does\n")
    if technical:
        for para in paragraphs(technical):
            out.append(para + "\n")
    else:
        out.append("_This file has no header comment yet._\n")

    out.append("## %s\n" % PLAIN_HEADING)
    for para in paragraphs(plain):
        out.append(para + "\n")

    if kind == "css":
        out.append("## The sections it is made of\n")
        if declared:
            out.append("| Section | Line |")
            out.append("|---|---:|")
            for name, number in declared:
                out.append("| %s | %d |" % (name.replace("|", "\\|"), number))
            out.append("")
        else:
            out.append("_This stylesheet has no section markers._\n")
    else:
        out.append("## What calls what\n")
        out.append(
            "Read out of the source: an edge means the callee's name appears,\n"
            "called, inside the caller's body. It is a syntactic reading, not a\n"
            "resolved one, so a call made through a variable will not appear.\n"
        )
        out.append(
            '<p align="center">\n'
            '  <img src="../../assets/sources/%s-chart.svg" alt="what calls what in %s" '
            'width="%d">\n'
            "</p>\n" % (slug, rel, docs.DIAGRAM_MAX_W)
        )
        if declared:
            out.append("| Function | Line |")
            out.append("|---|---:|")
            for name, number in declared:
                out.append("| `%s` | %d |" % (name, number))
            out.append("")

    return docs.tidy("\n".join(out))


def html_page(colours, rel, text, fingerprint):
    kind = kind_of(rel)
    header = header_comment(text, kind)
    technical, plain = split_plain(header)
    declared = functions_in(text, kind)
    nodes, edges = call_graph(text, kind)
    slug = slug_of(rel)
    lines = text.count("\n") + 1

    body = []
    body.append(
        '<p><img src="../../assets/sources/%s.svg" alt="%s" '
        'style="width:100%%;height:auto"></p>' % (slug, docs.esc(rel))
    )
    body.append("<h1><code>%s</code></h1>" % docs.esc(rel))
    body.append(
        '<p style="color:var(--muted)"><a href="index.html">the website\'s source</a> '
        "&middot; %d lines &middot; "
        '<a href="https://github.com/%s/blob/%s/%s" rel="noopener noreferrer">'
        "read it on GitHub</a></p>" % (lines, docs.REPO, docs.REF, docs.esc(rel))
    )

    body.append('<section id="s-what">')
    body.append("<h2>WHAT IT DOES</h2>")
    for para in paragraphs(technical) or ["This file has no header comment yet."]:
        body.append("<p>%s</p>" % docs.inline_html(para))
    body.append("</section>")

    body.append('<section id="s-plain">')
    body.append("<h2>%s</h2>" % PLAIN_HEADING.upper())
    for para in paragraphs(plain):
        body.append("<p>%s</p>" % docs.inline_html(para))
    body.append("</section>")

    if kind == "css":
        body.append('<section id="s-sections">')
        body.append("<h2>THE SECTIONS IT IS MADE OF</h2>")
        body.append("<table><tr><th>Section</th><th>Line</th></tr>")
        for name, number in declared:
            body.append("<tr><td>%s</td><td>%d</td></tr>" % (docs.esc(name), number))
        body.append("</table>")
        body.append("</section>")
    else:
        body.append('<section id="s-calls">')
        body.append("<h2>WHAT CALLS WHAT</h2>")
        body.append('<div class="diagram">')
        body.append(docs.diagram_svg(colours, nodes, edges).rstrip("\n"))
        body.append("</div>")
        body.append(
            '<p style="color:var(--muted);font-size:13px">Read out of the source: an '
            "edge means the callee&rsquo;s name appears, called, inside the caller&rsquo;s "
            "body. A syntactic reading, not a resolved one.</p>"
        )
        if declared:
            body.append("<table><tr><th>Function</th><th>Line</th></tr>")
            for name, number in declared:
                body.append(
                    "<tr><td><code>%s</code></td><td>%d</td></tr>"
                    % (docs.esc(name), number)
                )
            body.append("</table>")
        body.append("</section>")

    return docs.html_page(
        colours,
        2,
        "%s · VeilVoice" % rel,
        "What %s does, and the same thing in plain words." % rel,
        # A list of lines, not a joined string. `html_page` does `out.extend`,
        # so a string is extended one character at a time -- the page rendered
        # its own markup as spaced-out text, which is precisely what that looks
        # like, and it took looking at the page to see it.
        body,
        fingerprint,
    )


def wiki_page_name(rel):
    """What the GitHub wiki calls a page for this file.

    The wiki has one flat namespace, so a page name has to carry the path. The
    crate pages already use `Crate-x` and `File-crate-stem`; these use
    `Source-website-js-theme-js` for the same reason and by the same rule.
    """
    return "Source-%s" % slug_of(rel)


def wiki_page(rel, text):
    """One source file's page, for the GitHub wiki.

    The same content as the repository's copy, with wiki links and raw image
    URLs. Generated from the same header comment as the other two, so the three
    cannot disagree -- which is the whole reason any of this is generated.
    """
    kind = kind_of(rel)
    header = header_comment(text, kind)
    technical, plain = split_plain(header)
    declared = functions_in(text, kind)
    slug = slug_of(rel)
    lines = text.count("\n") + 1

    out = []
    out.append(
        "<!-- GENERATED by tools/docs/sources.py from the header comment in the "
        "source. Do not edit: edit the source file and run the generator. -->"
    )
    out.append("![%s](%sassets/sources/%s.svg)\n" % (rel, docs.RAW, slug))
    out.append("# `%s`\n" % rel)
    out.append(
        "[[The website's source|Source-index]] &middot; %d lines &middot; "
        "[read the source](https://github.com/%s/blob/%s/%s)\n"
        % (lines, docs.REPO, docs.REF, rel)
    )

    out.append("## What it does\n")
    for para in paragraphs(technical) or ["_This file has no header comment yet._"]:
        out.append(para + "\n")

    out.append("## %s\n" % PLAIN_HEADING)
    for para in paragraphs(plain):
        out.append(para + "\n")

    if kind == "css":
        out.append("## The sections it is made of\n")
        out.append("| Section | Line |")
        out.append("|---|---:|")
        for name, number in declared:
            out.append("| %s | %d |" % (name.replace("|", "\\|"), number))
        out.append("")
    else:
        out.append("## What calls what\n")
        out.append(
            "Read out of the source: an edge means the callee's name appears,\n"
            "called, inside the caller's body. A syntactic reading, not a\n"
            "resolved one.\n"
        )
        out.append(
            "![what calls what in %s](%sassets/sources/%s-chart.svg)\n"
            % (rel, docs.RAW, slug)
        )
        if declared:
            out.append("| Function | Line |")
            out.append("|---|---:|")
            for name, number in declared:
                out.append("| `%s` | %d |" % (name, number))
            out.append("")

    return docs.tidy("\n".join(out))


def wiki_index(files):
    out = [
        "<!-- GENERATED by tools/docs/sources.py from the header comments in the "
        "source. Do not edit: edit the source files and run the generator. -->"
    ]
    out.append("# The website's own source\n")
    out.append(
        "Every script and stylesheet this site is made of, each explained "
        "technically and then in plain words. The same pages are in the "
        "repository and on the website; all three come out of one generator, so "
        "they cannot disagree.\n"
    )
    out.append("| File | Lines | What it is |")
    out.append("|---|---:|---|")
    for rel, text in files:
        technical, _ = split_plain(header_comment(text, kind_of(rel)))
        summary = (paragraphs(technical) or [""])[0].split(". ")[0].rstrip(".")
        out.append(
            "| [[`%s`|%s]] | %d | %s |"
            % (rel, wiki_page_name(rel), text.count("\n") + 1, summary.replace("|", "\\|"))
        )
    out.append("")
    return docs.tidy("\n".join(out))


def index_markdown(files):
    out = [NOTE]
    out.append("# The website's own source\n")
    out.append(
        "Ten files the site invites you to open and read, each with a page of its\n"
        "own: what it does, and the same thing in plain words.\n"
    )
    out.append("| File | Lines | What it is |")
    out.append("|---|---:|---|")
    for rel, text in files:
        header = header_comment(text, kind_of(rel))
        technical, _ = split_plain(header)
        summary = (paragraphs(technical) or [""])[0]
        summary = summary.split(". ")[0].rstrip(".").replace("|", "\\|")
        out.append(
            "| [`%s`](%s.md) | %d | %s |"
            % (rel, slug_of(rel), text.count("\n") + 1, summary)
        )
    out.append("")
    return docs.tidy("\n".join(out))


def index_html(colours, files, fingerprint):
    body = ["<h1>The website&rsquo;s own source</h1>"]
    body.append(
        '<p class="lead">Ten files the site invites you to open and read, each with '
        "a page of its own: what it does, and the same thing in plain words.</p>"
    )
    body.append("<table><tr><th>File</th><th>Lines</th><th>What it is</th></tr>")
    for rel, text in files:
        header = header_comment(text, kind_of(rel))
        technical, _ = split_plain(header)
        summary = (paragraphs(technical) or [""])[0].split(". ")[0].rstrip(".")
        body.append(
            '<tr><td><a href="%s.html"><code>%s</code></a></td><td>%d</td><td>%s</td></tr>'
            % (slug_of(rel), docs.esc(rel), text.count("\n") + 1, docs.inline_html(summary))
        )
    body.append("</table>")
    return docs.html_page(
        colours,
        2,
        "The website's source · VeilVoice",
        "Every file the website is made of, explained twice.",
        # A list of lines, not a joined string. `html_page` does `out.extend`,
        # so a string is extended one character at a time -- the page rendered
        # its own markup as spaced-out text, which is precisely what that looks
        # like, and it took looking at the page to see it.
        body,
        fingerprint,
    )


def outputs():
    """Every file this generator owns, as {relative path: text}, and any refusal."""
    colours = docs.palette(ROOT)
    fingerprint = docs.read(
        os.path.join(ROOT, "website", "assets", "fingerprint.txt")
    ).strip()

    files = {}
    loaded = []
    missing_plain = []

    for rel in covered():
        with io.open(os.path.join(ROOT, rel.replace("/", os.sep)), encoding="utf-8") as h:
            text = h.read()
        loaded.append((rel, text))
        header = header_comment(text, kind_of(rel))
        _, plain = split_plain(header)
        if not plain:
            missing_plain.append(rel)
            continue

        slug = slug_of(rel)
        files["assets/sources/%s.svg" % slug] = docs.banner_svg(
            colours, rel, (paragraphs(header) or [""])[0][:96], kind_of(rel)
        )
        if kind_of(rel) != "css":
            nodes, edges = call_graph(text, kind_of(rel))
            files["assets/sources/%s-chart.svg" % slug] = docs.diagram_svg(
                colours, nodes, edges
            )
        files["docs/source/%s.md" % slug] = markdown_page(colours, rel, text)
        files["wiki/%s.md" % wiki_page_name(rel)] = wiki_page(rel, text)
        files["website/reference/source/%s.html" % slug] = html_page(
            colours, rel, text, fingerprint
        )

    if missing_plain:
        return {}, missing_plain

    files["docs/source/index.md"] = index_markdown(loaded)
    files["wiki/Source-index.md"] = wiki_index(loaded)
    files["website/reference/source/index.html"] = index_html(
        colours, loaded, fingerprint
    )

    # The site serves only what is under `website/`, so the pictures have to
    # exist there too. Written by the generator that owns them, for the reason
    # `assets/generate.py` learned the hard way -- finding F-41 was a second
    # copy drifting with nothing able to tell.
    for name in list(files):
        if name.startswith("assets/sources/"):
            files["website/" + name] = files[name]

    return files, []


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    files, missing = outputs()
    if missing:
        print("  these files have no '%s' section in their header comment:" % PLAIN_HEADING)
        for rel in missing:
            print("    %s" % rel)
        print()
        print("  Every page here says what a file does technically and then says the")
        print("  same thing in plain words. The plain half cannot be generated -- a")
        print("  sentence assembled from a filename is padding, and a reader can tell.")
        print("  Add it to the file's own header comment, under that heading.")
        return 1

    if args.check:
        problems = []
        for rel, text in sorted(files.items()):
            path = os.path.join(ROOT, rel.replace("/", os.sep))
            try:
                with io.open(path, encoding="utf-8") as handle:
                    if handle.read() != text:
                        problems.append(rel)
            except OSError as error:
                problems.append("%s (%s)" % (rel, error))
        # A page this tool used to write and no longer does would otherwise sit
        # in the tree for ever, describing a file that has been deleted. The
        # same sweep `generate.py` runs, over the directories this one owns --
        # and the reason that tool can safely skip `reference/source/`.
        for base in ("docs/source", "website/reference/source", "assets/sources",
                     "website/assets/sources"):
            directory = os.path.join(ROOT, base.replace("/", os.sep))
            if not os.path.isdir(directory):
                continue
            for current, _, names in os.walk(directory):
                for name in names:
                    rel = os.path.relpath(os.path.join(current, name), ROOT)
                    rel = rel.replace(os.sep, "/")
                    if rel not in files:
                        problems.append("%s (no longer produced)" % rel)

        # The wiki is one flat namespace shared with `generate.py`, so the
        # sweep there is over a name prefix rather than a directory. That is why
        # these pages are called `Source-` and nothing else in `wiki/` is.
        wiki = os.path.join(ROOT, "wiki")
        if os.path.isdir(wiki):
            for name in sorted(os.listdir(wiki)):
                rel = "wiki/%s" % name
                if name.startswith("Source-") and rel not in files:
                    problems.append("%s (no longer produced)" % rel)

        if problems:
            for rel in problems:
                print("  MISMATCH %s" % rel)
            print()
            print("  Run 'python tools/docs/sources.py' and commit the result.")
            return 1
        print("  %d source pages match their files" % len(files))
        return 0

    for rel, text in sorted(files.items()):
        path = os.path.join(ROOT, rel.replace("/", os.sep))
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
    print("  wrote %d files for %d source files" % (len(files), len(covered())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
