#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""
The wiki's landing page, its sidebar, and a page for every prose document.

    python tools/docs/wiki.py           # write them
    python tools/docs/wiki.py --check   # verify they are current

# What was already there, and what was missing

`tools/docs/generate.py` has long written the reference half of the wiki: a page
per crate and per source file, 180 of them, each with its banner, its flowchart
and its tables. `tools/docs/guides.py` adds three, one per program.

None of that is a way *in*. A GitHub wiki opens on a page called `Home`, and
there was no `Home`; it shows a sidebar on every page if one is called
`_Sidebar`, and there was no `_Sidebar`. A reader arriving at the wiki landed on
whichever page GitHub picked and had no list of the rest. Meanwhile the prose
that answers the questions people actually arrive with, how to build it, how to
check a download reproduces, how to contribute, was in `docs/` and not in the
wiki at all.

# Why the prose is converted rather than written again

`docs/` is the source. These pages are that text with its links rewritten for a
flat namespace, so there is no second copy to go stale: `--check` regenerates
into memory and compares, and CI fails on a difference. The same decision, for
the same reason, as every other generator here.

# What the link rewriting has to handle

The wiki has no directories. A document in `docs/` links to its neighbour as
`WHITEPAPER.md`, which is right in `docs/` and wrong in the wiki. Three cases:

  * a neighbour that has a wiki page becomes a `[[wiki link]]`,
  * a neighbour that does not becomes an absolute URL into the repository,
  * a link to a file elsewhere in the tree becomes an absolute URL too.

The third matters more than it looks: a relative link to `crates/...` or
`tools/...` resolves, in a wiki, to a wiki page of that name, which does not
exist. Silently. That is the failure this rewriting exists to prevent.

Pure standard library.
"""

from __future__ import annotations

import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
WIKI = os.path.join(ROOT, "wiki")
REPO = "https://github.com/tilas01/veilvoice"

BANNER = ("<!-- GENERATED by tools/docs/wiki.py from the documents in the "
          "repository. Do not edit: edit the source document and run the "
          "generator. -->")

# Every prose document that becomes a wiki page: where it lives, the page it
# becomes, and the one line the landing page and sidebar describe it by.
#
# The order is the order a reader needs them, not alphabetical: what the thing
# is, then how to get it, then how to check it, then how to work on it.
DOCUMENTS = [
    ("README.md", "What VeilVoice is",
     "The whole project in one page: what it does, what it refuses to claim, "
     "and how to install it"),
    ("docs/USER_GUIDE.md", "User guide",
     "Every screen and every command, in order"),
    ("docs/INSTALL.md", "Installing",
     "Per operating system, with the verification step in place rather than "
     "bolted on"),
    ("docs/FAQ.md", "Questions",
     "The questions people actually ask"),
    ("docs/WHITEPAPER.md", "How the veiling works",
     "What is done to a voice, why it cannot be undone, and what this is not"),
    ("docs/GUIDE_VERIFY.md", "Checking a download",
     "The signature chain end to end, and what each verdict is worth"),
    ("docs/REPRODUCIBLE_BUILDS.md", "Building it yourself",
     "Building from source and comparing the result against what was "
     "published"),
    ("docs/SELF_SIGNING.md", "The code-signing certificate",
     "What it is, and importing it"),
    ("docs/PACKAGING.md", "Packaging",
     "The deb, the RPM, the AUR recipe and the rest"),
    ("docs/USING_THE_CRATES.md", "Using it as a library",
     "The crates, and what depending on one commits you to"),
    ("docs/WEBSITE.md", "The website",
     "Both editions, what generates each page, and the twelve scripts"),
    ("docs/CONTRIBUTING.md", "Contributing",
     "Building, the standing rules, the house style and what a change has to "
     "pass"),
    ("docs/SECURITY.md", "Reporting a vulnerability",
     "Where to send it, what counts as one, and what does not"),
    ("docs/AUDIT.md", "Audit history",
     "Every defect found and fixed, in order, including the ones an earlier "
     "round had called clean"),
    ("ROADMAP.md", "Roadmap",
     "What is done, what is being worked on, and what is planned"),
    ("CHANGELOG.md", "Release notes",
     "Every release, newest first"),
]

# The three guides tools/docs/guides.py writes, listed so the landing page and
# the sidebar can point at them. Read from there rather than repeated: if a
# guide is renamed, this notices rather than linking into nothing.
GUIDES = [
    ("Guide-command-line", "The command line",
     "`veilvoice`, every command with worked examples"),
    ("Guide-desktop-app", "The desktop application",
     "`veilvoice-gui`, screen by screen"),
    ("Guide-verifier", "The verifier",
     "Checking a download, at length"),
]

# A relative link to a Markdown file: `](NAME.md)` or `](dir/NAME.md)`, with an
# optional fragment. Anything absolute, or a bare fragment, is left alone.
RELATIVE_MD = re.compile(r"\]\((?!https?:|#|/)([A-Za-z0-9_./-]+\.md)(#[^)]*)?\)")
# A relative link to anything else in the tree: source, a script, a directory.
RELATIVE_OTHER = re.compile(r"\]\((?!https?:|#|/|[A-Za-z0-9_./-]+\.md)([A-Za-z0-9_./-]+)(#[^)]*)?\)")
# A relative image, which in a wiki must be an absolute raw URL to render.
RELATIVE_IMG = re.compile(r"!\[([^\]]*)\]\((?!https?:|/)([A-Za-z0-9_./-]+)\)")


def page_name(source):
    """The wiki page a source document becomes."""
    stem = os.path.basename(source)[: -len(".md")]
    return "Doc-" + stem.replace("_", "-")


def read(path):
    with io.open(os.path.join(ROOT, path), encoding="utf-8") as handle:
        return handle.read()


def rewrite(text, source):
    """The same text, with every relative link made to work in a flat wiki."""
    here = os.path.dirname(source)
    pages = {src: page_name(src) for src, _, _ in DOCUMENTS}
    # Also reachable by bare name, which is how a document in `docs/` refers to
    # its neighbour.
    by_base = {os.path.basename(src): page for src, page in pages.items()}

    def md_link(found):
        target, fragment = found.group(1), found.group(2) or ""
        joined = os.path.normpath(os.path.join(here, target)) if here else target
        joined = joined.replace(os.sep, "/")
        if joined in pages:
            return "](%s)" % pages[joined]
        base = os.path.basename(target)
        if base in by_base and not target.startswith("../"):
            return "](%s)" % by_base[base]
        return "](%s/blob/main/%s%s)" % (REPO, joined, fragment)

    def other_link(found):
        target, fragment = found.group(1), found.group(2) or ""
        joined = os.path.normpath(os.path.join(here, target)) if here else target
        return "](%s/blob/main/%s%s)" % (REPO, joined.replace(os.sep, "/"), fragment)

    def image(found):
        alt, target = found.group(1), found.group(2)
        joined = os.path.normpath(os.path.join(here, target)) if here else target
        return "![%s](%s/raw/main/%s)" % (alt, REPO, joined.replace(os.sep, "/"))

    text = RELATIVE_IMG.sub(image, text)
    text = RELATIVE_MD.sub(md_link, text)
    text = RELATIVE_OTHER.sub(other_link, text)
    return text


def document_pages():
    """One wiki page per prose document."""
    out = {}
    for source, title, _blurb in DOCUMENTS:
        body = rewrite(read(source), source)
        header = (
            "%s\n"
            "*This page is [`%s`](%s/blob/main/%s) in the repository. "
            "The repository copy is the source; this is the same text with its "
            "links rewritten for the wiki.*\n"
            % (BANNER, source, REPO, source)
        )
        out[page_name(source)] = header + "\n" + body.rstrip("\n") + "\n"
    return out


def home():
    """The landing page: everything, grouped by what a reader came to do."""
    out = [BANNER, "# VeilVoice", ""]
    out.append("![VeilVoice](%s/raw/main/assets/banner.png)" % REPO)
    out.append("")
    out.append("Irreversible voice de-identification, fully offline. It destroys "
               "the biometric voiceprint, pitch, formants, timbre and accent, "
               "and leaves the speech transcribable.")
    out.append("")
    out.append("This wiki is generated from the repository. Every page here has "
               "a source file there, and CI fails if the two disagree, so "
               "nothing on it can quietly go stale.")
    out.append("")

    out.append("## Start here")
    out.append("")
    for source, title, blurb in DOCUMENTS[:5]:
        out.append("- **[[%s|%s]]** &middot; %s" % (title, page_name(source), blurb))
    out.append("")

    out.append("## One program at a time")
    out.append("")
    for page, title, blurb in GUIDES:
        out.append("- **[[%s|%s]]** &middot; %s" % (title, page, blurb))
    out.append("")

    out.append("## Checking it, building it, packaging it")
    out.append("")
    for source, title, blurb in DOCUMENTS[5:11]:
        out.append("- **[[%s|%s]]** &middot; %s" % (title, page_name(source), blurb))
    out.append("")

    out.append("## Working on it")
    out.append("")
    for source, title, blurb in DOCUMENTS[11:]:
        out.append("- **[[%s|%s]]** &middot; %s" % (title, page_name(source), blurb))
    out.append("")

    out.append("## Every crate and every file")
    out.append("")
    out.append("**[[The reference|Reference]]** is a page for each of the "
               "thirteen crates and each source file in them, generated from "
               "the doc comments in the code. Each crate page carries its "
               "banner, a flowchart of what calls what, and a table of every "
               "file in it.")
    out.append("")
    out.append("The same pages are on "
               "[the website](https://tilas01.github.io/veilvoice/wiki.html), "
               "which additionally shows the syntax-highlighted source beside "
               "each one.")
    out.append("")
    return "\n".join(out) + "\n"


def sidebar():
    """The navigation GitHub shows beside every page."""
    out = [BANNER, "### [[VeilVoice|Home]]", ""]
    groups = [
        ("Start here", [(page_name(s), t) for s, t, _ in DOCUMENTS[:5]]),
        ("Per program", [(p, t) for p, t, _ in GUIDES]),
        ("Check and build", [(page_name(s), t) for s, t, _ in DOCUMENTS[5:11]]),
        ("Work on it", [(page_name(s), t) for s, t, _ in DOCUMENTS[11:]]),
    ]
    for heading, entries in groups:
        out.append("**%s**" % heading)
        out.append("")
        for page, title in entries:
            out.append("- [[%s|%s]]" % (title, page))
        out.append("")
    out.append("**Reference**")
    out.append("")
    out.append("- [[Every crate and file|Reference]]")
    out.append("")
    return "\n".join(out) + "\n"


def build():
    pages = document_pages()
    pages["Home"] = home()
    pages["_Sidebar"] = sidebar()
    return pages


# A wiki link, in either form GitHub accepts: `[[Page]]` or `[[Title|Page]]`.
WIKI_LINK = re.compile(r"\[\[([^\]|]+)(?:\|([^\]]+))?\]\]")

# A fenced block, and an inline code span. Their spans are worked out so a
# `[[link]]` quoted inside one can be skipped, for the same reason
# `tools/audit/rsa_usage.py` strips string literals before looking for code:
# text quoting a link is not a link. The roadmap entry describing this very
# guard contains one in backticks.
#
# The test is containment, not overlap, and that distinction is the whole of
# it: the reference pages write `[[`devices.rs`|File-...]]`, where a code span
# sits *inside* a link and the link is real. Only a link wholly inside a span
# is quoted rather than meant.
FENCE = re.compile(r"^```.*?^```", re.S | re.M)
CODE_SPAN = re.compile(r"`[^`\n]*`")


def quoted_spans(text):
    """Where the fenced blocks and inline code spans are."""
    return [found.span() for found in FENCE.finditer(text)] + \
           [found.span() for found in CODE_SPAN.finditer(text)]


def links_in(text):
    """Every wiki link that is meant rather than quoted."""
    spans = quoted_spans(text)
    out = []
    for found in WIKI_LINK.finditer(text):
        start, end = found.span()
        if any(a <= start and end <= b for a, b in spans):
            continue
        out.append(found.group(2) or found.group(1))
    return out


def dead_links():
    """Every `[[link]]` in the wiki that names a page which does not exist.

    Worth checking separately from whether the pages are current, because a
    wiki link to a missing page does not fail loudly: GitHub renders it as an
    invitation to create that page, so a typo looks like a feature. This is
    the whole reason the link rewriting above exists, and a rule with no guard
    decays, so here is the guard.
    """
    have = {name[: -len(".md")]
            for name in os.listdir(WIKI) if name.endswith(".md")}
    dead = []
    for name in sorted(os.listdir(WIKI)):
        if not name.endswith(".md"):
            continue
        with io.open(os.path.join(WIKI, name), encoding="utf-8") as handle:
            text = handle.read()
        for target in links_in(text):
            if target not in have:
                dead.append((name, target))
    return dead


def main():
    check = "--check" in sys.argv[1:]
    pages = build()

    if check:
        problems = []
        for name, wanted in sorted(pages.items()):
            path = os.path.join(WIKI, name + ".md")
            if not os.path.exists(path):
                problems.append("missing: wiki/%s.md" % name)
                continue
            with io.open(path, encoding="utf-8") as handle:
                if handle.read() != wanted:
                    problems.append("stale:   wiki/%s.md" % name)
        if problems:
            for line in problems:
                print("  " + line)
            print()
            print("Run 'python tools/docs/wiki.py' and commit the result.")
            return 1
        dead = dead_links()
        if dead:
            print("  these wiki links name a page that does not exist:")
            for where, target in dead[:20]:
                print("    %-38s -> %s" % (where, target))
            if len(dead) > 20:
                print("    ... and %d more" % (len(dead) - 20))
            return 1

        total = sum(len(links_in(
            io.open(os.path.join(WIKI, n), encoding="utf-8").read()))
            for n in os.listdir(WIKI) if n.endswith(".md"))
        print("  %d wiki page(s) current, from %d document(s); "
              "%d internal link(s), all resolving"
              % (len(pages), len(DOCUMENTS), total))
        return 0

    os.makedirs(WIKI, exist_ok=True)
    for name, body in sorted(pages.items()):
        with io.open(os.path.join(WIKI, name + ".md"), "w",
                     encoding="utf-8", newline="\n") as handle:
            handle.write(body)
    print("  wrote %d wiki page(s) from %d document(s)"
          % (len(pages), len(DOCUMENTS)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
