#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""
The wiki's landing page, its sidebar, and a page for every prose document.

    python tools/docs/wiki.py           # write them
    python tools/docs/wiki.py --check   # verify they are current

# What was already there, and what was missing

`tools/docs/generate.py` has long written the reference half of the wiki: a page
per crate and per source file, 180 of them, each with its banner, its flowchart
and its tables. `tools/docs/guides.py` adds three, one per program.

None of that is a way *in*. A GitHub wiki opens on a page called `Home`, and
there was no `Home`; it shows a sidebar on every page if one is called
`_Sidebar`, and there was no `_Sidebar`. A reader arriving at the wiki landed on
whichever page GitHub picked and had no list of the rest. Meanwhile the prose
that answers the questions people actually arrive with, how to build it, how to
check a download reproduces, how to contribute, was in `docs/` and not in the
wiki at all.

# Why the prose is converted rather than written again

`docs/` is the source. These pages are that text with its links rewritten for a
flat namespace, so there is no second copy to go stale: `--check` regenerates
into memory and compares, and CI fails on a difference. The same decision, for
the same reason, as every other generator here.

# What the link rewriting has to handle

The wiki has no directories. A document in `docs/` links to its neighbour as
`WHITEPAPER.md`, which is right in `docs/` and wrong in the wiki. Three cases:

  * a neighbour that has a wiki page becomes a `[[wiki link]]`,
  * a neighbour that does not becomes an absolute URL into the repository,
  * a link to a file elsewhere in the tree becomes an absolute URL too.

The third matters more than it looks: a relative link to `crates/...` or
`tools/...` resolves, in a wiki, to a wiki page of that name, which does not
exist. Silently. That is the failure this rewriting exists to prevent.

# The wiki is the whole manual, and that is checked rather than intended

Roadmap item 178. Converting the documents was never the claim; the claim is
that somebody who has just downloaded a release can read the wiki and find
everything, which is a claim about *coverage* and was held up by nothing but
this file's list being kept current by hand.

Two guards now hold it, and both exist because the failure they catch is
silent rather than loud:

  * `unpublished()` walks `docs/` and the root and fails on any document that
    is in neither `DOCUMENTS` nor `NOT_A_WIKI_PAGE`. A document nobody listed
    is not a broken link or a missing file, it is a page that is simply not
    there, on the wiki and on the website both.
  * `misgrouped()` fails on a document naming a group that does not exist.
    The landing page used to slice this list by index, so the grouping was a
    fact about where a line sat in a Python file; see F-198 in `docs/AUDIT.md`.

Pure standard library.
"""

from __future__ import annotations

import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
WIKI = os.path.join(ROOT, "wiki")
REPO = "https://github.com/tilas01/veilvoice"

BANNER = ("<!-- GENERATED by tools/docs/wiki.py from the documents in the "
          "repository. Do not edit: edit the source document and run the "
          "generator. -->")

# The groups the landing page and the sidebar arrange the documents into: the
# key each document carries, the heading the landing page gives it, and the
# shorter one the sidebar uses in a narrow column.
#
# The order here is the order a reader needs them, not alphabetical: what the
# thing is, then how to get it, then living with it, then checking it, then
# working on it.
GROUPS = [
    ("start", "Start here", "Start here"),
    ("after", "After it is installed", "After installing"),
    ("check", "Checking it, building it, packaging it", "Check and build"),
    ("work", "Working on it", "Work on it"),
]

# Every prose document that becomes a wiki page: where it lives, the page it
# becomes, the group it belongs to, and the one line the landing page and
# sidebar describe it by.
#
# The group is named rather than implied by position. It used to be implied:
# the landing page sliced this list `[:5]`, `[5:11]` and `[11:]`, so adding a
# document in the wrong place silently moved somebody else's into a heading it
# did not belong under, and adding one past the end silently dropped it off
# both the landing page and the sidebar. Nothing failed; the page was simply
# unreachable. See F-198 in `docs/AUDIT.md`.
DOCUMENTS = [
    ("docs/START_HERE.md", "Start here", "start",
     "You have just downloaded it and have not run it yet: the order to do "
     "things in, and why that order"),
    ("README.md", "What VeilVoice is", "start",
     "The whole project in one page: what it does, what it refuses to claim, "
     "and how to install it"),
    ("docs/USER_GUIDE.md", "User guide", "start",
     "Every screen and every command, in order"),
    ("docs/INSTALL.md", "Installing", "start",
     "Per operating system, with the verification step in place rather than "
     "bolted on"),
    ("docs/COMMANDS.md", "Every command", "start",
     "All thirty-two, what each is for, and where the same job is in the "
     "window"),
    ("docs/FAQ.md", "Questions", "start",
     "The questions people actually ask"),
    ("docs/UPDATING.md", "Updating", "after",
     "Finding out something newer exists, moving to it, and why the window "
     "then reports that a file changed"),
    ("docs/GUARD.md", "When a file changes", "after",
     "What VeilVoice records about its own files, and what a report of a "
     "change is and is not evidence of"),
    ("docs/WHITEPAPER.md", "How the veiling works", "check",
     "What is done to a voice, why it cannot be undone, and what this is not"),
    ("docs/GUIDE_VERIFY.md", "Checking a download", "check",
     "The signature chain end to end, and what each verdict is worth"),
    ("docs/REPRODUCIBLE_BUILDS.md", "Building it yourself", "check",
     "Building from source and comparing the result against what was "
     "published"),
    ("docs/SELF_SIGNING.md", "The code-signing certificate", "check",
     "What it is, and importing it"),
    ("docs/PACKAGING.md", "Packaging", "check",
     "The deb, the RPM, the AUR recipe and the rest"),
    ("docs/USING_THE_CRATES.md", "Using it as a library", "check",
     "The crates, and what depending on one commits you to"),
    ("docs/WEBSITE.md", "The website", "work",
     "Both editions, what generates each page, and the twelve scripts"),
    ("docs/DEVELOPERS.md", "Working on the code", "work",
     "The shape of the repository: the crates, where to start reading, what "
     "a build enforces and how to run every check"),
    ("docs/CONTRIBUTING.md", "Contributing", "work",
     "Building, the standing rules, the house style and what a change has to "
     "pass"),
    ("docs/SECURITY.md", "Reporting a vulnerability", "work",
     "Where to send it, what counts as one, and what does not"),
    ("docs/AUDIT.md", "Audit history", "work",
     "Every defect found and fixed, in order, including the ones an earlier "
     "round had called clean"),
    ("ROADMAP.md", "Roadmap", "work",
     "What is done, what is being worked on, and what is planned"),
    ("CHANGELOG.md", "Release notes", "work",
     "Every release, newest first"),
]

# The prose files this tool deliberately does not publish, and why each one is
# not a gap. Checked rather than assumed: `unpublished()` below fails on any
# document that is in neither this mapping nor `DOCUMENTS`, because the whole
# claim of the wiki is that it is the whole manual, and a document nobody
# listed is a document nobody can find.
NOT_A_WIKI_PAGE = {
    "docs/GUIDE_CLI.md":
        "tools/docs/guides.py writes it into the wiki as Guide-command-line",
    "docs/GUIDE_GUI.md":
        "tools/docs/guides.py writes it into the wiki as Guide-desktop-app",
    "docs/MEASURED.md":
        "a table of measurements the other pages quote, not a page to read",
}

# The three guides tools/docs/guides.py writes, listed so the landing page and
# the sidebar can point at them. Read from there rather than repeated: if a
# guide is renamed, this notices rather than linking into nothing.
GUIDES = [
    ("Guide-command-line", "The command line",
     "`veilvoice`, every command with worked examples"),
    ("Guide-desktop-app", "The desktop application",
     "`veilvoice-gui`, screen by screen"),
    ("Guide-verifier", "The verifier",
     "Checking a download, at length"),
]

# A relative link to a Markdown file: `](NAME.md)` or `](dir/NAME.md)`, with an
# optional fragment. Anything absolute, or a bare fragment, is left alone.
RELATIVE_MD = re.compile(r"\]\((?!https?:|#|/)([A-Za-z0-9_./-]+\.md)(#[^)]*)?\)")
# A relative link to anything else in the tree: source, a script, a directory.
RELATIVE_OTHER = re.compile(r"\]\((?!https?:|#|/|[A-Za-z0-9_./-]+\.md)([A-Za-z0-9_./-]+)(#[^)]*)?\)")
# A relative image, which in a wiki must be an absolute raw URL to render.
RELATIVE_IMG = re.compile(r"!\[([^\]]*)\]\((?!https?:|/)([A-Za-z0-9_./-]+)\)")


def page_name(source):
    """The wiki page a source document becomes."""
    stem = os.path.basename(source)[: -len(".md")]
    return "Doc-" + stem.replace("_", "-")


def read(path):
    with io.open(os.path.join(ROOT, path), encoding="utf-8") as handle:
        return handle.read()


def rewrite(text, source):
    """The same text, with every relative link made to work in a flat wiki."""
    here = os.path.dirname(source)
    pages = {src: page_name(src) for src, _, _, _ in DOCUMENTS}
    # Also reachable by bare name, which is how a document in `docs/` refers to
    # its neighbour.
    by_base = {os.path.basename(src): page for src, page in pages.items()}

    def md_link(found):
        target, fragment = found.group(1), found.group(2) or ""
        joined = os.path.normpath(os.path.join(here, target)) if here else target
        joined = joined.replace(os.sep, "/")
        if joined in pages:
            return "](%s)" % pages[joined]
        base = os.path.basename(target)
        if base in by_base and not target.startswith("../"):
            return "](%s)" % by_base[base]
        return "](%s/blob/main/%s%s)" % (REPO, joined, fragment)

    def other_link(found):
        target, fragment = found.group(1), found.group(2) or ""
        joined = os.path.normpath(os.path.join(here, target)) if here else target
        return "](%s/blob/main/%s%s)" % (REPO, joined.replace(os.sep, "/"), fragment)

    def image(found):
        alt, target = found.group(1), found.group(2)
        joined = os.path.normpath(os.path.join(here, target)) if here else target
        return "![%s](%s/raw/main/%s)" % (alt, REPO, joined.replace(os.sep, "/"))

    text = RELATIVE_IMG.sub(image, text)
    text = RELATIVE_MD.sub(md_link, text)
    text = RELATIVE_OTHER.sub(other_link, text)
    return text


def document_pages():
    """One wiki page per prose document."""
    out = {}
    for source, _title, _group, _blurb in DOCUMENTS:
        body = rewrite(read(source), source)
        header = (
            "%s\n"
            "*This page is [`%s`](%s/blob/main/%s) in the repository. "
            "The repository copy is the source; this is the same text with its "
            "links rewritten for the wiki.*\n"
            % (BANNER, source, REPO, source)
        )
        out[page_name(source)] = header + "\n" + body.rstrip("\n") + "\n"
    return out


def home():
    """The landing page: everything, grouped by what a reader came to do.

    The separator between a title and its sentence is the character itself
    rather than `&middot;`. GitHub renders the entity and the website's own
    renderer escapes it, correctly: a Markdown renderer that passed `&` through
    would be a renderer that lets a document write markup. The page on the
    website therefore showed readers the letters `&middot;` twenty times, which
    is what publishing the wiki as pages of this site found.
    """
    out = [BANNER, "# VeilVoice", ""]
    out.append("![VeilVoice](%s/raw/main/assets/banner.png)" % REPO)
    out.append("")
    out.append("Irreversible voice de-identification, fully offline. It destroys "
               "the biometric voiceprint, pitch, formants, timbre and accent, "
               "and leaves the speech transcribable.")
    out.append("")
    out.append("This wiki is generated from the repository. Every page here has "
               "a source file there, and CI fails if the two disagree, so "
               "nothing on it can quietly go stale.")
    out.append("")

    for key, heading, _short in GROUPS:
        out.append("## %s" % heading)
        out.append("")
        for source, title, group, blurb in DOCUMENTS:
            if group == key:
                out.append("- **[[%s|%s]]** \u00b7 %s"
                           % (title, page_name(source), blurb))
        out.append("")
        # The per-program guides sit after the first group, where somebody who
        # has just arrived meets them: they are the same material narrowed to
        # whichever program is actually in front of the reader.
        if key == "start":
            out.append("## One program at a time")
            out.append("")
            for page, title, blurb in GUIDES:
                out.append("- **[[%s|%s]]** \u00b7 %s" % (title, page, blurb))
            out.append("")

    out.append("## Every crate and every file")
    out.append("")
    out.append("**[[The reference|Reference]]** is a page for each of the "
               "thirteen crates and each source file in them, generated from "
               "the doc comments in the code. Each crate page carries its "
               "banner, a flowchart of what calls what, and a table of every "
               "file in it.")
    out.append("")
    out.append("The same pages are on "
               "[the website](https://tilas01.github.io/veilvoice/wiki.html), "
               "which additionally shows the syntax-highlighted source beside "
               "each one.")
    out.append("")
    return "\n".join(out) + "\n"


def sidebar():
    """The navigation GitHub shows beside every page."""
    out = [BANNER, "### [[VeilVoice|Home]]", ""]
    groups = []
    for key, _heading, short in GROUPS:
        groups.append((short, [(page_name(s), t)
                               for s, t, g, _ in DOCUMENTS if g == key]))
        if key == "start":
            groups.append(("Per program", [(p, t) for p, t, _ in GUIDES]))
    for heading, entries in groups:
        out.append("**%s**" % heading)
        out.append("")
        for page, title in entries:
            out.append("- [[%s|%s]]" % (title, page))
        out.append("")
    out.append("**Reference**")
    out.append("")
    out.append("- [[Every crate and file|Reference]]")
    out.append("")
    return "\n".join(out) + "\n"


def build():
    pages = document_pages()
    pages["Home"] = home()
    pages["_Sidebar"] = sidebar()
    return pages


# A wiki link, in either form GitHub accepts: `[[Page]]` or `[[Title|Page]]`.
WIKI_LINK = re.compile(r"\[\[([^\]|]+)(?:\|([^\]]+))?\]\]")

# A fenced block, and an inline code span. Their spans are worked out so a
# `[[link]]` quoted inside one can be skipped, for the same reason
# `tools/audit/rsa_usage.py` strips string literals before looking for code:
# text quoting a link is not a link. The roadmap entry describing this very
# guard contains one in backticks.
#
# The test is containment, not overlap, and that distinction is the whole of
# it: the reference pages write `[[`devices.rs`|File-...]]`, where a code span
# sits *inside* a link and the link is real. Only a link wholly inside a span
# is quoted rather than meant.
FENCE = re.compile(r"^```.*?^```", re.S | re.M)
CODE_SPAN = re.compile(r"`[^`\n]*`")


def quoted_spans(text):
    """Where the fenced blocks and inline code spans are."""
    return [found.span() for found in FENCE.finditer(text)] + \
           [found.span() for found in CODE_SPAN.finditer(text)]


def links_in(text):
    """Every wiki link that is meant rather than quoted."""
    spans = quoted_spans(text)
    out = []
    for found in WIKI_LINK.finditer(text):
        start, end = found.span()
        if any(a <= start and end <= b for a, b in spans):
            continue
        out.append(found.group(2) or found.group(1))
    return out


def dead_links():
    """Every `[[link]]` in the wiki that names a page which does not exist.

    Worth checking separately from whether the pages are current, because a
    wiki link to a missing page does not fail loudly: GitHub renders it as an
    invitation to create that page, so a typo looks like a feature. This is
    the whole reason the link rewriting above exists, and a rule with no guard
    decays, so here is the guard.
    """
    have = {name[: -len(".md")]
            for name in os.listdir(WIKI) if name.endswith(".md")}
    dead = []
    for name in sorted(os.listdir(WIKI)):
        if not name.endswith(".md"):
            continue
        with io.open(os.path.join(WIKI, name), encoding="utf-8") as handle:
            text = handle.read()
        for target in links_in(text):
            if target not in have:
                dead.append((name, target))
    return dead


# A page name a GitHub wiki can hold. The wiki is a flat repository of
# Markdown files and the page name *is* the file name, so a character the wiki
# treats specially produces a page under a name nobody linked to.
#
# A slash is the one that matters: `Doc/README.md` is not a page called
# "Doc/README", it is a page GitHub shows at a path most links will not reach,
# and a generator that derives a page name from a source path is one careless
# `replace` away from writing one. The leading underscore is allowed because
# `_Sidebar` is a name GitHub itself defines.
PUBLISHABLE_NAME = re.compile(r"^[A-Za-z0-9_][A-Za-z0-9._ -]*$")


def unpublishable():
    """Every file in `wiki/` that a GitHub wiki could not hold as a page.

    Checked here rather than in the workflow that publishes, because the
    workflow runs on `main` only and after the fact: a page named something
    the wiki cannot take would reach a reader as a failed publish long after
    the commit that wrote it, on the one branch where a failure is most
    expensive. This fails the build that wrote it instead.

    Three things are refused. A subdirectory, because a wiki is flat and `cp
    wiki/*.md` would silently leave its contents behind. A file that is not
    Markdown, for the same reason. And a name outside `PUBLISHABLE_NAME`.
    """
    out = []
    for name in sorted(os.listdir(WIKI)):
        full = os.path.join(WIKI, name)
        if os.path.isdir(full):
            out.append("%s: a wiki is flat, so a directory cannot be published"
                       % name)
            continue
        if not name.endswith(".md"):
            out.append("%s: every page of a wiki is a Markdown file" % name)
            continue
        page = name[: -len(".md")]
        if not PUBLISHABLE_NAME.match(page):
            out.append("%s: not a page name a GitHub wiki can hold" % name)
    return out


def unpublished():
    """Every prose document in the repository that no wiki page carries.

    The wiki's claim is that it is the whole manual. That claim is kept by a
    list, and a list is exactly the thing that goes quietly out of date: a
    document added to `docs/` and not added to `DOCUMENTS` is not a broken
    build, a broken link or a missing file. It is a page that simply is not
    there, on the wiki and on the website both, and nothing anywhere reports
    it.

    So every document is either published or written down here as deliberately
    not published, with the reason beside it. Roadmap item 178.

    The root is walked as well as `docs/`, because `README.md`, `ROADMAP.md`
    and `CHANGELOG.md` are pages of the wiki too, and a new one beside them
    would be as invisible as a new one in `docs/`.
    """
    published = {src for src, _, _, _ in DOCUMENTS}
    out = []
    for folder in ("", "docs"):
        base = os.path.join(ROOT, folder) if folder else ROOT
        for name in sorted(os.listdir(base)):
            if not name.endswith(".md"):
                continue
            rel = "%s/%s" % (folder, name) if folder else name
            if rel in published or rel in NOT_A_WIKI_PAGE:
                continue
            out.append(rel)
    return out


def misgrouped():
    """Every document whose group is not one of the groups, and every empty one.

    Both halves of the same question. A document naming a group that does not
    exist would be dropped from the landing page and the sidebar without a
    word, which is the failure the named groups were introduced to stop; a
    group with nothing in it prints a heading over an empty list.
    """
    known = {key for key, _, _ in GROUPS}
    problems = ["%s: no group called %r" % (src, group)
                for src, _, group, _ in DOCUMENTS if group not in known]
    used = {group for _, _, group, _ in DOCUMENTS}
    problems += ["group %r has no documents in it" % key
                 for key in sorted(known - used)]
    return problems


def main():
    check = "--check" in sys.argv[1:]

    problems = misgrouped()
    if problems:
        for line in problems:
            print("  " + line)
        print()
        print("Fix GROUPS or DOCUMENTS in tools/docs/wiki.py.")
        return 1

    pages = build()

    missing = unpublished()
    if missing:
        print("  these documents have no page in the wiki, and are not listed")
        print("  in NOT_A_WIKI_PAGE as deliberately left out:")
        for rel in missing:
            print("    %s" % rel)
        print()
        print("Add each to DOCUMENTS in tools/docs/wiki.py, or to")
        print("NOT_A_WIKI_PAGE with the reason it is not a page.")
        return 1

    if check:
        problems = []
        for name, wanted in sorted(pages.items()):
            path = os.path.join(WIKI, name + ".md")
            if not os.path.exists(path):
                problems.append("missing: wiki/%s.md" % name)
                continue
            with io.open(path, encoding="utf-8") as handle:
                if handle.read() != wanted:
                    problems.append("stale:   wiki/%s.md" % name)
        if problems:
            for line in problems:
                print("  " + line)
            print()
            print("Run 'python tools/docs/wiki.py' and commit the result.")
            return 1
        unholdable = unpublishable()
        if unholdable:
            print("  these could not be published as wiki pages:")
            for line in unholdable:
                print("    %s" % line)
            return 1
        dead = dead_links()
        if dead:
            print("  these wiki links name a page that does not exist:")
            for where, target in dead[:20]:
                print("    %-38s -> %s" % (where, target))
            if len(dead) > 20:
                print("    ... and %d more" % (len(dead) - 20))
            return 1

        total = sum(len(links_in(
            io.open(os.path.join(WIKI, n), encoding="utf-8").read()))
            for n in os.listdir(WIKI) if n.endswith(".md"))
        print("  %d wiki page(s) current, from %d document(s); "
              "%d internal link(s), all resolving"
              % (len(pages), len(DOCUMENTS), total))
        return 0

    os.makedirs(WIKI, exist_ok=True)
    for name, body in sorted(pages.items()):
        with io.open(os.path.join(WIKI, name + ".md"), "w",
                     encoding="utf-8", newline="\n") as handle:
            handle.write(body)
    print("  wrote %d wiki page(s) from %d document(s)"
          % (len(pages), len(DOCUMENTS)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
