#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""The facts the website's interactive demonstration is drawn from.

    python tools/site/demo.py           # write website/js/demo-data.js
    python tools/site/demo.py --check   # verify it is current

# What this generates, and what it deliberately does not

`website/js/demo.js` draws a working model of the desktop application and of
the command line, inside the page, so somebody can click through both before
downloading anything. The *drawing* is hand written, because it is an
interface and interfaces are designed rather than derived.

The **facts inside it are not**. Three things come from the source:

  * **The tabs the application has, in order, with their labels.** Read out of
    `crates/veilvoice-gui/src/app.rs`, which is where they are decided. A tab
    added to the application appears in the demonstration on the next run, and
    a demonstration showing a tab that no longer exists fails the build.
  * **What each command line subcommand printed.** Taken from the `cli-*.txt`
    captures in `assets/screenshots/`, which are what the real program actually
    wrote. The terminal in the demonstration replays those bytes rather than a
    plausible-looking imitation of them.
  * **The version.** From `Cargo.toml`.

A demonstration of software that quietly stops matching the software is worse
than no demonstration, because it is a claim rather than an omission. So it is
generated and checked, exactly as the documentation, the artwork, the roadmap
page and the search index are.

# The honest label

None of this makes the model *be* the application. It is a drawing that
responds to clicks, the panels are written by hand, and the numbers in them are
illustrations. `demo.js` says so at the top of the overlay, in the reader's
sight rather than in a comment, and points at the photographs and the
downloads. That sentence is the price of having a demonstration at all.

# In plain words

The website has a pretend version of the app you can click around in. This file
takes the parts of it that have to be true, the list of tabs and the real
output of each command, out of the actual source code, so the pretend version
cannot quietly drift away from the real one.

Pure standard library.
"""

import argparse
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))

OUT = "website/js/demo-data.js"
MARKER = "GENERATED by tools/site/demo.py"

# The tab strip, as `app.rs` writes it: `(Tab::File, "Anonymise file"),`.
TAB_ROW = re.compile(r"\(Tab::(?P<variant>\w+),\s*\"(?P<label>[^\"]+)\"\)")
# And the key each variant is stored under: `Self::File => "file",`.
TAB_KEY = re.compile(r"Self::(?P<variant>\w+) => \"(?P<key>[a-z]+)\",")

# What each command line capture is a picture of. The captures themselves are
# named by `tools/shots/terminal.py`; this is the command a reader types to get
# them, which that file knows and does not write down anywhere a page can read.
COMMANDS = [
    ("help", "veilvoice --help", "everything the command line offers"),
    ("anonymise", "veilvoice anonymise --help", "veiling one recording"),
    ("live", "veilvoice live --help", "scrambling a microphone as it runs"),
    ("conversation", "veilvoice conversation --help", "several people in one recording"),
    ("render", "veilvoice conversation render --help", "a plan, a recording and a page"),
    ("preview", "veilvoice conversation preview --help", "what the video will look like"),
    ("companions", "veilvoice companions --help", "software VeilVoice uses and never bundles"),
    ("capture", "veilvoice capture --help", "which screen recorders are running"),
    ("guard", "veilvoice guard --help", "noticing that a file changed"),
    ("clean", "veilvoice clean --help", "metadata, EXIF and GPS"),
]



# What each tab of the application is for, in one sentence, for the walkthrough
# that shows the screenshots. The tab list itself is read out of `app.rs`: this
# is only the sentence under the picture, and a tab that gains a screenshot
# without gaining a sentence here fails the build rather than appearing blank.
TAB_NOTES = {
    "file": "Point it at a recording, choose how hard to push the voice, and "
            "write the result. Encryption at rest is already on.",
    "live": "The microphone, veiled as it runs, into a virtual cable other "
            "programs can hear. The meters say sound is arriving and leaving.",
    "group": "One recording with several people in it. Each speaker is given "
             "their own destination voice, and every voiceprint is destroyed.",
    "monitor": "Which programs are holding the microphone and camera right "
               "now, and which screen recorders are running.",
    "lock": "The password for VeilVoice itself, what that lock is worth, and "
            "what it deliberately does not protect.",
    "verify": "Check a download against the signed hash list, then ask your "
              "own GnuPG the same question.",
    "settings": "Palettes, motion, the autolock timeout, and the ratchet "
                "interval. Every one of them says what it costs.",
    "install": "Copy VeilVoice somewhere the system can find it, or keep "
               "running it from the folder it is in.",
    "about": "The version, what this build can do on this machine, and the "
             "graphics driver that actually drew the window.",
}

# Worked cases: the things somebody actually wants to do, each as a real
# command. The *prose* is written here, because an explanation is writing. The
# **command is checked against the program** in `usecases()`: a case naming a
# subcommand this build does not have fails the build, so the page cannot go on
# teaching a command that has been renamed or removed.
USECASES = [
    ("Veil one recording",
     "veilvoice anonymise interview.m4a",
     "Reads almost any format, writes a veiled WAV, and seals it. It asks for "
     "a passphrase because the words survive on purpose: a veiled recording "
     "left in the clear is still a recording of everything that was said."),
    ("Veil it, and keep the accent",
     "veilvoice anonymise talk.wav --keep-accent",
     "The voiceprint still goes. The rhythm and intonation stay, which is "
     "what you want when the delivery is the point and only the speaker is not."),
    ("Write it unencrypted, deliberately",
     "veilvoice anonymise clip.wav --encrypt false",
     "Allowed, and it tells you in full what you are giving up first, then "
     "waits for an answer. In a script it prints the same warning and refuses "
     "rather than guessing."),
    ("Seal it to somebody else",
     "veilvoice anonymise clip.wav --encrypt-to them.pub",
     "X25519 and ML-KEM-768 together, so a recording stored today survives a "
     "quantum adversary later. Only their secret key opens it, and yours never "
     "existed."),
    ("Hear yourself before anybody else does",
     "veilvoice live --preview",
     "Routes the veiled voice to your own headphones and nowhere else. This is "
     "the check to run before an interview rather than during one."),
    ("Be a microphone other programs can use",
     "veilvoice live",
     "Finds a virtual cable and sends the veiled voice into it, so a call, a "
     "stream or a recorder hears the veiled voice and never the real one."),
    ("Record yourself, already veiled",
     "veilvoice record --seconds 30",
     "Captures the veiled voice straight into an encrypted file. There is "
     "never an unencrypted recording on the disk, not even briefly, so there "
     "is nothing to delete afterwards."),
    ("An interview, one voice each",
     "veilvoice conversation render --plan interview.toml",
     "Give each speaker their own destination voice so a question can still be "
     "told from its answer, with every voiceprint destroyed just as thoroughly."),
    ("Check a download before running it",
     "veilvoice verify auto",
     "Looks in Downloads, checks the signature over the hash list, then checks "
     "the archive and every file that came out of it. It never holds a private "
     "key and needs no GnuPG."),
    ("Strip the metadata off a file",
     "veilvoice clean photo.jpg",
     "Tags, EXIF and GPS, in place. A veiled recording in a folder of "
     "photographs that still carry coordinates is not anonymous."),
    ("See what is listening",
     "veilvoice watch",
     "Which programs currently hold the microphone and the camera. It says "
     "what it cannot see as plainly as what it can."),
    ("Erase something properly",
     "veilvoice shred draft.wav",
     "Overwrites and deletes, and is honest that on an SSD or a memory card "
     "the original blocks can survive every overwrite. That is why encryption "
     "at rest is the default rather than a thing to remember."),
    ("What this build can actually do here",
     "veilvoice info",
     "Every version, whether live audio has a backend on this machine, and the "
     "network answer, which is that nothing here reaches one."),
    ("Require a lock and encryption, always",
     "veilvoice mandate status",
     "The two things VeilVoice insists on unless told otherwise. Relaxing one "
     "is written down with the date, so the choice is never a mystery later."),
]

# The recorded sessions, in the order somebody meeting this project would want
# them: check the download first, then see what the program does, then see what
# it refuses to do. `tools/shots/sessions.py` records them; this is what each
# one is for, which that file knows and no page can read out of it.
SESSIONS = [
    ("verify", "veilvoice-verify",
     "Checking a download",
     "The published archive, its signed hash list, and the same question "
     "asked again of your own GnuPG."),
    ("anonymise", "veilvoice",
     "Veiling one recording",
     "A key made, then a three second recording veiled and sealed to it. "
     "Nothing typed at the second step."),
    ("info", "veilvoice",
     "What this build can do",
     "Every version, whether live audio works on this machine, and the "
     "network answer."),
    ("refusal", "veilvoice",
     "In a script, with nobody to type a passphrase",
     "It stops, explains, offers the two ways round it, and writes nothing."),
    ("unencrypted", "veilvoice",
     "Asking for it in the clear",
     "The escape hatch exists, and says in full what you are giving up "
     "before it uses it."),
]


def read(path):
    with io.open(path, encoding="utf-8") as handle:
        return handle.read()


def tabs():
    """Every tab the application shows, in order, with its label and key."""
    source = read(os.path.join(ROOT, "crates", "veilvoice-gui", "src", "app.rs"))
    keys = {m.group("variant"): m.group("key") for m in TAB_KEY.finditer(source)}
    found = []
    for match in TAB_ROW.finditer(source):
        variant = match.group("variant")
        key = keys.get(variant)
        if key is None:
            raise SystemExit(
                "crates/veilvoice-gui/src/app.rs shows a tab %s with no key.\n"
                "  `Tab::key` is what the demonstration and the screenshots are\n"
                "  named by, so a tab without one cannot be drawn." % variant)
        found.append({"key": key, "label": match.group("label")})
    if not found:
        raise SystemExit(
            "no tabs were found in crates/veilvoice-gui/src/app.rs.\n"
            "  They are read from the `(Tab::X, \"label\")` list the window\n"
            "  draws. If that moved, fix TAB_ROW here rather than shipping a\n"
            "  demonstration with no tabs in it.")
    return found


def commands():
    """Each subcommand, and exactly what it printed."""
    out = []
    for name, typed, note in COMMANDS:
        path = os.path.join(ROOT, "assets", "screenshots", "cli-%s.txt" % name)
        if not os.path.exists(path):
            raise SystemExit(
                "%s is missing, so the demonstration would have to invent what\n"
                "  `%s` prints. Run: python tools/shots/terminal.py --capture"
                % (os.path.relpath(path, ROOT), typed))
        out.append({
            "name": name,
            "typed": typed,
            "note": note,
            "output": read(path).replace("\r\n", "\n").rstrip("\n"),
        })
    return out


def sessions():
    """The transcripts of the programs actually running.

    These are the answer to the demonstration's oldest problem. It showed ten
    help screens, which are real and are the least interesting real thing
    these programs produce: a help screen says what a flag is called and
    nothing about what happens when you use one. Somebody deciding whether to
    trust this wants to watch it work.

    Each is a transcript of a real run, captured from a terminal by
    `tools/shots/sessions.py`, including the prompts and the passphrase typed
    at them. The command line is split from its output so the page can type
    the one and print the other, which is what a terminal looks like.
    """
    out = []
    for name, programme, title, note in SESSIONS:
        path = os.path.join(ROOT, "assets", "screenshots", "session-%s.txt" % name)
        if not os.path.exists(path):
            raise SystemExit(
                "%s is missing, so the demonstration would have to invent a\n"
                "  session. Run: tools/shots/sessions.py --record"
                % os.path.relpath(path, ROOT))
        text = read(path).replace("\r\n", "\n").rstrip("\n")
        steps = []
        current = None
        for line in text.split("\n"):
            if line.startswith("$ "):
                if current:
                    steps.append(current)
                current = {"typed": line[2:], "output": []}
            elif current is not None:
                current["output"].append(line)
        if current:
            steps.append(current)
        if not steps:
            raise SystemExit(
                "%s has no `$ ` command line in it, so there is nothing to\n"
                "  replay. The recorder writes one before each step."
                % os.path.relpath(path, ROOT))
        out.append({
            "name": name,
            "programme": programme,
            "title": title,
            "note": note,
            "steps": [{"typed": step["typed"],
                       "output": "\n".join(step["output"]).strip("\n")}
                      for step in steps],
        })
    return out


def shots():
    """Each tab, its screenshot, and the sentence that goes under it.

    The tab list comes from `app.rs` and the pictures from `assets/screenshots`.
    Pairing them here is what keeps the walkthrough honest: a tab with no
    photograph, or a photograph with no sentence, stops the build rather than
    rendering a gap somebody has to notice.
    """
    out = []
    for tab in tabs():
        key = tab["key"]
        name = "gui-%s.png" % key
        path = os.path.join(ROOT, "assets", "screenshots", name)
        if not os.path.exists(path):
            raise SystemExit(
                "the application has a %r tab and %s does not exist, so the\n"
                "  walkthrough would show a heading with nothing under it.\n"
                "  Run: python tools/shots/gui.py --capture"
                % (key, os.path.relpath(path, ROOT)))
        note = TAB_NOTES.get(key)
        if not note:
            raise SystemExit(
                "the application has a %r tab with no sentence in TAB_NOTES.\n"
                "  Every picture in the walkthrough is captioned; add one\n"
                "  rather than shipping a screenshot nobody has explained."
                % key)
        out.append({
            "key": key,
            "label": tab["label"],
            "image": "assets/screenshots/" + name,
            "note": note,
        })
    return out


def usecases():
    """The worked command line cases, each checked against the real program.

    The explanation is written by hand. The command is not trusted: the
    subcommand it names is looked up in the captured `veilvoice --help`, so a
    case teaching a command that has been renamed or removed fails here instead
    of on somebody's terminal.
    """
    help_text = read(os.path.join(ROOT, "assets", "screenshots", "cli-help.txt"))
    known = set(re.findall(r"^\s{2}([a-z][a-z-]+)\s{2,}\S", help_text, re.M))
    out = []
    for title, typed, note in USECASES:
        parts = typed.split()
        if not parts or parts[0] != "veilvoice":
            raise SystemExit("a use case must be a `veilvoice ...` command: %r" % typed)
        if len(parts) < 2:
            raise SystemExit("a use case must name a subcommand: %r" % typed)
        sub = parts[1]
        if sub not in known:
            raise SystemExit(
                "the use case %r runs `veilvoice %s`, which this build's own\n"
                "  --help does not list. Either the command was renamed and this\n"
                "  case teaches something that no longer works, or the capture in\n"
                "  assets/screenshots/cli-help.txt is stale. Fix whichever it is\n"
                "  rather than publishing a command that fails.\n"
                "  Known: %s" % (title, sub, ", ".join(sorted(known))))
        out.append({"title": title, "typed": typed, "note": note})
    return out


def version():
    manifest = read(os.path.join(ROOT, "Cargo.toml"))
    block = re.search(r"\[workspace\.package\]([\s\S]*?)(\n\[|$)", manifest)
    found = re.search(r'^\s*version\s*=\s*"([^"]+)"', block.group(1), re.M)
    return found.group(1)


def build():
    data = {
        "version": version(),
        "tabs": tabs(),
        "commands": commands(),
        "sessions": sessions(),
        "shots": shots(),
        "usecases": usecases(),
    }
    # Sorted keys and a fixed indent, so the file is a function of the facts
    # rather than of the order a dict happened to be built in.
    body = json.dumps(data, indent=2, sort_keys=True, ensure_ascii=True)
    return (
        "// SPDX-License-Identifier: GPL-3.0-or-later\n"
        "//\n"
        "// %s. Do not edit.\n"
        "//\n"
        "// The facts the interactive demonstration is drawn from: the tabs the\n"
        "// desktop application has, and exactly what each command line\n"
        "// subcommand printed when it was last captured. Both come from the\n"
        "// source rather than from anybody's memory of it, so the model in the\n"
        "// page cannot quietly stop matching the program it is a model of.\n"
        "//\n"
        "// In plain words\n"
        "//\n"
        "// A list of what is in the app and what each command prints, taken\n"
        "// straight from the code, so the demonstration on the website stays\n"
        "// honest when the program changes.\n"
        "\n"
        "window.VEILVOICE_DEMO = %s;\n" % (MARKER, body)
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    text = build()
    path = os.path.join(ROOT, OUT.replace("/", os.sep))
    if args.check:
        if not os.path.exists(path) or read(path) != text:
            print("  out of date: %s" % OUT)
            print("\n  Run: python tools/site/demo.py")
            return 1
        print("the demonstration's data matches the source")
        return 0

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    print("  wrote %s (%d tabs, %d commands, %d sessions, %d shots, %d cases)"
          % (OUT, len(tabs()), len(commands()), len(sessions()),
             len(shots()), len(usecases())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
