#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""The questions page, rendered from the document that holds the answers.

    python tools/site/faq.py           # write website/faq.html
    python tools/site/faq.py --check   # verify it is current

# Why the answers live in a Markdown file

`docs/FAQ.md` is readable on GitHub, in a checkout, and by anybody who has
cloned this and never opened the website. That is the audience this project
keeps writing for, and a page that existed only as HTML would put the answers
somewhere a reader has to be online to reach.

So the document is the source and the page is its output, checked in CI, which
is the arrangement the documentation, the roadmap page and the section pages
already have. Two hand-maintained copies of the same prose is finding F-41
waiting to happen.

# The contents list is derived, not written

Every `##` in the file becomes a question in the list at the top and an anchor
to link to. A question added to the document appears in the list on the next
run, and a question renamed takes its link with it. Writing that list by hand
would mean maintaining a copy of the headings beside the headings.

# In plain words

The frequently asked questions are written in an ordinary text file in the
repository, and this turns that file into the page on the website. There is one
copy of the answers, so the page cannot start saying something the file does
not.

Pure standard library.
"""

import argparse
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))

sys.path.insert(0, os.path.join(ROOT, "tools", "docs"))
import generate as docs  # noqa: E402  (the path has to be set first)

sys.path.insert(0, HERE)
import split  # noqa: E402  (same)

SOURCE = "docs/FAQ.md"
OUT = "website/faq.html"
MARKER = "GENERATED by tools/site/faq.py"


def read(path):
    with io.open(path, encoding="utf-8") as handle:
        return handle.read()


def questions(lines):
    """Every `##` heading, with the anchor it will be given."""
    found = []
    fenced = False
    for line in lines:
        if line.strip().startswith("```"):
            fenced = not fenced
            continue
        if fenced:
            continue
        match = re.match(r"^##\s+(.*)$", line.strip())
        if match:
            title = match.group(1).strip()
            found.append((title, docs.slug(re.sub(r"[*`_]", "", title))))
    return found


def build(root):
    text = read(os.path.join(root, SOURCE))
    lines = text.split("\n")

    # The licence comment, the `# ` title and the two paragraphs about where
    # the file lives are for a reader of the repository. The page has a title
    # of its own and does not need to be told what generated it twice.
    body_lines = []
    started = False
    for line in lines:
        if line.startswith("<!--"):
            continue
        if line.startswith("# "):
            started = True
            continue
        if not started:
            continue
        body_lines.append(line)
    # Drop the note about this being the source, which is true and is meant for
    # somebody editing rather than somebody reading.
    joined = "\n".join(body_lines)
    joined = re.sub(
        r"Rendered to a page at[\s\S]*?edit it here\.\n", "", joined, count=1)
    body_lines = joined.split("\n")

    asked = questions(lines)
    if not asked:
        raise SystemExit(
            "%s has no `##` questions in it, so the page would be empty.\n"
            "  Each question is a level two heading; that is what the contents\n"
            "  list and the anchors are built from." % SOURCE)

    out = []
    out.append('<nav class="faq-list" aria-label="The questions">')
    out.append("<ul>")
    for title, anchor in asked:
        out.append('<li><a href="#%s">%s</a></li>' % (anchor, docs.inline_html(title)))
    out.append("</ul>")
    out.append("</nav>")
    out.extend(docs.doc_html(body_lines))

    index_html = read(os.path.join(root, "website", "index.html"))
    parts = split.shell(index_html)
    page = split.page(
        root,
        parts,
        "faq",
        "Questions people ask",
        "Answers to what actually gets asked, including the ones where the "
        "answer is that it does not do that.",
        "\n".join(out),
        # This page is written for itself, so its `#anchor` links point at
        # its own headings rather than at sections of the front page.
        relink_body=False,
    )
    page = page.replace(
        '<p style="color:var(--muted)">This section is also part of '
        '<a href="index.html">the front page</a>, where it sits in context '
        'with the rest.</p>',
        '<p style="color:var(--muted)">The same answers as '
        '<a href="https://github.com/%s/blob/%s/docs/FAQ.md">docs/FAQ.md</a>, '
        'which is where they are written.</p>' % (docs.REPO, docs.REF))
    page = page.replace("GENERATED by tools/site/split.py from website/index.html.",
                        "%s from docs/FAQ.md." % MARKER)
    return {OUT: page}


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    files = build(ROOT)
    if args.check:
        stale = [rel for rel, text in files.items()
                 if not os.path.exists(os.path.join(ROOT, rel.replace("/", os.sep)))
                 or read(os.path.join(ROOT, rel.replace("/", os.sep))) != text]
        if stale:
            for rel in stale:
                print("  out of date: %s" % rel)
            print("\n  Run: python tools/site/faq.py")
            return 1
        print("the questions page matches docs/FAQ.md")
        return 0

    for rel, text in sorted(files.items()):
        path = os.path.join(ROOT, rel.replace("/", os.sep))
        with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        print("  wrote %s (%d questions)" % (rel, len(questions(read(os.path.join(ROOT, SOURCE)).split("\n")))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
