#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""The releases page: every version, its notes, and its files.

    python tools/site/releases.py           # write website/releases.html
    python tools/site/releases.py --check   # verify it is current

# Marker 94, and the problem it solves

Until now the only way to see what changed in a release was `CHANGELOG.md`,
which is thousands of lines and is written newest-first for somebody reading
top to bottom, and the only way to reach the files was GitHub's releases page,
which is a different site with a different layout.

Somebody who wants "what is in the newest one, and where do I download it"
had to visit two places and scroll a lot in one of them. This page is both, in
one, with every release collapsed to its heading so the list is readable at a
glance and any one of them opening in place.

# Why the notes come from CHANGELOG.md

The same reason the questions page comes from `docs/FAQ.md`: that file is
readable on GitHub, in a checkout, and by anybody who has never opened the
website, and it is where the notes are actually written. A second hand-kept
copy of release notes is F-41 waiting to happen, and F-71 says what happens
when two hand-typed things are only ever compared against each other.

# The download links are derived from the naming, not from the network

Nothing here fetches anything: this project's build talks to no servers, and a
generator that asked GitHub what files a release has would make the website
un-buildable offline and un-reproducible. The archive names follow a fixed
pattern per platform, so the links are constructed from the version and the
pattern, and the page says plainly that it is linking rather than listing.

That has one honest consequence, stated on the page: a link here is a link to
where a file *should* be. GitHub answers with a 404 for a platform a given
release did not build, and the release page itself is one click away for
anybody who wants the definitive list.

# In plain words

Every version of VeilVoice, newest first, with what changed in it and where to
get it.

Click a version to open its notes without leaving the page. The download links
are worked out from the version number rather than fetched, so this page builds
with no network, and the release page on GitHub is always one click away if a
file is not where the pattern says.
"""

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tools", "docs"))
sys.path.insert(0, os.path.join(ROOT, "tools", "site"))

import generate as docs  # noqa: E402
import split  # noqa: E402

SOURCE = "CHANGELOG.md"
OUT = os.path.join("website", "releases.html")
MARKER = "GENERATED by tools/site/releases.py"

#: How a platform's label reads to somebody choosing a download.
#:
#: The labels themselves come from `release.yml` and are made for a build
#: matrix; "linux-arm64-musl-static" is exact and is not what somebody scanning
#: a list of downloads is looking for. Anything not named here falls back to
#: its label, so a platform added to the matrix appears on the page with an
#: ugly name rather than not at all.
PLATFORMS = {
    "windows-x86_64": "Windows, 64-bit",
    "macos-arm64": "macOS, Apple silicon",
    "macos-x86_64": "macOS, Intel",
    "linux-x86_64": "Linux, 64-bit",
    "linux-arm64": "Linux, ARM 64-bit",
    "linux-armv7-pi": "Raspberry Pi OS, 32-bit (command line only)",
    "linux-x86_64-musl-static": "Linux, 64-bit, static (command line only)",
    "linux-arm64-musl-static": "Linux, ARM 64-bit, static (command line only)",
    "freebsd-x86_64": "FreeBSD, 64-bit (command line only)",
    "openbsd-x86_64": "OpenBSD, 64-bit (command line only)",
    "netbsd-x86_64": "NetBSD, 64-bit (command line only)",
}

#: The workflow that decides what a release actually contains.
WORKFLOW = os.path.join(".github", "workflows", "release.yml")

#: The first release that publishes a contents list. See marker 97.
CONTENTS_FROM = (0, 1, 15)


def archives():
    """Every archive a release publishes, as `(label, filename pattern)`.

    **F-101.** This was a hand-written list of five, kept beside the build
    matrix by nothing but attention, and the two had drifted: it linked
    `macos-aarch64` and `linux-aarch64`, which have never existed under those
    names, and it omitted six platforms that do. Two dead links and six missing
    ones, on every release entry, on the page whose entire job is to be the
    list of downloads.

    That is F-71's shape again -- two things only ever compared against each
    other -- so the fix is not to correct the five names. `release.yml` is the
    file that decides what gets built and what each archive is called, and this
    reads it. A platform added to the matrix appears here; a label renamed
    there cannot leave a dead link here.

    Parsed with a regular expression rather than a YAML library, because this
    project's website build has no dependencies and adding one for eleven lines
    would be the larger cost. The shape being matched is the matrix's own
    `label:` and `archive:` pair, and the three BSD jobs name their output
    directly; both are asserted to be present, so a workflow rewritten into a
    shape this cannot read fails the build rather than quietly publishing a
    page with no downloads on it.
    """
    text = read(os.path.join(ROOT, WORKFLOW))
    found = []

    # The build matrix: a `label:` and, below it, the `archive:` kind.
    for match in re.finditer(
        r"^\s*label:\s*(\S+)\s*$\n(?:^\s*#.*$\n)*^\s*archive:\s*(\S+)\s*$",
        text,
        re.M,
    ):
        found.append((match.group(1), match.group(2)))

    # The BSD jobs, which are not in that matrix and name their archive in the
    # staging step. Always a tarball; there is no BSD zip.
    for match in re.finditer(r'out="veilvoice-\$\{\{[^}]*\}\}-(\S+?)"', text):
        found.append((match.group(1), "tar.gz"))

    if len(found) < 5:
        raise SystemExit(
            "%s: only %d archives could be read out of %s.\n"
            "  The page's download list is derived from that workflow, so a\n"
            "  shape this cannot read would publish a page with no downloads."
            % (OUT, len(found), WORKFLOW)
        )

    out = []
    seen = set()
    for label, kind in found:
        if label in seen:
            continue
        seen.add(label)
        out.append((PLATFORMS.get(label, label), "veilvoice-v{v}-%s.%s" % (label, kind)))
    return out


#: The three files every release carries beside its archives.
BESIDE = [
    ("SHA256SUMS", "the hash of every file above"),
    ("SHA256SUMS.asc", "the signature over that list"),
    ("veilvoice-signing-key.asc", "the public key it was signed with"),
]


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read().replace("\r\n", "\n")


def releases(text):
    """Every `## vX.Y.Z` heading and the lines under it, newest first."""
    lines = text.split("\n")
    found = []
    current = None
    for line in lines:
        match = re.fullmatch(r"## v(\d+\.\d+\.\d+)\s*", line)
        if match:
            current = {"version": match.group(1), "body": []}
            found.append(current)
            continue
        # A new top-level heading that is not a release ends the one before it,
        # so `## Unreleased` above them does not swallow the first release and
        # anything after the last does not get appended to it.
        if line.startswith("## ") and current is not None:
            current = None
            continue
        if current is not None:
            current["body"].append(line)
    return found


def earlier(text):
    """The versions covered by a combined `## vX.Y.Z and earlier` heading.

    `CHANGELOG.md` keeps one section for the first six releases, which says in
    full: "See the release notes for each tag." That is honest and it left them
    off this page entirely, because the pattern above matches `## vX.Y.Z` and
    nothing else. Six published versions with no entry, no summary and no
    download links, on the page whose whole job is to be the list.

    So the heading is read for what it says: every patch version of that series
    from zero up to and including the one named. This project has released
    0.1.0, 0.1.1 and so on with no gaps -- which is checked, by the version
    ordering guard added as marker 95 -- so the enumeration is a fact about the
    file rather than a guess about the world.

    Their notes genuinely are on their release pages and this page says so
    rather than inventing a summary for a section that has none.
    """
    match = re.search(r"^## v(\d+)\.(\d+)\.(\d+) and earlier\s*$", text, re.M)
    if not match:
        return []
    major, minor, patch = (int(part) for part in match.groups())
    return ["%d.%d.%d" % (major, minor, n) for n in range(patch, -1, -1)]


def unreleased(text):
    """The lines under `## Unreleased`, which is what the next version holds."""
    lines = text.split("\n")
    out = []
    taking = False
    for line in lines:
        if line.strip() == "## Unreleased":
            taking = True
            continue
        if taking and line.startswith("## "):
            break
        if taking:
            out.append(line)
    return out


def summary(body):
    """The first thing a release says about itself, for the closed heading.

    Three shapes appear in this file across nine releases, and taking the first
    line works for none of them:

    * A paragraph, hard-wrapped at about eighty columns. Taking one line stops
      mid-sentence, which produced "a window that does" for v0.1.14.
    * A paragraph opening in bold. A naive bullet test skips it and then takes
      the continuation, which produced "a console window and could fail with no
      message at all." for v0.1.11.
    * A `### Added` heading and then a bullet list, which is how the older
      releases are written. Skipping bullets takes the *continuation* of the
      first one, which produced "SHA-256 manifest of VeilVoice's own files"
      starting mid-sentence for v0.1.7.

    So the whole first block is collected, whatever shape it is, joined, and cut
    at a sentence. A bullet keeps its text and loses its marker: for those
    releases the first bullet genuinely is the first thing said.
    """
    block = []
    for line in body:
        text = line.strip()
        if not text:
            if block:
                break
            continue
        if text.startswith(("#", "|", ">", "```")):
            if block:
                break
            continue
        marker = re.match(r"(?:[-*+]\s+|\d+\.\s+)", text)
        if marker:
            if block:
                break
            text = text[marker.end():]
        block.append(text)
    if not block:
        return ""

    text = " ".join(block)
    text = re.sub(r"\(https?://[^)]*\)", "", text)
    text = re.sub(r"[*`_\[\]]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    stop = text.find(". ")
    if stop > 30:
        text = text[: stop + 1]
    # Short enough to read as a label beside the version rather than as a
    # paragraph. The notes themselves open below and begin with this same
    # sentence, so a long one is printed twice on the release that is open by
    # default, which looks like a mistake.
    if len(text) > 72:
        text = text[:72].rsplit(" ", 1)[0] + "..."
    return text


def beside_for(version):
    """The files a release of this version carries beside its archives.

    `CONTENTS.sha256` is new in v0.1.15 and linking it on an older release
    would be a dead link among live ones, which teaches people that the links
    here are unreliable. So the version decides.
    """
    out = list(BESIDE)
    parts = tuple(int(n) for n in version.split("."))
    if parts >= CONTENTS_FROM:
        out.insert(
            1,
            (
                "CONTENTS.sha256",
                "the hash of every file inside those archives",
            ),
        )
    return out


def files_html(version):
    """The download list for one release."""
    base = "https://github.com/%s/releases/download/v%s/" % (docs.REPO, version)
    out = ['<div class="release-files">']
    out.append("<h4>Files</h4>")
    out.append("<ul>")
    for label, pattern in archives():
        name = pattern.format(v=version)
        out.append(
            '<li><a href="%s%s" rel="noopener noreferrer">%s</a> '
            '<span class="muted">%s</span></li>' % (base, name, label, name)
        )
    for name, what in beside_for(version):
        out.append(
            '<li><a href="%s%s" rel="noopener noreferrer">%s</a> '
            '<span class="muted">%s</span></li>' % (base, name, name, what)
        )
    out.append("</ul>")
    out.append(
        '<p class="muted">These links are worked out from the version number '
        "rather than fetched, so this page builds with no network. A release "
        "that did not build for a platform answers with a not-found; "
        '<a href="https://github.com/%s/releases/tag/v%s" '
        'rel="noopener noreferrer">the release page</a> is the definitive '
        "list.</p>" % (docs.REPO, version)
    )
    out.append("</div>")
    return out


def build():
    text = read(os.path.join(ROOT, SOURCE))
    found = releases(text)
    if not found:
        raise SystemExit(
            "%s has no `## vX.Y.Z` headings, so the page would be empty.\n"
            "  Each release is a level two heading naming its version." % SOURCE
        )

    # One anchor pool for the whole page, not one per release. Every release
    # since v0.1.6 has a `### Added` and most have a `### Testing`, so a fresh
    # pool per release hands out the same `id` nine times over. `Anchors`
    # already suffixes repeats the way GitHub does; it just has to be told the
    # page is one document.
    anchors = docs.Anchors()

    def ids_for(lines):
        """The anchors `doc_html` will pop, one per heading, in order.

        `doc_html` takes a list it pops from rather than an `Anchors`, so the
        headings are counted here and the pool is shared across every release.
        """
        return [
            anchors.take(line.strip().lstrip("#").strip())
            for line in lines
            if line.strip().startswith("#")
        ]

    out = []
    out.append('<p class="muted">')
    out.append(
        "Every release, newest first. Open one to read what changed in it; "
        "its files are at the end of the notes. The notes are "
        '<a href="https://github.com/%s/blob/%s/CHANGELOG.md">CHANGELOG.md</a>, '
        "which is where they are written." % (docs.REPO, docs.REF)
    )
    out.append("</p>")

    pending = unreleased(text)
    # An `Unreleased` entry is worth showing when something is in it, and is
    # noise when it holds the placeholder that sits there between releases:
    # a dropdown at the top of the page promising unreleased changes and
    # containing "Nothing yet" is worse than no dropdown. A heading or a bullet
    # is what a real entry has; a sentence on its own is the placeholder.
    if any(line.strip().startswith(("#", "-", "*", "+")) for line in pending):
        out.append('<details class="release">')
        out.append(
            "<summary><strong>Unreleased</strong> "
            '<span class="muted">finished and waiting for the next version</span>'
            "</summary>"
        )
        out.extend(docs.doc_html(pending, ids_for(pending)))
        out.append("</details>")

    for index, release in enumerate(found):
        version = release["version"]
        # The newest one opens by default: somebody arriving here almost always
        # wants the one they are about to install.
        attrs = ' open' if index == 0 else ""
        out.append('<details class="release" id="v%s"%s>' % (version, attrs))
        line = summary(release["body"])
        out.append(
            "<summary><strong>v%s</strong> <span class=\"muted\">%s</span></summary>"
            % (version, docs.inline_html(line))
        )
        # The notes first and the files last, so opening a release shows what
        # changed in it rather than a wall of links. Somebody who came for the
        # download scrolls past the notes to reach them, which is the right way
        # round: the notes are what this page is for, and the release page on
        # GitHub is one click away for anybody who only wants a file.
        out.extend(docs.doc_html(release["body"], ids_for(release["body"])))
        out.extend(files_html(version))
        out.append("</details>")

    # Every version that predates the first section with notes of its own. They
    # are published releases and were missing from the list entirely.
    for version in earlier(text):
        out.append('<details class="release" id="v%s">' % version)
        out.append(
            "<summary><strong>v%s</strong> "
            '<span class="muted">notes on its own release page</span></summary>'
            % version
        )
        out.append(
            '<p class="muted">CHANGELOG.md keeps one section for v%s and '
            "earlier, and it says to read the notes for each tag rather than "
            "repeating them. This entry is here so the list is the whole list "
            "and the files are reachable; "
            '<a href="https://github.com/%s/releases/tag/v%s" '
            'rel="noopener noreferrer">the release page for v%s</a> is where '
            "its notes are.</p>" % (earlier(text)[0], docs.REPO, version, version)
        )
        out.extend(files_html(version))
        out.append("</details>")

    index_html = read(os.path.join(ROOT, "website", "index.html"))
    parts = split.shell(index_html)
    page = split.page(
        parts,
        "releases",
        "Releases",
        "Every version of VeilVoice, what changed in it, and where to get it.",
        "\n".join(out),
        # Its `#anchor` links point at its own releases, not at sections of the
        # front page.
        relink_body=False,
    )
    page = page.replace(
        '<p style="color:var(--muted)">This section is also part of '
        '<a href="index.html">the front page</a>, where it sits in context '
        "with the rest.</p>",
        '<p style="color:var(--muted)">The same notes as '
        '<a href="https://github.com/%s/blob/%s/CHANGELOG.md">CHANGELOG.md</a>.'
        "</p>" % (docs.REPO, docs.REF),
    )
    page = page.replace(
        "GENERATED by tools/site/split.py from website/index.html.",
        "%s from CHANGELOG.md." % MARKER,
    )
    return {OUT: page}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the page is not what this would write")
    args = parser.parse_args()

    written = build()
    if args.check:
        for rel, want in written.items():
            path = os.path.join(ROOT, rel)
            if not os.path.exists(path):
                print("missing: %s" % rel)
                return 1
            if read(path) != want:
                print("out of date: %s" % rel)
                print("  regenerate with: python tools/site/releases.py")
                return 1
        print("the releases page matches %s" % SOURCE)
        return 0

    for rel, body in written.items():
        path = os.path.join(ROOT, rel)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(body)
        print("wrote %s" % rel)
    return 0


if __name__ == "__main__":
    sys.exit(main())
