#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""The releases page: every version, its notes, and its files.

    python tools/site/releases.py           # write website/releases.html
    python tools/site/releases.py --check   # verify it is current

# Marker 94, and the problem it solves

Until now the only way to see what changed in a release was `CHANGELOG.md`,
which is thousands of lines and is written newest-first for somebody reading
top to bottom, and the only way to reach the files was GitHub's releases page,
which is a different site with a different layout.

Somebody who wants "what is in the newest one, and where do I download it"
had to visit two places and scroll a lot in one of them. This page is both, in
one, with every release collapsed to its heading so the list is readable at a
glance and any one of them opening in place.

# Why the notes come from CHANGELOG.md

The same reason the questions page comes from `docs/FAQ.md`: that file is
readable on GitHub, in a checkout, and by anybody who has never opened the
website, and it is where the notes are actually written. A second hand-kept
copy of release notes is F-41 waiting to happen, and F-71 says what happens
when two hand-typed things are only ever compared against each other.

# The download links are derived from the naming, not from the network

Nothing here fetches anything: this project's build talks to no servers, and a
generator that asked GitHub what files a release has would make the website
un-buildable offline and un-reproducible. The archive names follow a fixed
pattern per platform, so the links are constructed from the version and the
pattern, and the page says plainly that it is linking rather than listing.

That has one honest consequence, stated on the page: a link here is a link to
where a file *should* be. GitHub answers with a 404 for a platform a given
release did not build, and the release page itself is one click away for
anybody who wants the definitive list.

# In plain words

Every version of VeilVoice, newest first, with what changed in it and where to
get it.

Click a version to open its notes without leaving the page. The download links
are worked out from the version number rather than fetched, so this page builds
with no network, and the release page on GitHub is always one click away if a
file is not where the pattern says.
"""

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tools", "docs"))
sys.path.insert(0, os.path.join(ROOT, "tools", "site"))

import generate as docs  # noqa: E402
import split  # noqa: E402

SOURCE = "CHANGELOG.md"
OUT = os.path.join("website", "releases.html")
MARKER = "GENERATED by tools/site/releases.py"

#: How a platform's label reads to somebody choosing a download.
#:
#: The labels themselves come from `release.yml` and are made for a build
#: matrix; "linux-arm64-musl-static" is exact and is not what somebody scanning
#: a list of downloads is looking for. Anything not named here falls back to
#: its label, so a platform added to the matrix appears on the page with an
#: ugly name rather than not at all.
PLATFORMS = {
    "windows-x86_64": "Windows, 64-bit",
    "macos-arm64": "macOS, Apple silicon",
    "macos-x86_64": "macOS, Intel",
    "linux-x86_64": "Linux, 64-bit",
    "linux-arm64": "Linux, ARM 64-bit",
    "linux-armv7-pi": "Raspberry Pi OS, 32-bit (command line only)",
    "linux-x86_64-musl-static": "Linux, 64-bit, static (command line only)",
    "linux-arm64-musl-static": "Linux, ARM 64-bit, static (command line only)",
    "freebsd-x86_64": "FreeBSD, 64-bit (command line only)",
    "openbsd-x86_64": "OpenBSD, 64-bit (command line only)",
    "netbsd-x86_64": "NetBSD, 64-bit (command line only)",
}

#: The workflow that decides what a release actually contains.
WORKFLOW = os.path.join(".github", "workflows", "release.yml")

#: The first release that publishes a contents list. See marker 97.
CONTENTS_FROM = (0, 1, 15)


# --- checking a download ----------------------------------------------------
#
# The releases page is where somebody lands with a file they have just
# downloaded, and it was the one page that told them what changed without
# telling them how to check it. `docs/INSTALL.md` has always carried the
# instructions; a reader on this page had to know that and go and find it.
#
# So the tutorial is here as well, and it is **generated**, for the reason
# everything else on this site is: two hand-kept copies of a command are two
# copies that drift, and the copy on the page nobody edits is the one that goes
# wrong. Every command below is checked against the verifier's own help text,
# read out of `crates/veilvoice-verify/src/lib.rs`, when this page is built. A
# subcommand that is renamed or dropped fails the build here rather than
# teaching somebody to type something that no longer works.

VERIFIER_SOURCE = os.path.join("crates", "veilvoice-verify", "src", "lib.rs")

# Where the Verify tab's capture goes. A line of its own in the Markdown, swapped
# for markup after rendering.
FIGURE = "<!--verify-tab-figure-->"

# Where the documentation is, linked twice: to the file on GitHub, which is
# where it is written and where somebody with a checkout already has it, and to
# the page on this site that covers the same ground where there is one.
#
# Two links rather than a choice between them. The file is the source and reads
# the same in a terminal, a checkout and a release archive; the page is styled,
# searchable and does not require leaving the site. A reader wants whichever of
# those they are already in the middle of.
DOCS = [
    ("USER_GUIDE.md", "The whole application, screen by screen", "guide.html"),
    ("GUIDE_CLI.md", "Every command line command, with worked examples", None),
    ("GUIDE_GUI.md", "The desktop application on its own", None),
    ("GUIDE_VERIFY.md", "Checking a download, at length", "verify.html"),
    ("INSTALL.md", "Installing and verifying, per operating system", "download.html"),
    ("FAQ.md", "The questions people actually ask", "faq.html"),
    ("WHITEPAPER.md", "What the veiling does and why it cannot be undone",
     "crypto.html"),
    ("REPRODUCIBLE_BUILDS.md", "Building it yourself and comparing", None),
    ("SELF_SIGNING.md", "The code-signing certificate, and importing it", None),
    ("PACKAGING.md", "The deb, the RPM, the AUR recipe and the rest", None),
    ("USING_THE_CRATES.md", "Using VeilVoice as a library", None),
    ("AUDIT.md", "Every defect found and fixed, in order", None),
]
FIGURE_HTML = (
    '<figure class="shot">'
    '<img src="assets/screenshots/gui-verify.png" '
    'alt="the Verify tab, with a slot each for the archive, SHA256SUMS and '
    'SHA256SUMS.asc" loading="lazy" width="1400" height="1000">'
    "<figcaption><strong>The Verify tab.</strong> All three slots are shown "
    "before anything is dropped, and each of the three answers is drawn on its "
    "own.</figcaption>"
    "</figure>"
)

# The signing key's fingerprint, read from the crate that carries it rather
# than typed again. This is the one value in the whole chain that a person has
# to compare by eye, so a wrong copy of it here would be the worst possible
# defect on a page about verification.
FINGERPRINT_SOURCE = os.path.join("crates", "veilvoice-check", "src", "lib.rs")


def verifier_usage():
    """The verifier's own `--help` text, out of the source that prints it."""
    source = read(os.path.join(ROOT, VERIFIER_SOURCE))
    start = source.index('const USAGE: &str = "')
    end = source.index('\n";', start)
    return source[start:end]


def fingerprint():
    """The signing key fingerprint, from the constant the programs compare."""
    source = read(os.path.join(ROOT, FINGERPRINT_SOURCE))
    found = re.search(r'pub const FINGERPRINT: &str = "([0-9A-F]{40})";', source)
    if not found:
        raise SystemExit(
            "%s no longer declares FINGERPRINT, so the page cannot state the "
            "fingerprint without typing it again" % FINGERPRINT_SOURCE
        )
    digits = found.group(1)
    return " ".join(digits[i:i + 4] for i in range(0, 40, 4))


# Each step: the heading, the command, and what a pass actually proves.
#
# The order is the order somebody meets the problem in, not the order the help
# lists them: the whole check first, then the pieces of it, then the parts that
# are about the *source* rather than the download.
VERIFY_CLI = [
    (
        "The whole check, in one command",
        "veilvoice verify",
        "Run it in the folder you downloaded to. It finds the release, checks "
        "the OpenPGP signature over `SHA256SUMS`, checks every archive against "
        "that list, checks `CONTENTS.sha256` against it as well, and then "
        "checks **every file you extracted** against `CONTENTS.sha256`. Each "
        "step runs only if the one before it passed. Entirely offline.",
    ),
    (
        "The same, pointed at a folder",
        "veilvoice verify auto ~/Downloads",
        "A named directory is checked and nothing else is searched. A path "
        "that is not there is refused by name rather than answered with a "
        "verdict about somewhere else.",
    ),
    (
        "The signature over the hash list, on its own",
        "veilvoice verify sums SHA256SUMS SHA256SUMS.asc",
        "This is the step everything else rests on. `SHA256SUMS` is a list of "
        "numbers; `SHA256SUMS.asc` is the detached OpenPGP signature over it. "
        "Until that signature checks out against the signing key, the list is "
        "just numbers somebody sent you.",
    ),
    (
        "One file, against the signed list",
        "veilvoice verify file veilvoice-vVERSION-linux-x86_64.tar.gz "
        "--sums SHA256SUMS --sig SHA256SUMS.asc",
        "The signature is verified **first**, and the file is compared against "
        "the list only after that passes. A pass means the download is "
        "**INTACT**: byte for byte the file that was published, signed by the "
        "VeilVoice key.",
    ),
    (
        "One file, with no hash list at all",
        "veilvoice verify file veilvoice-vVERSION-linux-x86_64.tar.gz "
        "--sha256 THE_HASH_YOU_WERE_GIVEN",
        "For when you have a hash rather than a signed list. What a match "
        "proves depends entirely on where that hash came from, and only you "
        "know that, so the tool says so instead of guessing. If it came from "
        "somebody else's independent build of the same tag, a match means the "
        "release is **REPRODUCIBLE**, which is the stronger claim.",
    ),
    (
        "Just the hash, verifying nothing",
        "veilvoice verify hash veilvoice-vVERSION-linux-x86_64.tar.gz",
        "Prints the SHA-256 and checks nothing, for when you want to compare "
        "it against something yourself.",
    ),
    (
        "The same check through your own GnuPG",
        "veilvoice verify gnupg",
        "The one thing no program can do for itself: the tool telling you a "
        "download is genuine came out of that download. This runs the `gpg` on "
        "your machine over the same signature, says it added the public key "
        "and how to remove it again, and prints the commands so you can run "
        "them yourself.",
    ),
    (
        "The key it is checking against",
        "veilvoice verify key",
        "Prints the signing key compiled into the program, and its "
        "fingerprint. Compare it against the fingerprint at the top of this "
        "section, against `README.md`, and against the website. It is the one "
        "step nothing can do for you.",
    ),
    (
        "What a pass actually proves",
        "veilvoice verify --explain",
        "INTACT and REPRODUCIBLE are different claims, and this is the "
        "difference written out in full.",
    ),
]

# The half about the source rather than the download. Separate because it
# answers a different question and takes a great deal longer.
VERIFY_BUILD = [
    (
        "What a build needs on this machine",
        "veilvoice verify deps",
        "What is required to build VeilVoice here and which of it is already "
        "present. `--install` offers the missing pieces one at a time with the "
        "exact command shown before each question.",
    ),
    (
        "Build it, and compare against the published hashes",
        "veilvoice verify reproduce . --sums SHA256SUMS --sig SHA256SUMS.asc",
        "A signature says who made a file. Only a build says what it is made "
        "of. This compiles the workspace here and compares what came out "
        "against the published hashes for this platform, with the signature "
        "verified before any hash from the list is read. A difference is a "
        "**finding**, not an accusation: both hashes are printed and the exit "
        "status is deliberately not the one that means tampering.",
    ),
]

# Doing it entirely with tools that are not VeilVoice's. Taken from the same
# list `veilvoice verify gnupg` prints, in `veilvoice-gnupg`, so the page and
# the program cannot come to say different things.
BY_HAND = [
    "gpg --import veilvoice-signing-key.asc",
    "gpg --verify SHA256SUMS.asc SHA256SUMS",
    "sha256sum -c SHA256SUMS --ignore-missing",
]

GUI_STEPS = [
    "Open **Verify** in the desktop application. Three slots are shown before "
    "you drop anything, because verifying needs three files and an interface "
    "that discovers that after the drop teaches people it is fiddly.",
    "Drop the **archive** you downloaded, the **`SHA256SUMS`** and the "
    "**`SHA256SUMS.asc`** on the window. A drop fills whichever slot the "
    "file's name says it is, in any order.",
    "Press the button once. It checks the signature over the hash list, then "
    "the archive against that list, then every file extracted out of the "
    "archive against the signed contents list, and then runs the GnuPG on "
    "this machine over the same signature.",
    "Read the three answers, which are drawn separately on purpose so a pass "
    "on one is never mistaken for a pass on another. A release published "
    "before v0.1.15 carries no contents list and simply has no such row. A "
    "GnuPG that will not run on this machine is drawn quietly: that is a fact "
    "about the computer and says nothing about the download.",
]


def check_verify_commands():
    """Every command shown on this page must exist in the verifier's help.

    The page is generated and the help is the source, so a subcommand renamed
    or dropped stops the build rather than leaving an instruction that fails
    for somebody who followed it. `veilvoice-verify` was a separate program
    until 0.1.18 and nine places went on saying so for a release; this is the
    same class of drift, caught before it is published rather than after.
    """
    usage = verifier_usage()
    missing = []
    for _title, command, _why in VERIFY_CLI + VERIFY_BUILD:
        words = command.split()
        # `veilvoice verify <sub>`, which is what the help lists.
        head = " ".join(words[:3])
        if head not in usage:
            missing.append(command)
            continue
        for word in words[3:]:
            if word.startswith("--") and word not in usage:
                missing.append("%s (the flag %s)" % (command, word))
    if missing:
        raise SystemExit(
            "these commands are on the releases page and not in the "
            "verifier's own help in %s:\n    %s\n"
            "  Either the help changed and the page has not, or the page is "
            "wrong. Fix whichever it is rather than removing this check."
            % (VERIFIER_SOURCE, "\n    ".join(missing))
        )


def verify_markdown(version):
    """The tutorial, as Markdown, for the same renderer the notes use."""
    check_verify_commands()
    out = []
    add = out.append

    add("## Check a download before you run it")
    add("")
    add("Every archive below is signed, and every release publishes the two "
        "files that let you check it: `SHA256SUMS`, a list of hashes, and "
        "`SHA256SUMS.asc`, the detached OpenPGP signature over that list. "
        "From v0.1.15 there is a third, `CONTENTS.sha256`, which is itself "
        "covered by `SHA256SUMS` and lists every file **inside** each archive, "
        "so the binary you are about to run can be checked and not merely the "
        "zip it arrived in.")
    add("")
    add("The signing key's fingerprint is:")
    add("")
    add("```")
    add(fingerprint())
    add("```")
    add("")
    add("Comparing that against the copy in `README.md` and the copy on the "
        "front page is the one step no program can do for you, because a "
        "program that came out of the download cannot vouch for the download.")
    add("")
    add("**The chain, end to end.** Every check below is one link in this, and "
        "each link is only worth anything if the one above it held:")
    add("")
    add("1. `SHA256SUMS.asc` is a detached OpenPGP signature, made with the "
        "key above, **over `SHA256SUMS`**. Verifying it is what ties "
        "everything under it to a person rather than to whoever served you "
        "the files. Skip it and the hash list is numbers of unknown origin, "
        "and comparing your file against numbers of unknown origin proves "
        "nothing at all.")
    add("2. `SHA256SUMS` holds the hash of **each archive** and the hash of "
        "**`CONTENTS.sha256`**, so the contents list is signed as well, by "
        "being covered by the list the signature is over.")
    add("3. `CONTENTS.sha256` holds the hash of **every file inside each "
        "archive**: `veilvoice`, `veilvoice-gui`, and everything shipped "
        "beside them.")
    add("")
    add("So the hash of the binary you are about to run traces back, link by "
        "link, to that one signature. Checking the archive stops at step 2 "
        "and tells you the *zip* was published; going on to step 3 tells you "
        "the *program* was, which is the question somebody actually has. "
        "Releases before v0.1.15 publish no `CONTENTS.sha256` and stop at "
        "step 2, and every command here says so at the time rather than "
        "quietly checking less.")
    add("")

    add("### With VeilVoice itself, no GnuPG required")
    add("")
    add("The verifier is part of `veilvoice`: it is not a separate download, "
        "and it carries the signing key compiled in, so it needs no GnuPG, no "
        "keyring and no network.")
    add("")
    for title, command, why in VERIFY_CLI:
        add("**%s**" % title)
        add("")
        add("```")
        add(command.replace("VERSION", version))
        add("```")
        add("")
        add(why)
        add("")

    add("### The same thing, with your own GnuPG and nothing of ours")
    add("")
    add("Three commands, in the folder you downloaded to. This is what "
        "`veilvoice verify gnupg` runs and prints, and it is worth typing "
        "yourself: the second opinion is the whole point.")
    add("")
    add("```")
    for command in BY_HAND:
        add(command)
    add("```")
    add("")
    add("`gpg --verify` answers whether the hash list is the one that was "
        "signed with the key above. `sha256sum -c` answers whether your files "
        "match that list. Both have to pass, and in that order: a hash list "
        "nobody checked the signature of proves nothing at all. On macOS and "
        "the BSDs the last command is `shasum -a 256 -c SHA256SUMS` or "
        "`sha256 -c SHA256SUMS`; the first two are the same everywhere.")
    add("")

    add("### In the desktop application")
    add("")
    add("`veilvoice-gui` runs the same code with the same key, so the answer "
        "is the same one; only the typing is different.")
    add("")
    for index, step in enumerate(GUI_STEPS, 1):
        add("%d. %s" % (index, step))
    add("")
    # The tab itself, as a sentinel the builder replaces with markup: this
    # renderer escapes raw HTML, which is right for it and means a picture has
    # to be put in from outside.
    #
    # A capture rather than a drawing. The file is re-taken from the running
    # window on every build, which is the difference between showing somebody
    # the program and showing them what it used to look like.
    add(FIGURE)
    add("")

    add("### Checking the source rather than the download")
    add("")
    for title, command, why in VERIFY_BUILD:
        add("**%s**" % title)
        add("")
        add("```")
        add(command)
        add("```")
        add("")
        add(why)
        add("")

    add("### What each answer is worth")
    add("")
    add("- **INTACT** means your file is byte for byte the one that was "
        "published: not truncated, not corrupted in transit, not swapped by "
        "whoever served it to you. The hash came from the signed list.")
    add("- **REPRODUCIBLE** is the stronger claim and needs a hash from "
        "somewhere else: somebody else's independent build of the same tagged "
        "source. It says the published binary corresponds to the published "
        "source, which a signature alone cannot.")
    add("- **A GnuPG that will not run** is a fact about your computer. It is "
        "not a failed check and nothing here treats it as one.")
    add("")
    add("Full instructions per platform, including Windows and the BSDs, are "
        "in [`docs/INSTALL.md`](https://github.com/%s/blob/%s/docs/INSTALL.md)."
        % (docs.REPO, docs.REF))
    return out


def docs_html():
    """Where every document is, on GitHub and on this site.

    A release archive ships `docs/` inside it, the repository holds the same
    files, and this website renders several of them. Somebody who has just
    downloaded VeilVoice has all three and no reason to know that, so the list
    is here, with both links where both exist.
    """
    out = []
    out.append('<details class="release" id="the-documentation">')
    out.append(
        "<summary><strong>The documentation</strong> "
        '<span class="muted">every guide, on GitHub and on this site, and in '
        "the archive you just downloaded</span></summary>"
    )
    out.append(
        '<p class="muted">Each of these is a file in <code>docs/</code>. Every '
        "release archive carries the whole folder, so once you have unpacked "
        "one you have all of it offline. The first link is the file as it is "
        "written; the second, where there is one, is the same ground covered "
        "as a page of this site.</p>"
    )
    out.append("<table><thead><tr><th>Document</th><th>What it covers</th>"
               "<th>On this site</th></tr></thead><tbody>")
    for name, what, page in DOCS:
        here = ('<a href="%s">%s</a>' % (page, page[:-5])) if page else "&mdash;"
        out.append(
            '<tr><td><a href="https://github.com/%s/blob/%s/docs/%s" '
            'rel="noopener noreferrer"><code>%s</code></a></td>'
            "<td>%s</td><td>%s</td></tr>"
            % (docs.REPO, docs.REF, name, name, docs.esc(what), here)
        )
    out.append("</tbody></table>")
    out.append(
        '<p class="muted">The generated reference for every crate and every '
        'source file is under <a href="wiki.html">the reference</a>, and the '
        'same pages are in <a href="https://github.com/%s/wiki" '
        'rel="noopener noreferrer">the wiki</a>.</p>' % docs.REPO
    )
    out.append("</details>")
    return out


def archives():
    """Every archive a release publishes, as `(label, filename pattern)`.

    **F-101.** This was a hand-written list of five, kept beside the build
    matrix by nothing but attention, and the two had drifted: it linked
    `macos-aarch64` and `linux-aarch64`, which have never existed under those
    names, and it omitted six platforms that do. Two dead links and six missing
    ones, on every release entry, on the page whose entire job is to be the
    list of downloads.

    That is F-71's shape again -- two things only ever compared against each
    other -- so the fix is not to correct the five names. `release.yml` is the
    file that decides what gets built and what each archive is called, and this
    reads it. A platform added to the matrix appears here; a label renamed
    there cannot leave a dead link here.

    Parsed with a regular expression rather than a YAML library, because this
    project's website build has no dependencies and adding one for eleven lines
    would be the larger cost. The shape being matched is the matrix's own
    `label:` and `archive:` pair, and the three BSD jobs name their output
    directly; both are asserted to be present, so a workflow rewritten into a
    shape this cannot read fails the build rather than quietly publishing a
    page with no downloads on it.
    """
    text = read(os.path.join(ROOT, WORKFLOW))
    found = []

    # The build matrix: a `label:` and, below it, the `archive:` kind.
    for match in re.finditer(
        r"^\s*label:\s*(\S+)\s*$\n(?:^\s*#.*$\n)*^\s*archive:\s*(\S+)\s*$",
        text,
        re.M,
    ):
        found.append((match.group(1), match.group(2)))

    # The BSD jobs, which are not in that matrix and name their archive in the
    # staging step. Always a tarball; there is no BSD zip.
    for match in re.finditer(r'out="veilvoice-\$\{\{[^}]*\}\}-(\S+?)"', text):
        found.append((match.group(1), "tar.gz"))

    if len(found) < 5:
        raise SystemExit(
            "%s: only %d archives could be read out of %s.\n"
            "  The page's download list is derived from that workflow, so a\n"
            "  shape this cannot read would publish a page with no downloads."
            % (OUT, len(found), WORKFLOW)
        )

    out = []
    seen = set()
    for label, kind in found:
        if label in seen:
            continue
        seen.add(label)
        out.append((PLATFORMS.get(label, label), "veilvoice-v{v}-%s.%s" % (label, kind)))
    return out


#: The three files every release carries beside its archives.
BESIDE = [
    ("SHA256SUMS", "the hash of every file above"),
    ("SHA256SUMS.asc", "the signature over that list"),
    ("veilvoice-signing-key.asc", "the public key it was signed with"),
]


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read().replace("\r\n", "\n")


def releases(text):
    """Every `## vX.Y.Z` heading and the lines under it, newest first."""
    lines = text.split("\n")
    found = []
    current = None
    for line in lines:
        match = re.fullmatch(r"## v(\d+\.\d+\.\d+)\s*", line)
        if match:
            current = {"version": match.group(1), "body": []}
            found.append(current)
            continue
        # A new top-level heading that is not a release ends the one before it,
        # so `## Unreleased` above them does not swallow the first release and
        # anything after the last does not get appended to it.
        if line.startswith("## ") and current is not None:
            current = None
            continue
        if current is not None:
            current["body"].append(line)
    return found


def earlier(text):
    """The versions covered by a combined `## vX.Y.Z and earlier` heading.

    `CHANGELOG.md` keeps one section for the first six releases, which says in
    full: "See the release notes for each tag." That is honest and it left them
    off this page entirely, because the pattern above matches `## vX.Y.Z` and
    nothing else. Six published versions with no entry, no summary and no
    download links, on the page whose whole job is to be the list.

    So the heading is read for what it says: every patch version of that series
    from zero up to and including the one named. This project has released
    0.1.0, 0.1.1 and so on with no gaps -- which is checked, by the version
    ordering guard added as marker 95 -- so the enumeration is a fact about the
    file rather than a guess about the world.

    Their notes genuinely are on their release pages and this page says so
    rather than inventing a summary for a section that has none.
    """
    match = re.search(r"^## v(\d+)\.(\d+)\.(\d+) and earlier\s*$", text, re.M)
    if not match:
        return []
    major, minor, patch = (int(part) for part in match.groups())
    return ["%d.%d.%d" % (major, minor, n) for n in range(patch, -1, -1)]


def unreleased(text):
    """The lines under `## Unreleased`, which is what the next version holds."""
    lines = text.split("\n")
    out = []
    taking = False
    for line in lines:
        if line.strip() == "## Unreleased":
            taking = True
            continue
        if taking and line.startswith("## "):
            break
        if taking:
            out.append(line)
    return out


def summary(body):
    """The first thing a release says about itself, for the closed heading.

    Three shapes appear in this file across nine releases, and taking the first
    line works for none of them:

    * A paragraph, hard-wrapped at about eighty columns. Taking one line stops
      mid-sentence, which produced "a window that does" for v0.1.14.
    * A paragraph opening in bold. A naive bullet test skips it and then takes
      the continuation, which produced "a console window and could fail with no
      message at all." for v0.1.11.
    * A `### Added` heading and then a bullet list, which is how the older
      releases are written. Skipping bullets takes the *continuation* of the
      first one, which produced "SHA-256 manifest of VeilVoice's own files"
      starting mid-sentence for v0.1.7.

    So the whole first block is collected, whatever shape it is, joined, and cut
    at a sentence. A bullet keeps its text and loses its marker: for those
    releases the first bullet genuinely is the first thing said.
    """
    # A block that is nothing but a bold label is a heading written in bold
    # rather than with hashes, and saying nothing more than that. `v0.1.17`
    # opens `**In short**`, and taking it gave a row in the list reading
    # "v0.1.17  In short", which is a label that labels nothing. Skip those and
    # take the block under them. Now that every release on the page is closed
    # by default, this line is all a reader has to go on.
    LABEL = re.compile(r"^\*\*[^*]{1,40}\*\*[.:]?$")

    block = []
    for line in body:
        text = line.strip()
        if not text:
            if block:
                break
            continue
        if text.startswith(("#", "|", ">", "```")) or LABEL.match(text):
            if block:
                break
            continue
        marker = re.match(r"(?:[-*+]\s+|\d+\.\s+)", text)
        if marker:
            if block:
                break
            text = text[marker.end():]
        block.append(text)
    if not block:
        return ""

    text = " ".join(block)
    text = re.sub(r"\(https?://[^)]*\)", "", text)
    text = re.sub(r"[*`_\[\]]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    stop = text.find(". ")
    if stop > 30:
        text = text[: stop + 1]
    # Short enough to read as a label beside the version rather than as a
    # paragraph. The notes themselves open below and begin with this same
    # sentence, so a long one is printed twice on the release that is open by
    # default, which looks like a mistake.
    if len(text) > 72:
        text = text[:72].rsplit(" ", 1)[0] + "..."
    return text


def beside_for(version):
    """The files a release of this version carries beside its archives.

    `CONTENTS.sha256` is new in v0.1.15 and linking it on an older release
    would be a dead link among live ones, which teaches people that the links
    here are unreliable. So the version decides.
    """
    out = list(BESIDE)
    parts = tuple(int(n) for n in version.split("."))
    if parts >= CONTENTS_FROM:
        out.insert(
            1,
            (
                "CONTENTS.sha256",
                "the hash of every file inside those archives",
            ),
        )
    return out


def files_html(version):
    """The download list for one release."""
    base = "https://github.com/%s/releases/download/v%s/" % (docs.REPO, version)
    out = ['<div class="release-files">']
    out.append("<h4>Files</h4>")
    out.append("<ul>")
    for label, pattern in archives():
        name = pattern.format(v=version)
        out.append(
            '<li><a href="%s%s" rel="noopener noreferrer">%s</a> '
            '<span class="muted">%s</span></li>' % (base, name, label, name)
        )
    for name, what in beside_for(version):
        out.append(
            '<li><a href="%s%s" rel="noopener noreferrer">%s</a> '
            '<span class="muted">%s</span></li>' % (base, name, name, what)
        )
    out.append("</ul>")
    out.append(
        '<p class="muted">These links are worked out from the version number '
        "rather than fetched, so this page builds with no network. A release "
        "that did not build for a platform answers with a not-found; "
        '<a href="https://github.com/%s/releases/tag/v%s" '
        'rel="noopener noreferrer">the release page</a> is the definitive '
        "list.</p>" % (docs.REPO, version)
    )
    out.append("</div>")
    return out


def build():
    text = read(os.path.join(ROOT, SOURCE))
    found = releases(text)
    if not found:
        raise SystemExit(
            "%s has no `## vX.Y.Z` headings, so the page would be empty.\n"
            "  Each release is a level two heading naming its version." % SOURCE
        )

    # One anchor pool for the whole page, not one per release. Every release
    # since v0.1.6 has a `### Added` and most have a `### Testing`, so a fresh
    # pool per release hands out the same `id` nine times over. `Anchors`
    # already suffixes repeats the way GitHub does; it just has to be told the
    # page is one document.
    anchors = docs.Anchors()

    def ids_for(lines):
        """The anchors `doc_html` will pop, one per heading, in order.

        `doc_html` takes a list it pops from rather than an `Anchors`, so the
        headings are counted here and the pool is shared across every release.
        """
        return [
            anchors.take(line.strip().lstrip("#").strip())
            for line in lines
            if line.strip().startswith("#")
        ]

    out = []
    out.append('<p class="muted">')
    out.append(
        "Every release, newest first. Open one to read what changed in it; "
        "its files are at the end of the notes. The notes are "
        '<a href="https://github.com/%s/blob/%s/CHANGELOG.md">CHANGELOG.md</a>, '
        "which is where they are written." % (docs.REPO, docs.REF)
    )
    out.append("</p>")

    # The tutorial, above the list. Somebody arrives here holding a file they
    # have just downloaded, and "what changed" is the second question they have.
    # Open by default rather than collapsed: a verification step behind a
    # disclosure triangle is a verification step most people will not take.
    newest = found[0]["version"]
    tutorial = verify_markdown(newest)
    out.append('<details class="release" id="verify-a-download" open>')
    out.append(
        "<summary><strong>Check a download</strong> "
        '<span class="muted">the signature, the hashes, and the files inside '
        "the archive, from the command line or the window</span></summary>"
    )
    # The tutorial's own `##` heading would repeat the summary above it, so the
    # renderer is given the body from the first `###` down.
    body = tutorial[tutorial.index("### With VeilVoice itself, no GnuPG required"):]
    preamble = tutorial[1:tutorial.index("### With VeilVoice itself, no GnuPG required")]
    out.extend(docs.doc_html(preamble, ids_for(preamble)))
    # The capture sits between two rendered halves rather than inside either,
    # because the renderer escapes markup and should go on doing so.
    at = body.index(FIGURE)
    before, after = body[:at], body[at + 1:]
    out.extend(docs.doc_html(before, ids_for(before)))
    out.append(FIGURE_HTML)
    out.extend(docs.doc_html(after, ids_for(after)))
    out.append("</details>")

    out.extend(docs_html())

    pending = unreleased(text)
    # An `Unreleased` entry is worth showing when something is in it, and is
    # noise when it holds the placeholder that sits there between releases:
    # a dropdown at the top of the page promising unreleased changes and
    # containing "Nothing yet" is worse than no dropdown. A heading or a bullet
    # is what a real entry has; a sentence on its own is the placeholder.
    if any(line.strip().startswith(("#", "-", "*", "+")) for line in pending):
        out.append('<details class="release">')
        out.append(
            "<summary><strong>Unreleased</strong> "
            '<span class="muted">finished and waiting for the next version</span>'
            "</summary>"
        )
        out.extend(docs.doc_html(pending, ids_for(pending)))
        out.append("</details>")

    for release in found:
        version = release["version"]
        # **Every release is closed, including the newest.**
        #
        # The newest used to open by default, on the reasoning that somebody
        # arriving here wants the one they are about to install. That was true
        # about *which* release they want and wrong about what they want from
        # it. These notes run to hundreds of lines, so an open newest release
        # put a wall of prose between the top of the page and everything else
        # on it: the older releases, and the files.
        #
        # Closed, the page is a list of versions a reader can see the whole of,
        # and opening one is a decision rather than the default.
        out.append('<details class="release" id="v%s">' % version)
        line = summary(release["body"])
        out.append(
            "<summary><strong>v%s</strong> <span class=\"muted\">%s</span></summary>"
            % (version, docs.inline_html(line))
        )
        # **The files first, the notes under them.**
        #
        # This was the other way round, with a comment arguing that the notes
        # are what the page is for. They are what the page is *made of*; the
        # files are what somebody came for. Putting several hundred lines of
        # prose in front of the download links means scrolling past all of it
        # to reach them, every time, which is a poor trade for making a point
        # about what the page is for.
        out.extend(files_html(version))
        out.append('<details class="notes">')
        out.append(
            "<summary><strong>Release notes</strong> "
            '<span class="muted">everything that changed in v%s, in '
            "full</span></summary>" % version
        )
        out.extend(docs.doc_html(release["body"], ids_for(release["body"])))
        out.append(
            '<p class="muted">The same notes are in '
            '<a href="https://github.com/%s/blob/%s/CHANGELOG.md" '
            'rel="noopener noreferrer"><code>CHANGELOG.md</code></a>, where '
            "they are written, and at the top of "
            '<a href="https://github.com/%s/releases/tag/v%s" '
            'rel="noopener noreferrer">this release on GitHub</a>.</p>'
            % (docs.REPO, docs.REF, docs.REPO, version)
        )
        out.append("</details>")
        out.append("</details>")

    # Every version that predates the first section with notes of its own. They
    # are published releases and were missing from the list entirely.
    for version in earlier(text):
        out.append('<details class="release" id="v%s">' % version)
        out.append(
            "<summary><strong>v%s</strong> "
            '<span class="muted">notes on its own release page</span></summary>'
            % version
        )
        out.append(
            '<p class="muted">CHANGELOG.md keeps one section for v%s and '
            "earlier, and it says to read the notes for each tag rather than "
            "repeating them. This entry is here so the list is the whole list "
            "and the files are reachable; "
            '<a href="https://github.com/%s/releases/tag/v%s" '
            'rel="noopener noreferrer">the release page for v%s</a> is where '
            "its notes are.</p>" % (earlier(text)[0], docs.REPO, version, version)
        )
        out.extend(files_html(version))
        out.append("</details>")

    index_html = read(os.path.join(ROOT, "website", "index.html"))
    parts = split.shell(index_html)
    page = split.page(
        ROOT,
        parts,
        "releases",
        "Releases",
        "Every version of VeilVoice, what changed in it, and where to get it.",
        "\n".join(out),
        # Its `#anchor` links point at its own releases, not at sections of the
        # front page.
        relink_body=False,
    )
    page = page.replace(
        '<p style="color:var(--muted)">This section is also part of '
        '<a href="index.html">the front page</a>, where it sits in context '
        "with the rest.</p>",
        '<p style="color:var(--muted)">The same notes as '
        '<a href="https://github.com/%s/blob/%s/CHANGELOG.md">CHANGELOG.md</a>.'
        "</p>" % (docs.REPO, docs.REF),
    )
    page = page.replace(
        "GENERATED by tools/site/split.py from website/index.html.",
        "%s from CHANGELOG.md." % MARKER,
    )
    return {OUT: page}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the page is not what this would write")
    args = parser.parse_args()

    written = build()
    if args.check:
        for rel, want in written.items():
            path = os.path.join(ROOT, rel)
            if not os.path.exists(path):
                print("missing: %s" % rel)
                return 1
            if read(path) != want:
                print("out of date: %s" % rel)
                print("  regenerate with: python tools/site/releases.py")
                return 1
        print("the releases page matches %s" % SOURCE)
        return 0

    for rel, body in written.items():
        path = os.path.join(ROOT, rel)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(body)
        print("wrote %s" % rel)
    return 0


if __name__ == "__main__":
    sys.exit(main())
