#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""The roadmap, as a page anybody can read and a picture of where it has got to.

    python tools/site/roadmap.py           # write the page and the graphic
    python tools/site/roadmap.py --check   # verify they are current

# Why this is generated

`ROADMAP.md` is the file that decides what is done. It is also a two thousand
line document in a repository, which is the wrong shape for the question people
actually ask, which is "is this finished, and if not, what is left".

So this reads that file and writes two things: a picture of every marker
coloured by its state, and a page that puts the picture at the top and the list
under it. Neither is typed. A marker whose status changes in `ROADMAP.md`
changes here on the next run, and `--check` fails the build if it has not, which
is the same arrangement the documentation, the artwork and the search index
already have. A published roadmap that quietly disagrees with the roadmap would
be worse than not publishing one.

# What the picture shows, and what it deliberately does not

One square per marker, in the order the roadmap lists them, grouped by the
section headings that file already has. Colour is state and nothing else:
done, next, planned, blocked.

**Area is not progress.** Every square is the same size, and a marker is not a
day: marker 1 is the entire signal engine and marker 68 is a page of questions.
Reading the coloured fraction as "how far along this is" would be wrong, and the
page says so under the picture rather than leaving somebody to work it out. The
estimates, which are the closest thing to an answer, are in the text where they
can carry the sentence that goes with them.

**Blocked is its own colour, not a shade of unfinished.** Four markers are
blocked on a decision or on somebody else's rules rather than on effort, and
showing them as "not done yet" would promise work that is not going to happen
by working harder.

# In plain words

The roadmap is a long file in the source code. This turns it into a page with a
picture at the top, so somebody can see at a glance what is built and what is
not, without reading two thousand lines or taking anybody's word for it.

The picture is drawn from that file every time, so it cannot say something the
roadmap does not.

Pure standard library.
"""

import argparse
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))

sys.path.insert(0, os.path.join(ROOT, "tools", "docs"))
import generate as docs  # noqa: E402  (the path has to be set first)

sys.path.insert(0, HERE)
import split  # noqa: E402  (same)

MARKER = "GENERATED by tools/site/roadmap.py"

# A row in one of the roadmap's tables: number, marker, status, and sometimes an
# estimate. The status is bold in the file, which is what `\*\*` is doing here.
ROW = re.compile(
    r"^\|\s*(?P<number>\d+)\s*\|\s*(?P<marker>.+?)\s*\|\s*"
    r"\*\*(?P<status>done|next|planned|blocked)\*\*\s*\|"
    r"(?:\s*(?P<estimate>[^|]*?)\s*\|)?\s*$",
    re.M,
)

HEADING = re.compile(r"^## (?P<title>.+?)\s*$", re.M)

# The four states, in the order a legend should list them, with the palette
# token each is drawn in.
STATES = [
    ("done", "ok", "Built, tested, documented, in main"),
    ("next", "accent", "Started or specified in detail, being worked on now"),
    ("planned", "warn", "Specified, not started"),
    ("blocked", "err", "Cannot proceed until something outside the code changes"),
]

# Sections of the roadmap that are a list of markers. Anything else in the file
# is prose and is linked to rather than redrawn.
SKIP_SECTIONS = {"Legend"}


def read(path):
    with io.open(path, encoding="utf-8") as handle:
        return handle.read()


def markers(text):
    """Every marker in the roadmap, as (section, number, marker, status, estimate).

    Walked in file order, so the picture reads in the same order as the
    document, and a section added to `ROADMAP.md` appears here without anybody
    editing this file.
    """
    sections = [(m.start(), m.group("title")) for m in HEADING.finditer(text)]

    def section_of(position):
        title = "Markers"
        for start, name in sections:
            if start < position:
                title = name
            else:
                break
        return title

    # A line that looks like a marker row and does not parse is not skipped.
    #
    # `63b` was such a row. It sat in a table between 63 and the next section,
    # written exactly like its neighbours, carrying a status like its
    # neighbours, and `ROW` requires a plain integer, so it matched nothing and
    # was dropped without a word. It never appeared on the website, never
    # appeared in the picture, and was in no count of anything, for as long as
    # it existed.
    #
    # A parser that silently ignores what it cannot read turns a typo into an
    # invisible item, which is the worst of both: the document says the work is
    # tracked and nothing tracks it. So anything shaped like a row and not
    # matched is a failure here, loudly, rather than a gap nobody sees.
    looks_like_a_row = re.compile(r"^\|\s*[^|\s]+\s*\|.*\|\s*\*\*\w+\*\*\s*\|", re.M)
    parsed_at = {m.start() for m in ROW.finditer(text)}
    for candidate in looks_like_a_row.finditer(text):
        if candidate.start() in parsed_at:
            continue
        if section_of(candidate.start()) in SKIP_SECTIONS:
            continue
        raise SystemExit(
            "a row in ROADMAP.md looks like a marker and does not parse:\n"
            "    %s\n"
            "  A row needs a plain integer, a marker, and a bold status of\n"
            "  done, next, planned or blocked. Fix the row: a row this cannot\n"
            "  read is a row that appears nowhere."
            % candidate.group(0).strip()[:120])

    out = []
    for match in ROW.finditer(text):
        title = section_of(match.start())
        if title in SKIP_SECTIONS:
            continue
        estimate = (match.group("estimate") or "").strip()
        if estimate in ("—", "-", "--"):
            estimate = ""
        out.append({
            "section": title,
            "number": int(match.group("number")),
            "marker": match.group("marker"),
            "status": match.group("status"),
            "estimate": estimate,
        })
    return out


def split_marker(marker):
    """A marker's bold title, and the rest of it.

    Every row in `ROADMAP.md` is written as `**A short name**: what that
    actually means`, and the page used to print the whole string as one line.
    In a list of a hundred that reads as a wall: the name and the explanation
    have the same weight, so neither is scannable and the explanation is not
    reachable except by reading every word of it.

    Split here rather than in the template, because a handful of the oldest
    rows have no bold title at all and the caller should not have to know
    which. Those come back with no title and their whole text as the detail,
    which renders as it always did.
    """
    match = re.match(r"^\*\*(?P<title>.+?)\*\*\s*[:.]?\s*(?P<detail>.*)$", marker,
                     re.S)
    if not match:
        return "", marker
    return match.group("title"), match.group("detail").strip()


def anchor(title):
    """A stable `#id` for a section heading.

    The same shape GitHub gives a heading, so a link written against the
    document works against the page: lowercased, spaces to hyphens, everything
    else dropped.
    """
    slug = re.sub(r"[^a-z0-9\s-]", "", title.lower())
    return re.sub(r"\s+", "-", slug.strip())


def prose_for(text, sections):
    """The paragraphs a section opens with, before its table.

    This is where the reasoning behind a group of markers is written, and the
    page threw all of it away: it kept the rows and dropped the sentences that
    say why the rows exist. A reader of the page saw a list; a reader of the
    document saw an argument.
    """
    out = {}
    for index, (start, title) in enumerate(sections):
        end = sections[index + 1][0] if index + 1 < len(sections) else len(text)
        chunk = text[start:end]
        # Everything between the heading and the first table row or the first
        # horizontal rule, whichever comes first.
        body_text = chunk.split("\n", 1)[1] if "\n" in chunk else ""
        lines = []
        for line in body_text.split("\n"):
            if line.startswith("|") or line.startswith("---"):
                break
            lines.append(line)
        paragraphs = [p.strip() for p in "\n".join(lines).split("\n\n") if p.strip()]
        out[title] = paragraphs
    return out


def plain(markup):
    """A marker's text without its Markdown, for a tooltip.

    Deliberately small: bold, code and links, which is everything the roadmap's
    marker column actually uses. Anything else is left as it is rather than
    half-converted.
    """
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", markup)
    text = text.replace("**", "").replace("`", "")
    return re.sub(r"\s+", " ", text).strip()


# --- the picture -------------------------------------------------------------

SQUARE = 22.0
GAP = 6.0
LABEL_H = 30.0
BLOCK_GAP = 18.0
MARGIN = 24.0
WIDTH = 640.0


def graphic(colours, groups, counts):
    """Every marker as a square, grouped by the roadmap's own sections."""
    per_row = int((WIDTH - MARGIN * 2 + GAP) // (SQUARE + GAP))

    # Height first, so the canvas is the size of what goes in it rather than a
    # number that has to be kept in step by hand.
    y = MARGIN + 34.0
    plan = []
    for title, rows in groups:
        lines = (len(rows) + per_row - 1) // per_row
        plan.append((title, rows, y))
        y += LABEL_H + lines * (SQUARE + GAP) + BLOCK_GAP
    legend_y = y + 4.0
    height = legend_y + 2 * (SQUARE - 2) + 22.0 + MARGIN

    out = []
    add = out.append
    add('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %.0f %.0f" '
        'width="%.0f" height="%.0f" style="max-width:100%%;height:auto" '
        'role="img" aria-label="every roadmap item, coloured by state">'
        % (WIDTH, height, WIDTH, height))
    add("<!-- %s from ROADMAP.md. Do not edit. -->" % MARKER)
    # The reveal, and the hover, written into the drawing.
    #
    # In the drawing rather than in `main.css` because this file is also
    # written to `assets/roadmap.svg` and opened on its own, where no
    # stylesheet of ours is loaded. A picture that animates in one place and
    # not the other is the sort of difference nobody notices until it looks
    # broken.
    #
    # `transform-box: fill-box` is what makes `transform-origin: center` mean
    # the square's own centre rather than the origin of the whole drawing.
    # Without it every square flies in from the top-left corner.
    add('<style>'
        '.rm-square{transform-box:fill-box;transform-origin:center;'
        'animation:rm-in .45s cubic-bezier(.2,.8,.3,1) both;'
        'transition:filter .15s ease}'
        '.rm-square:hover{filter:brightness(1.35)}'
        '@keyframes rm-in{from{opacity:0;transform:scale(.4)}'
        'to{opacity:1;transform:none}}'
        # Somebody who has asked their system for less movement gets the
        # finished picture, immediately, rather than a faster version of the
        # same animation.
        '@media (prefers-reduced-motion:reduce){'
        '.rm-square{animation:none}}'
        '</style>')
    add('<rect x="0" y="0" width="%.0f" height="%.0f" rx="10" '
        'fill="var(--bg-inset, %s)"/>' % (WIDTH, height, colours["bg-inset"]))

    total = sum(counts.values())
    add('<text x="%.1f" y="%.1f" font-family="%s" font-size="14" '
        'fill="var(--fg, %s)">%d items</text>'
        % (MARGIN, MARGIN + 14, docs.MONO, colours["fg"], total))
    add('<text x="%.1f" y="%.1f" font-family="%s" font-size="12" '
        'fill="var(--muted, %s)" text-anchor="end">%s</text>'
        % (WIDTH - MARGIN, MARGIN + 14, docs.MONO, colours["muted"],
           docs.esc(", ".join("%d %s" % (counts.get(name, 0), name)
                              for name, _, _ in STATES if counts.get(name)))))

    token = {name: colour for name, colour, _ in STATES}
    for title, rows, top in plan:
        add('<text x="%.1f" y="%.1f" font-family="%s" font-size="12" '
            'fill="var(--muted, %s)">%s</text>'
            % (MARGIN, top + 16, docs.MONO, colours["muted"], docs.esc(title)))
        for index, row in enumerate(rows):
            column = index % per_row
            line = index // per_row
            x = MARGIN + column * (SQUARE + GAP)
            square_y = top + LABEL_H + line * (SQUARE + GAP)
            colour = token[row["status"]]
            # No number drawn in the square.
            #
            # It used to carry one, and a grid of ninety-six numbered squares
            # tells a reader nothing: the number is an index into a document
            # they are not in, and the one thing they want -- what this square
            # is -- was the thing it did not say. The name is in the `<title>`,
            # which every browser shows on hover and which a screen reader
            # reads, and it is now the only thing the square carries.
            #
            # The status opacity moves to the group so the square's own
            # opacity is free for the reveal below.
            add('<g opacity="%s"><title>%s (%s)</title>'
                '<rect class="rm-square" style="animation-delay:%dms" '
                'x="%.1f" y="%.1f" width="%.1f" height="%.1f" rx="4" '
                'fill="var(--%s, %s)"/></g>'
                % ("1" if row["status"] == "done" else "0.85",
                   docs.esc(plain(row["marker"])[:90]), row["status"],
                   # Staggered along each row, and capped: ninety-six squares
                   # at 12 ms each would take a second and a quarter to
                   # finish, which is a page that looks slow rather than one
                   # that looks alive.
                   min(index * 12, 600),
                   x, square_y, SQUARE, SQUARE, colour, colours[colour]))

    # The legend, two to a row, so a narrow screen does not scale the picture
    # down to fit one long line of it.
    for index, (name, colour, note) in enumerate(STATES):
        column = index % 2
        line = index // 2
        x = MARGIN + column * ((WIDTH - MARGIN * 2) / 2)
        y = legend_y + line * (SQUARE - 2)
        add('<rect x="%.1f" y="%.1f" width="12" height="12" rx="3" '
            'fill="var(--%s, %s)"/>' % (x, y, colour, colours[colour]))
        add('<text x="%.1f" y="%.1f" font-family="%s" font-size="11" '
            'fill="var(--muted, %s)">%s</text>'
            % (x + 18, y + 10, docs.MONO, colours["muted"],
               docs.esc("%s: %d" % (name, counts.get(name, 0)))))
    add("</svg>")
    return "\n".join(out) + "\n"


# --- the film ----------------------------------------------------------------

FILM_W = 640.0
FILM_H = 360.0
FILM_PAD = 20.0
FILM_ROW = 17.0
FILM_TOP = 46.0
# How fast the list moves, and how long it waits at the end before repeating.
FILM_SPEED = 42.0
FILM_PAUSE = 4.0


def film(colours, done):
    """Everything that is finished, scrolling, with a countdown before it repeats.

    # Why this is an animation and not an MP4

    A video was asked for, and a video is the right shape for this: something
    somebody watches rather than a picture with a long dead pause in it. What
    it is not is a reason to put an H.264 file in this repository.

    This project ships no codec and does not bundle `ffmpeg`, and `ROADMAP.md`
    already settled what that means for video: render here, and *always write a
    self-contained animation that needs nothing else installed*. An encoded
    file would also be a committed binary whose bytes depend on which build of
    which encoder made it, so it could not be regenerated and compared the way
    every other picture in this repository is.

    So it is an SVG that animates itself. It plays in any browser with no
    plugin, no codec and no download, it is a few kilobytes rather than a few
    megabytes, it takes the reader's colour scheme, and it is generated from
    `ROADMAP.md`, so it cannot show a marker as finished that is not.
    `docs/PACKAGING.md` is not the place for it; the command to turn it into an
    actual file, for anybody who wants one, is under the picture on the page.

    # The countdown

    A loop with no warning restarts under the reader while they are still
    reading the last line. The ring in the corner fills during the pause, so
    the restart is something you can see coming rather than something that
    happens to you. Four seconds: long enough to finish a line, short enough
    that nobody is waiting.
    """
    rows = []
    y = 0.0
    columns = int((FILM_W - FILM_PAD * 2 - 34.0) / (12.0 * docs.TEXT_RATIO))
    for row in done:
        lines = wrap(plain(row["marker"]), columns)
        rows.append((row["number"], lines, y))
        y += len(lines) * FILM_ROW + 7.0
    content = y

    view_h = FILM_H - FILM_TOP - FILM_PAD
    distance = max(0.0, content - view_h)
    scroll = distance / FILM_SPEED if distance else 1.0
    total = scroll + FILM_PAUSE
    turn = (scroll / total) * 100.0

    ring_r = 9.0
    circumference = 2 * 3.14159265 * ring_r

    out = []
    add = out.append
    add('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %.0f %.0f" '
        'width="%.0f" height="%.0f" style="max-width:100%%;height:auto" '
        'role="img" aria-label="everything finished, scrolling">'
        % (FILM_W, FILM_H, FILM_W, FILM_H))
    add("<!-- %s from ROADMAP.md. Do not edit. -->" % MARKER)
    add("<style>")
    add("  .film-list { animation: film-scroll %.2fs linear infinite; }" % total)
    add("  .film-ring { animation: film-count %.2fs linear infinite; }" % total)
    add("  @keyframes film-scroll {")
    add("    0%% { transform: translateY(0); }")
    add("    %.2f%%, 100%% { transform: translateY(-%.1fpx); }" % (turn, distance))
    add("  }")
    add("  @keyframes film-count {")
    add("    0%%, %.2f%% { opacity: 0; stroke-dashoffset: %.2f; }" % (turn, circumference))
    add("    %.2f%% { opacity: 1; stroke-dashoffset: %.2f; }" % (turn + 0.01, circumference))
    add("    100%% { opacity: 1; stroke-dashoffset: 0; }")
    add("  }")
    # Somebody who asked their system for less movement gets the list at the
    # top and no countdown, rather than a picture that never settles.
    add("  @media (prefers-reduced-motion: reduce) {")
    add("    .film-list, .film-ring { animation: none; }")
    add("    .film-ring { opacity: 0; }")
    add("  }")
    add("</style>")
    add('<defs><clipPath id="film-view"><rect x="0" y="%.1f" width="%.0f" '
        'height="%.1f"/></clipPath></defs>' % (FILM_TOP, FILM_W, view_h))
    add('<rect x="0" y="0" width="%.0f" height="%.0f" rx="10" '
        'fill="var(--bg-inset, %s)"/>' % (FILM_W, FILM_H, colours["bg-inset"]))
    add('<text x="%.1f" y="26" font-family="%s" font-size="13" '
        'fill="var(--fg, %s)">%d items finished</text>'
        % (FILM_PAD, docs.MONO, colours["fg"], len(done)))
    add('<line x1="0" y1="%.1f" x2="%.0f" y2="%.1f" stroke="var(--border, %s)"/>'
        % (FILM_TOP - 8, FILM_W, FILM_TOP - 8, colours["border"]))

    add('<g clip-path="url(#film-view)">')
    add('<g class="film-list">')
    for number, lines, top in rows:
        base = FILM_TOP + 12.0 + top
        add('<rect x="%.1f" y="%.1f" width="20" height="12" rx="3" '
            'fill="var(--ok, %s)"/>' % (FILM_PAD, base - 9.5, colours["ok"]))
        add('<text x="%.1f" y="%.1f" font-family="%s" font-size="9" '
            'fill="var(--bg-inset, %s)" text-anchor="middle">%d</text>'
            % (FILM_PAD + 10, base, docs.MONO, colours["bg-inset"], number))
        for index, line in enumerate(lines):
            add('<text x="%.1f" y="%.1f" font-family="%s" font-size="12" '
                'fill="var(--%s, %s)">%s</text>'
                % (FILM_PAD + 28, base + index * FILM_ROW, docs.MONO,
                   "fg" if index == 0 else "muted",
                   colours["fg"] if index == 0 else colours["muted"],
                   docs.esc(line)))
    add("</g>")
    add("</g>")

    # The countdown, over the top right, outside the clip so it never scrolls.
    add('<g class="film-ring" opacity="0">')
    add('<circle cx="%.1f" cy="24" r="%.1f" fill="none" '
        'stroke="var(--border, %s)" stroke-width="3"/>'
        % (FILM_W - 26, ring_r, colours["border"]))
    add('<circle cx="%.1f" cy="24" r="%.1f" fill="none" '
        'stroke="var(--accent, %s)" stroke-width="3" stroke-linecap="round" '
        'stroke-dasharray="%.2f" stroke-dashoffset="%.2f" '
        'transform="rotate(-90 %.1f 24)"/>'
        % (FILM_W - 26, ring_r, colours["accent"], circumference, circumference,
           FILM_W - 26))
    add("</g>")
    add("</svg>")
    return "\n".join(out) + "\n"


def wrap(text, columns):
    """Prose as lines no wider than `columns`, broken on words."""
    out = []
    line = ""
    for word in text.split():
        candidate = word if not line else line + " " + word
        if len(candidate) > columns and line:
            out.append(line)
            line = word
        else:
            line = candidate
    if line:
        out.append(line)
    return out or [""]


# --- the page ----------------------------------------------------------------

def marker_html(title, detail):
    """A marker's name in bold and its explanation after it."""
    if not title:
        return docs.inline_html(detail)
    if not detail:
        return "<strong>%s</strong>" % docs.inline_html(title)
    return '<strong>%s</strong> <span class="marker-detail">%s</span>' % (
        docs.inline_html(title), docs.inline_html(detail))


def marker_item(row):
    """One list entry, addressable on its own.

    The number is the link. A roadmap item somebody wants to point at is the
    unit of conversation about this project, and until now the only way to send
    one was to send the whole page and say which paragraph.
    """
    title, detail = split_marker(row["marker"])
    return ('<li id="m%d"><a class="marker-link" href="#m%d" '
            'aria-label="link to item %d">%d</a> %s</li>'
            % (row["number"], row["number"], row["number"], row["number"],
               marker_html(title, detail)))


def body(colours, groups, counts, generated_at, prose):
    """The page under the picture: the same markers, as readable rows."""
    total = sum(counts.values())
    done = counts.get("done", 0)
    out = []
    add = out.append

    # No lede here: `split.page` has already written one from the description,
    # and two of them in a row is the shape of a page nobody proofread.
    add('<div class="diagram">')
    add(graphic(colours, groups, counts).rstrip("\n"))
    add("</div>")

    add('<p style="color:var(--muted);font-size:13px">%d of %d are '
        'built, tested, documented and in <code>main</code>. '
        '<strong>Area is not progress.</strong> Every square is the same size '
        'and one item is not one day: the first is the whole signal engine, '
        'and another is a page of questions. The estimates below are the '
        'closest thing to an answer, and they are estimates.</p>'
        % (done, total))

    add('<h2 id="film">Everything that is finished, in one go</h2>')
    add('<p>A little under half a minute. It scrolls what is done, waits four '
        'seconds with a countdown in the corner, and starts again.</p>')
    add('<div class="diagram">')
    add(film(colours, [row for _, rows in groups for row in rows
                       if row["status"] == "done"]).rstrip("\n"))
    add("</div>")
    add('<p style="color:var(--muted);font-size:13px">An animation rather than '
        'a video file, and that is a decision rather than a shortcut. This '
        'project ships no codec and does not bundle <code>ffmpeg</code>, and '
        'the rule it already follows for video is to render here and always '
        'produce something that needs nothing else installed. An encoded file '
        'would also be a committed binary whose bytes depend on which build of '
        'which encoder made it, so it could not be regenerated and compared '
        'the way every other picture here is. If you want a file, '
        '<code>ffmpeg -i roadmap-film.svg roadmap.mp4</code> will make you one '
        'from this.</p>')

    add('<h2 id="what-is-left">What is left, and roughly what it takes</h2>')
    add('<p>Working days, one person, no interruptions, so the calendar will be '
        'longer than the sum. In the order it is expected to be done.</p>')
    add('<table><thead><tr><th>#</th><th>Marker</th><th>State</th>'
        "<th>Estimate</th></tr></thead><tbody>")
    outstanding = [row for _, rows in groups for row in rows
                   if row["status"] in ("next", "planned")]
    for row in outstanding:
        title, detail = split_marker(row["marker"])
        add('<tr id="m%d"><td><a class="marker-link" href="#m%d" '
            'aria-label="link to item %d">%d</a></td><td>%s</td><td>%s</td>'
            "<td>%s</td></tr>"
            % (row["number"], row["number"], row["number"], row["number"],
               marker_html(title, detail), docs.esc(row["status"]),
               docs.esc(row["estimate"] or "not estimated")))
    add("</tbody></table>")

    # Written for the case where there are none, because there are none now
    # and a heading over an empty list reads as a page that failed to load.
    blocked = [r for _, rows in groups for r in rows if r["status"] == "blocked"]
    add('<h2 id="blocked">Blocked, and why that is not the same as late</h2>')
    if blocked:
        add('<p>These are waiting on a decision or on somebody else&#8217;s rules '
            'rather than on effort. Working harder does not move them, and '
            '<a href="https://github.com/%s/blob/%s/ROADMAP.md">the roadmap</a> '
            'says what each one is waiting for.</p>' % (docs.REPO, docs.REF))
        add('<ul class="markers">')
        for row in blocked:
            add(marker_item(row))
        add("</ul>")
    else:
        add('<p>Nothing is blocked. Five items were, some of them for months, '
            'each waiting on a decision rather than on effort, and they have '
            'been taken off rather than left to make the list look busy. '
            '<a href="https://github.com/%s/blob/%s/ROADMAP.md">The roadmap</a> '
            'says what each one was, what it was waiting for, and why the '
            'reasoning is kept even though the item is gone.</p>'
            % (docs.REPO, docs.REF))

    # Grouped by the section it is written under, with the paragraphs that
    # section opens with. One flat list of a hundred items answers "how much is
    # done" and nothing else; the sections are where the reasoning is, and
    # dropping them was dropping the argument and keeping the score.
    add('<h2 id="done">Everything that is finished</h2>')
    add('<p>In the order the roadmap lists it, under the heading it was asked '
        'for. Every item links to itself, so one can be sent to somebody on '
        'its own.</p>')
    for title, rows in groups:
        finished = [row for row in rows if row["status"] == "done"]
        if not finished:
            continue
        slug = anchor(title)
        add('<h3 id="%s">%s <a class="marker-link" href="#%s" '
            'aria-label="link to this section">#</a></h3>' % (slug, docs.esc(title), slug))
        for paragraph in prose.get(title, []):
            add("<p>%s</p>" % docs.inline_html(paragraph.replace("\n", " ")))
        add('<ul class="markers">')
        for row in finished:
            add(marker_item(row))
        add("</ul>")

    add('<p style="color:var(--muted);font-size:13px">Generated from '
        '<code>ROADMAP.md</code> at commit time by '
        '<code>tools/site/roadmap.py</code>. %s</p>' % docs.esc(generated_at))
    return out


def build(root):
    colours = docs.palette(root)
    text = read(os.path.join(root, "ROADMAP.md"))
    rows = markers(text)
    if not rows:
        raise SystemExit(
            "no markers were found in ROADMAP.md.\n"
            "  The tables are parsed by their shape: a number, a marker, a\n"
            "  bold status. If that shape changed, fix ROW in this file rather\n"
            "  than publishing an empty page.")

    groups = []
    for row in rows:
        if not groups or groups[-1][0] != row["section"]:
            groups.append((row["section"], []))
        groups[-1][1].append(row)

    counts = {}
    for row in rows:
        counts[row["status"]] = counts.get(row["status"], 0) + 1

    prose = prose_for(text, [(m.start(), m.group("title")) for m in HEADING.finditer(text)])
    note = ("%d items across %d sections." % (len(rows), len(groups)))
    drawing = graphic(colours, groups, counts)

    index_html = read(os.path.join(root, "website", "index.html"))
    parts = split.shell(index_html)
    page = split.page(
        root,
        parts,
        "roadmap",
        "Roadmap",
        "What is built, what is coming, and roughly when. Generated from ROADMAP.md.",
        "\n".join(body(colours, groups, counts, note, prose)),
        # This page is written for itself, so its `#anchor` links point at
        # its own headings rather than at sections of the front page.
        relink_body=False,
    )
    # `split.page` says the section is also on the front page, which is true of
    # a section and not of this. Replaced rather than parameterised, because
    # every other caller of that function wants the sentence it writes.
    page = page.replace(
        '<p style="color:var(--muted)">This section is also part of '
        '<a href="index.html">the front page</a>, where it sits in context '
        'with the rest.</p>',
        '<p style="color:var(--muted)">The same information as '
        '<a href="https://github.com/%s/blob/%s/ROADMAP.md">ROADMAP.md</a>, '
        'which is where it is written and where the reasoning behind each one '
        'lives.</p>' % (docs.REPO, docs.REF))
    page = page.replace("GENERATED by tools/site/split.py from website/index.html.",
                        "%s from ROADMAP.md." % MARKER)
    moving = film(colours, [row for row in rows if row["status"] == "done"])
    return {
        "assets/roadmap.svg": drawing,
        "website/assets/roadmap.svg": drawing,
        "assets/roadmap-film.svg": moving,
        "website/assets/roadmap-film.svg": moving,
        "website/roadmap.html": page,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true",
                        help="fail if the page or the picture is out of date")
    args = parser.parse_args()

    files = build(ROOT)
    if args.check:
        stale = []
        for rel, text in sorted(files.items()):
            path = os.path.join(ROOT, rel.replace("/", os.sep))
            if not os.path.exists(path) or read(path) != text:
                stale.append(rel)
        if stale:
            for rel in stale:
                print("  out of date: %s" % rel)
            print("\n  Run: python tools/site/roadmap.py")
            return 1
        print("the roadmap page and its picture match ROADMAP.md")
        return 0

    for rel, text in sorted(files.items()):
        path = os.path.join(ROOT, rel.replace("/", os.sep))
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        print("  wrote %s" % rel)
    return 0


if __name__ == "__main__":
    sys.exit(main())
