#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""The roadmap, as a page anybody can read and a picture of where it has got to.

    python tools/site/roadmap.py           # write the page and the graphic
    python tools/site/roadmap.py --check   # verify they are current

# Why this is generated

`ROADMAP.md` is the file that decides what is done. It is also a two thousand
line document in a repository, which is the wrong shape for the question people
actually ask, which is "is this finished, and if not, what is left".

So this reads that file and writes two things: a picture of every marker
coloured by its state, and a page that puts the picture at the top and the list
under it. Neither is typed. A marker whose status changes in `ROADMAP.md`
changes here on the next run, and `--check` fails the build if it has not, which
is the same arrangement the documentation, the artwork and the search index
already have. A published roadmap that quietly disagrees with the roadmap would
be worse than not publishing one.

# What the picture shows, and what it deliberately does not

One square per marker, in the order the roadmap lists them, grouped by the
section headings that file already has. Colour is state and nothing else:
done, next, planned, blocked.

**Area is not progress.** Every square is the same size, and a marker is not a
day: marker 1 is the entire signal engine and marker 68 is a page of questions.
Reading the coloured fraction as "how far along this is" would be wrong, and the
page says so under the picture rather than leaving somebody to work it out. The
estimates, which are the closest thing to an answer, are in the text where they
can carry the sentence that goes with them.

**Blocked is its own colour, not a shade of unfinished.** Four markers are
blocked on a decision or on somebody else's rules rather than on effort, and
showing them as "not done yet" would promise work that is not going to happen
by working harder.

# In plain words

The roadmap is a long file in the source code. This turns it into a page with a
picture at the top, so somebody can see at a glance what is built and what is
not, without reading two thousand lines or taking anybody's word for it.

The picture is drawn from that file every time, so it cannot say something the
roadmap does not.

Pure standard library.
"""

import argparse
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))

sys.path.insert(0, os.path.join(ROOT, "tools", "docs"))
import generate as docs  # noqa: E402  (the path has to be set first)

sys.path.insert(0, HERE)
import split  # noqa: E402  (same)

MARKER = "GENERATED by tools/site/roadmap.py"

# A row in one of the roadmap's tables: number, marker, status, and sometimes an
# estimate. The status is bold in the file, which is what `\*\*` is doing here.
ROW = re.compile(
    r"^\|\s*(?P<number>\d+)\s*\|\s*(?P<marker>.+?)\s*\|\s*"
    r"\*\*(?P<status>done|next|planned|blocked)\*\*\s*\|"
    r"(?:\s*(?P<estimate>[^|]*?)\s*\|)?\s*$",
    re.M,
)

HEADING = re.compile(r"^## (?P<title>.+?)\s*$", re.M)

# The four states, in the order a legend should list them, with the palette
# token each is drawn in.
STATES = [
    ("done", "ok", "Built, tested, documented, in main"),
    ("next", "accent", "Started or specified in detail, being worked on now"),
    ("planned", "warn", "Specified, not started"),
    ("blocked", "err", "Cannot proceed until something outside the code changes"),
]

# Sections of the roadmap that are a list of markers. Anything else in the file
# is prose and is linked to rather than redrawn.
SKIP_SECTIONS = {"Legend"}


def read(path):
    with io.open(path, encoding="utf-8") as handle:
        return handle.read()


def markers(text):
    """Every marker in the roadmap, as (section, number, marker, status, estimate).

    Walked in file order, so the picture reads in the same order as the
    document, and a section added to `ROADMAP.md` appears here without anybody
    editing this file.
    """
    sections = [(m.start(), m.group("title")) for m in HEADING.finditer(text)]

    def section_of(position):
        title = "Markers"
        for start, name in sections:
            if start < position:
                title = name
            else:
                break
        return title

    out = []
    for match in ROW.finditer(text):
        title = section_of(match.start())
        if title in SKIP_SECTIONS:
            continue
        estimate = (match.group("estimate") or "").strip()
        if estimate in ("—", "-", "--"):
            estimate = ""
        out.append({
            "section": title,
            "number": int(match.group("number")),
            "marker": match.group("marker"),
            "status": match.group("status"),
            "estimate": estimate,
        })
    return out


def plain(markup):
    """A marker's text without its Markdown, for a tooltip.

    Deliberately small: bold, code and links, which is everything the roadmap's
    marker column actually uses. Anything else is left as it is rather than
    half-converted.
    """
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", markup)
    text = text.replace("**", "").replace("`", "")
    return re.sub(r"\s+", " ", text).strip()


# --- the picture -------------------------------------------------------------

SQUARE = 22.0
GAP = 6.0
LABEL_H = 30.0
BLOCK_GAP = 18.0
MARGIN = 24.0
WIDTH = 640.0


def graphic(colours, groups, counts):
    """Every marker as a square, grouped by the roadmap's own sections."""
    per_row = int((WIDTH - MARGIN * 2 + GAP) // (SQUARE + GAP))

    # Height first, so the canvas is the size of what goes in it rather than a
    # number that has to be kept in step by hand.
    y = MARGIN + 34.0
    plan = []
    for title, rows in groups:
        lines = (len(rows) + per_row - 1) // per_row
        plan.append((title, rows, y))
        y += LABEL_H + lines * (SQUARE + GAP) + BLOCK_GAP
    legend_y = y + 4.0
    height = legend_y + 2 * (SQUARE - 2) + 22.0 + MARGIN

    out = []
    add = out.append
    add('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %.0f %.0f" '
        'width="%.0f" height="%.0f" style="max-width:100%%;height:auto" '
        'role="img" aria-label="every roadmap marker, coloured by state">'
        % (WIDTH, height, WIDTH, height))
    add("<!-- %s from ROADMAP.md. Do not edit. -->" % MARKER)
    add('<rect x="0" y="0" width="%.0f" height="%.0f" rx="10" '
        'fill="var(--bg-inset, %s)"/>' % (WIDTH, height, colours["bg-inset"]))

    total = sum(counts.values())
    add('<text x="%.1f" y="%.1f" font-family="%s" font-size="14" '
        'fill="var(--fg, %s)">%d markers</text>'
        % (MARGIN, MARGIN + 14, docs.MONO, colours["fg"], total))
    add('<text x="%.1f" y="%.1f" font-family="%s" font-size="12" '
        'fill="var(--muted, %s)" text-anchor="end">%s</text>'
        % (WIDTH - MARGIN, MARGIN + 14, docs.MONO, colours["muted"],
           docs.esc(", ".join("%d %s" % (counts.get(name, 0), name)
                              for name, _, _ in STATES if counts.get(name)))))

    token = {name: colour for name, colour, _ in STATES}
    for title, rows, top in plan:
        add('<text x="%.1f" y="%.1f" font-family="%s" font-size="12" '
            'fill="var(--muted, %s)">%s</text>'
            % (MARGIN, top + 16, docs.MONO, colours["muted"], docs.esc(title)))
        for index, row in enumerate(rows):
            column = index % per_row
            line = index // per_row
            x = MARGIN + column * (SQUARE + GAP)
            square_y = top + LABEL_H + line * (SQUARE + GAP)
            colour = token[row["status"]]
            add('<g><title>%s. %s (%s)</title>'
                '<rect x="%.1f" y="%.1f" width="%.1f" height="%.1f" rx="4" '
                'fill="var(--%s, %s)" opacity="%s"/>'
                '<text x="%.1f" y="%.1f" font-family="%s" font-size="9" '
                'fill="var(--bg-inset, %s)" text-anchor="middle">%d</text></g>'
                % (row["number"], docs.esc(plain(row["marker"])[:90]), row["status"],
                   x, square_y, SQUARE, SQUARE, colour, colours[colour],
                   "1" if row["status"] == "done" else "0.85",
                   x + SQUARE / 2, square_y + SQUARE / 2 + 3.2, docs.MONO,
                   colours["bg-inset"], row["number"]))

    # The legend, two to a row, so a narrow screen does not scale the picture
    # down to fit one long line of it.
    for index, (name, colour, note) in enumerate(STATES):
        column = index % 2
        line = index // 2
        x = MARGIN + column * ((WIDTH - MARGIN * 2) / 2)
        y = legend_y + line * (SQUARE - 2)
        add('<rect x="%.1f" y="%.1f" width="12" height="12" rx="3" '
            'fill="var(--%s, %s)"/>' % (x, y, colour, colours[colour]))
        add('<text x="%.1f" y="%.1f" font-family="%s" font-size="11" '
            'fill="var(--muted, %s)">%s</text>'
            % (x + 18, y + 10, docs.MONO, colours["muted"],
               docs.esc("%s: %d" % (name, counts.get(name, 0)))))
    add("</svg>")
    return "\n".join(out) + "\n"


# --- the page ----------------------------------------------------------------

def body(colours, groups, counts, generated_at):
    """The page under the picture: the same markers, as readable rows."""
    total = sum(counts.values())
    done = counts.get("done", 0)
    out = []
    add = out.append

    # No lede here: `split.page` has already written one from the description,
    # and two of them in a row is the shape of a page nobody proofread.
    add('<div class="diagram">')
    add(graphic(colours, groups, counts).rstrip("\n"))
    add("</div>")

    add('<p style="color:var(--muted);font-size:13px">%d of %d markers are '
        'built, tested, documented and in <code>main</code>. '
        '<strong>Area is not progress.</strong> Every square is the same size '
        'and a marker is not a day: marker 1 is the whole signal engine and '
        'marker 68 is a page of questions. The estimates below are the closest '
        'thing to an answer, and they are estimates.</p>' % (done, total))

    add('<h2 id="what-is-left">What is left, and roughly what it takes</h2>')
    add('<p>Working days, one person, no interruptions, so the calendar will be '
        'longer than the sum. In the order it is expected to be done.</p>')
    add('<table><thead><tr><th>#</th><th>Marker</th><th>State</th>'
        "<th>Estimate</th></tr></thead><tbody>")
    outstanding = [row for _, rows in groups for row in rows
                   if row["status"] in ("next", "planned")]
    for row in outstanding:
        add("<tr><td>%d</td><td>%s</td><td>%s</td><td>%s</td></tr>"
            % (row["number"], docs.inline_html(row["marker"]),
               docs.esc(row["status"]), docs.esc(row["estimate"] or "not estimated")))
    add("</tbody></table>")

    add('<h2 id="blocked">Blocked, and why that is not the same as late</h2>')
    add('<p>These are waiting on a decision or on somebody else&#8217;s rules '
        'rather than on effort. Working harder does not move them, and '
        '<a href="https://github.com/%s/blob/%s/ROADMAP.md">the roadmap</a> '
        'says what each one is waiting for.</p>' % (docs.REPO, docs.REF))
    add("<ul>")
    for row in [r for _, rows in groups for r in rows if r["status"] == "blocked"]:
        add("<li><strong>%d.</strong> %s</li>"
            % (row["number"], docs.inline_html(row["marker"])))
    add("</ul>")

    add('<h2 id="done">Everything that is finished</h2>')
    add("<ul>")
    for row in [r for _, rows in groups for r in rows if r["status"] == "done"]:
        add("<li><strong>%d.</strong> %s</li>"
            % (row["number"], docs.inline_html(row["marker"])))
    add("</ul>")

    add('<p style="color:var(--muted);font-size:13px">Generated from '
        '<code>ROADMAP.md</code> at commit time by '
        '<code>tools/site/roadmap.py</code>. %s</p>' % docs.esc(generated_at))
    return out


def build(root):
    colours = docs.palette(root)
    text = read(os.path.join(root, "ROADMAP.md"))
    rows = markers(text)
    if not rows:
        raise SystemExit(
            "no markers were found in ROADMAP.md.\n"
            "  The tables are parsed by their shape: a number, a marker, a\n"
            "  bold status. If that shape changed, fix ROW in this file rather\n"
            "  than publishing an empty page.")

    groups = []
    for row in rows:
        if not groups or groups[-1][0] != row["section"]:
            groups.append((row["section"], []))
        groups[-1][1].append(row)

    counts = {}
    for row in rows:
        counts[row["status"]] = counts.get(row["status"], 0) + 1

    note = ("%d markers across %d sections." % (len(rows), len(groups)))
    drawing = graphic(colours, groups, counts)

    index_html = read(os.path.join(root, "website", "index.html"))
    parts = split.shell(index_html)
    page = split.page(
        parts,
        "roadmap",
        "Roadmap",
        "What is built, what is coming, and roughly when. Generated from ROADMAP.md.",
        "\n".join(body(colours, groups, counts, note)),
    )
    # `split.page` says the section is also on the front page, which is true of
    # a section and not of this. Replaced rather than parameterised, because
    # every other caller of that function wants the sentence it writes.
    page = page.replace(
        '<p style="color:var(--muted)">This section is also part of '
        '<a href="index.html">the front page</a>, where it sits in context '
        'with the rest.</p>',
        '<p style="color:var(--muted)">The same information as '
        '<a href="https://github.com/%s/blob/%s/ROADMAP.md">ROADMAP.md</a>, '
        'which is where it is written and where the reasoning behind each '
        'marker lives.</p>' % (docs.REPO, docs.REF))
    page = page.replace("GENERATED by tools/site/split.py from website/index.html.",
                        "%s from ROADMAP.md." % MARKER)
    return {
        "assets/roadmap.svg": drawing,
        "website/assets/roadmap.svg": drawing,
        "website/roadmap.html": page,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true",
                        help="fail if the page or the picture is out of date")
    args = parser.parse_args()

    files = build(ROOT)
    if args.check:
        stale = []
        for rel, text in sorted(files.items()):
            path = os.path.join(ROOT, rel.replace("/", os.sep))
            if not os.path.exists(path) or read(path) != text:
                stale.append(rel)
        if stale:
            for rel in stale:
                print("  out of date: %s" % rel)
            print("\n  Run: python tools/site/roadmap.py")
            return 1
        print("the roadmap page and its picture match ROADMAP.md")
        return 0

    for rel, text in sorted(files.items()):
        path = os.path.join(ROOT, rel.replace("/", os.sep))
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        print("  wrote %s" % rel)
    return 0


if __name__ == "__main__":
    sys.exit(main())
