#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Every page says where it lives, and search engines are told they may read it.

    python tools/site/seo.py            # write robots.txt, the sitemap and
                                        # the head tags on every page
    python tools/site/seo.py --check    # fail if any of it is out of date

# Why this is generated rather than written

The Open Graph tags were typed into each page by hand, which produced three
things worth fixing. `og:image` was `assets/banner.png`, a **relative** URL,
and the crawlers that read these tags do not resolve relative URLs: every link
to this site, in every chat application and every social network, showed no
picture at all. There was no `og:url` and no canonical link, so a page reached
at two addresses is two pages as far as an index is concerned. And two pages,
`404.html` and `wiki.html`, had no tags of any kind.

So the tags are built from what the page already says. The title comes from its
`<title>`, the description from its `<meta name="description">`, and the
address from where the file is. None of it is a second copy of anything, and a
page cannot be added without them.

# What is told to a crawler

`robots.txt` allows everything and names the sitemap. `sitemap.xml` lists every
page on the site, generated by walking it, so a page that is added is listed
and a page that is deleted stops being listed.

That is the whole of what a site can do from its own side. It asks to be read;
it cannot ask to be ranked. What decides whether a search for "veilvoice"
reaches this site is whether anything else links to it, which is not something
a file in this repository can arrange.
"""

import html
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SITE = os.path.join(ROOT, "website")

def read(path):
    with io.open(path, encoding="utf-8") as handle:
        return handle.read()


def repository():
    """The owner and name of this project, from the workspace manifest.

    `Cargo.toml` is where this project says where it lives, so the address of
    its website is worked out from that rather than typed here. A fork that
    changes the manifest gets its own addresses without editing this file.
    """
    manifest = read(os.path.join(ROOT, "Cargo.toml"))
    found = re.search(r'^repository\s*=\s*"https://github\.com/([^/"]+)/([^/"]+)"',
                      manifest, re.M)
    if not found:
        raise SystemExit(
            "Cargo.toml has no `repository = \"https://github.com/<owner>/<name>\"`, "
            "so the address of the website cannot be derived from it")
    return found.group(1), found.group(2)


# Where the site is published: GitHub Pages serves a project site at
# `https://<owner>.github.io/<repo>/`.
OWNER, NAME = repository()
BASE = "https://%s.github.io/%s/" % (OWNER, NAME)

# The picture a link to this site shows. It is the banner the front page draws
# in CSS, rendered by `assets/generate.py`, at 1280x640: GitHub's social card
# size exactly, and the 2:1 that Twitter's large-image card asks for.
PREVIEW = "assets/banner.png"
PREVIEW_W, PREVIEW_H = 1280, 640

SITE_NAME = "VeilVoice"

OPEN = "<!-- Written by tools/site/seo.py. Edit that, not this. -->"
CLOSE = "<!-- end of the generated addresses -->"

BLOCK = re.compile(re.escape(OPEN) + r".*?" + re.escape(CLOSE) + r"\n?", re.S)

# The tags this tool owns. Any of these left loose in a page is one it wrote
# before this existed, and is removed rather than left to contradict the block.
OWNED = re.compile(
    r'^[ \t]*<(?:meta\s+(?:property|name)="(?:og:[^"]*|twitter:[^"]*)"[^>]*'
    r'|link\s+rel="canonical"[^>]*)>[ \t]*\n',
    re.M,
)

TITLE = re.compile(r"<title>(.*?)</title>", re.S)
DESCRIPTION = re.compile(r'<meta name="description" content="([^"]*)">')


def write(path, text):
    with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def pages():
    """Every page of the site, as a path relative to `website/`, sorted.

    Walked rather than listed, so a page that is added is covered and a page
    that is deleted stops being claimed.
    """
    out = []
    for where, directories, files in os.walk(SITE):
        directories.sort()
        for name in sorted(files):
            if name.endswith(".html"):
                out.append(os.path.relpath(os.path.join(where, name), SITE).replace(os.sep, "/"))
    return sorted(out)


def address(relative):
    """The canonical URL of a page.

    `index.html` is the directory it is in: a server serves the same bytes for
    both, and telling an index they are two pages is how a site competes with
    itself.
    """
    if relative == "index.html":
        return BASE
    if relative.endswith("/index.html"):
        return BASE + relative[: -len("index.html")]
    return BASE + relative


def up_to_root(relative):
    """The `../` prefix that reaches `website/` from this page."""
    return "../" * relative.count("/")


def escape(text):
    """Text safe inside a `content="..."` attribute.

    The titles these are taken from are already HTML, so `&middot;` has to be
    read back to the character it stands for before being written out again.
    Escaping without that step produced `&amp;middot;`, which is what the
    no-JavaScript page's preview title said before this existed.
    """
    plain = html.unescape(text)
    return (plain.replace("&", "&amp;").replace("<", "&lt;")
                 .replace(">", "&gt;").replace('"', "&quot;"))


def tags(relative, title, description):
    """The block of addresses and preview tags for one page."""
    url = address(relative)
    image = BASE + PREVIEW
    kind = "website" if relative in ("index.html", "nojs/index.html") else "article"
    lines = [
        OPEN,
        '<link rel="canonical" href="%s">' % url,
        '<meta property="og:type" content="%s">' % kind,
        '<meta property="og:site_name" content="%s">' % SITE_NAME,
        '<meta property="og:url" content="%s">' % url,
        '<meta property="og:title" content="%s">' % escape(title),
        '<meta property="og:description" content="%s">' % escape(description),
        '<meta property="og:image" content="%s">' % image,
        '<meta property="og:image:width" content="%d">' % PREVIEW_W,
        '<meta property="og:image:height" content="%d">' % PREVIEW_H,
        '<meta property="og:image:alt" content="VeilVoice: irreversible voice '
        'de-identification">',
        '<meta name="twitter:card" content="summary_large_image">',
        '<meta name="twitter:title" content="%s">' % escape(title),
        '<meta name="twitter:description" content="%s">' % escape(description),
        '<meta name="twitter:image" content="%s">' % image,
        CLOSE,
    ]
    return "\n".join(lines) + "\n"


def head_of(relative, text):
    """The page with its address block current, or `None` if it has no head."""
    title = TITLE.search(text)
    description = DESCRIPTION.search(text)
    if not title or "</head>" not in text:
        return None

    block = tags(
        relative,
        " ".join(title.group(1).split()),
        description.group(1) if description else "",
    )

    text = BLOCK.sub("", text)
    text = OWNED.sub("", text)
    # Immediately before `</head>`, which every page has and no generator
    # writes anything after.
    return text.replace("</head>", block + "</head>", 1)


def finish(relative, text):
    """A page with its address block current.

    Every generator that writes a page calls this on its own output, so the
    tags are part of what the generator produces and its `--check` compares.
    A page with no `<head>` comes back untouched.
    """
    updated = head_of(relative, text)
    return text if updated is None else updated


def finished(files):
    """Every page in a generator's `{path: text}` with its address block current.

    The generators build a dictionary of what they are about to write and then
    either write it or compare it, so this is one call in each of them rather
    than one at every place a page is produced.
    """
    out = {}
    for relative, text in files.items():
        if relative.startswith("website/") and relative.endswith(".html"):
            out[relative] = finish(relative[len("website/"):], text)
        else:
            out[relative] = text
    return out


def robots():
    return (
        "# VeilVoice. Everything here is meant to be read.\n"
        "User-agent: *\n"
        "Allow: /\n"
        "\n"
        "Sitemap: %ssitemap.xml\n" % BASE
    )


def sitemap(relatives):
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    for relative in relatives:
        lines.append("  <url><loc>%s</loc></url>" % escape(address(relative)))
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def build():
    """Every file this tool owns, as {path relative to the repository: text}."""
    out = {}
    listed = []
    for relative in pages():
        path = os.path.join(SITE, relative)
        updated = head_of(relative, read(path))
        if updated is None:
            continue
        listed.append(relative)
        out["website/" + relative] = updated
    out["website/robots.txt"] = robots()
    out["website/sitemap.xml"] = sitemap(listed)
    return out


def main():
    check = "--check" in sys.argv
    files = build()

    problems = []
    for relative, text in sorted(files.items()):
        path = os.path.join(ROOT, relative)
        current = read(path) if os.path.exists(path) else None
        if current == text:
            continue
        if check:
            problems.append(relative)
        else:
            write(path, text)

    if problems:
        print("these are out of date; run tools/site/seo.py:")
        for relative in problems[:20]:
            print("  %s" % relative)
        if len(problems) > 20:
            print("  ... and %d more" % (len(problems) - 20))
        return 1

    pagecount = len(files) - 2
    if check:
        print("  %d pages, robots.txt and the sitemap all current" % pagecount)
    else:
        print("  wrote robots.txt, sitemap.xml and the addresses on %d pages" % pagecount)
    return 0


if __name__ == "__main__":
    sys.exit(main())
