#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""The whole GitHub wiki, as pages of this website.

    python tools/site/wiki_site.py           # write them
    python tools/site/wiki_site.py --check   # verify they are current

# What was wrong with what was here before

`website/wiki.html` was a hand-written page called "Wiki" that covered some of
the same ground as the real wiki in its own words. It was a second copy, and it
did what a second copy does: it told readers the desktop application had "five
tabs" for as long as it has had eleven. `docs/USER_GUIDE.md` said the same
thing once and that was written up as a defect; this said it on the website,
where more people read it, and nothing noticed for longer.

So the page is generated now, from the wiki, which is itself generated from the
documents. There is one source for each sentence and two renderings of it.

# What a reader gets

Every page of the wiki is on this site: the landing page at `wiki.html`, and
one page under `website/wiki/` for each document and guide. The reference, a
page per crate and per source file, was already here under
`website/reference/`, so those pages are linked rather than written again,
which is the only reason this does not publish four hundred pages where two
hundred would do.

`[[wiki links]]`, which mean nothing outside a wiki, are resolved to whichever
of those two places the page they name actually lives in. A link that names no
page at all stops the build: in a wiki a broken link renders as an invitation
to create the page, so nothing else would ever report it.

# Why the rendering is not done here

Markdown is rendered by `website/js/markdown.js`, through
`tools/site/render_markdown.js`, because that renderer already draws the README
on the front page and has been through two rounds of hostile-input auditing. A
third Markdown implementation in this repository would be a third set of rules
about what a table means and a third thing to audit. The pages therefore look
exactly like the same text does on the front page, which is the other half of
the argument.

Headings are given the same anchors GitHub gives them, from `tools/docs/
generate.py`'s `slug`, so a contents list written inside a document works
unchanged here.

# In plain words

Puts the whole wiki on the website, generated from the same text, so it can be
read without leaving the site and cannot say something the wiki does not.

Pure standard library, plus node for the renderer the site already ships.
"""

from __future__ import annotations

import argparse
import io
import json
import os
import re
import struct
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))

sys.path.insert(0, os.path.join(ROOT, "tools", "docs"))
import generate as docs  # noqa: E402  (the path has to be set first)
import wiki as wikigen  # noqa: E402  (same)

sys.path.insert(0, HERE)
import seo  # noqa: E402  the addresses and preview tags every page carries

MARKER = "GENERATED by tools/site/wiki_site.py"

# Where the generated pages go, under `website/`.
FOLDER = "wiki"

# The fragments `wiki.html` used to carry, and the page that covers each one
# now.
#
# These are addresses that have been published: `index.html` and `guide.html`
# both link to `wiki.html#applock`, and anything outside this repository that
# ever linked to one cannot be updated. A fragment cannot be redirected by a
# server, because browsers do not send it, so a reader following an old link
# would land at the top of a page with no explanation of why.
#
# Each one is therefore kept, as an anchor on the row of the landing page that
# now leads where it used to. The same argument, and the same answer, as
# `tools/site/split.py` gives for never removing a section from the front page.
LEGACY = {
    "start": "Doc-INSTALL",
    "app": "Guide-desktop-app",
    "cli": "Guide-command-line",
    "live": "Guide-desktop-app",
    "cable": "Doc-INSTALL",
    "record": "Guide-desktop-app",
    "transcribe": "Doc-FAQ",
    "encrypt": "Doc-USER-GUIDE",
    "applock": "Doc-USER-GUIDE",
    "destruct": "Doc-USER-GUIDE",
    "verify": "Guide-verifier",
    "how": "Doc-WHITEPAPER",
    "limits": "Doc-WHITEPAPER",
    "build": "Doc-REPRODUCIBLE-BUILDS",
    "library": "Doc-USING-THE-CRATES",
    "faq": "Doc-FAQ",
}

# A wiki link, in either form GitHub accepts. The same pattern
# `tools/docs/wiki.py` walks, and it is imported from there rather than written
# again for exactly the reason this whole tool exists.
WIKI_LINK = wikigen.WIKI_LINK

# A heading in rendered HTML, so an anchor can be put on it.
HEADING = re.compile(r"<h([2-6])>(.*?)</h\1>", re.S)
TAGS = re.compile(r"<[^>]+>")


def read(path):
    with io.open(path, encoding="utf-8") as handle:
        return handle.read()


def wiki_sources():
    """Every page of the wiki, by name, as it is written in the repository."""
    folder = os.path.join(ROOT, "wiki")
    pages = {}
    for name in sorted(os.listdir(folder)):
        if not name.endswith(".md"):
            continue
        pages[name[: -len(".md")]] = read(os.path.join(folder, name))
    if not pages:
        raise SystemExit(
            "wiki/ is empty, so there is nothing to publish.\n"
            "  Run: python tools/docs/generate.py && python tools/docs/wiki.py")
    return pages


def reference_pages():
    """Wiki page names that are already on this site, and where.

    Built by walking `website/reference/` rather than by taking a wiki page
    name apart, because taking it apart is guesswork: `File-veilvoice-gui-app`
    splits into a crate and a file in four places and only one of them is
    right. The tree knows, so the tree is asked.
    """
    out = {"Reference": "reference/index.html"}
    base = os.path.join(ROOT, "website", "reference")
    for entry in sorted(os.listdir(base)):
        full = os.path.join(base, entry)
        if entry.endswith(".html") and entry != "index.html":
            crate = entry[: -len(".html")]
            out[docs.wiki_crate_page(crate)] = "reference/%s" % entry
        elif os.path.isdir(full) and entry != "source":
            for page in sorted(os.listdir(full)):
                if not page.endswith(".html") or page.endswith(".src.html"):
                    continue
                stem = page[: -len(".html")]
                out[docs.wiki_file_page(entry, stem)] = "reference/%s/%s" % (entry, page)
    source = os.path.join(base, "source")
    if os.path.isdir(source):
        for page in sorted(os.listdir(source)):
            if not page.endswith(".html"):
                continue
            stem = page[: -len(".html")]
            name = "Source-%s" % stem
            out[name] = "reference/source/%s" % page
    return out


def our_pages(sources, already):
    """The wiki pages this tool has to render, because nothing else shows them."""
    return [name for name in sorted(sources)
            if name not in already and name not in ("Home", "_Sidebar")]


def destination(name, already, ours):
    """Where a wiki page lives on this site, from the website's root."""
    if name == "Home":
        return "wiki.html"
    if name in already:
        return already[name]
    if name in ours:
        return "%s/%s.html" % (FOLDER, name)
    return None


def resolve_links(text, page, already, ours):
    """Turn every `[[wiki link]]` into a link to wherever that page is here.

    A link inside a code span is left alone, which is the rule
    `tools/docs/wiki.py` already applies for the same reason: the roadmap's own
    description of the wiki-link guard contains one in backticks, and it is
    being quoted rather than followed.
    """
    spans = wikigen.quoted_spans(text)
    up = "" if page in ("Home",) else "../"
    missing = []

    def one(found):
        start, end = found.span()
        if any(a <= start and end <= b for a, b in spans):
            return found.group(0)
        label = found.group(1)
        target = found.group(2) or found.group(1)
        where = destination(target, already, ours)
        if where is None:
            missing.append(target)
            return found.group(0)
        return "[%s](%s%s)" % (label, up, where)

    out = WIKI_LINK.sub(one, text)
    if missing:
        raise SystemExit(
            "wiki/%s.md links to %s, which is not a page of the wiki and has\n"
            "  no page on this site either. A wiki renders a link like that as\n"
            "  an invitation to create the page, so nothing but this would\n"
            "  report it." % (page, ", ".join(sorted(set(missing)))))
    return out


def render(pages):
    """Markdown to HTML, through the renderer the website already ships."""
    driver = os.path.join(HERE, "render_markdown.js")
    try:
        done = subprocess.run(
            ["node", driver],
            input=json.dumps(pages).encode("utf-8"),
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=ROOT)
    except OSError as error:
        raise SystemExit(
            "node is needed to render the wiki, because the renderer is the\n"
            "  one the website already uses: %s" % error)
    if done.returncode != 0:
        raise SystemExit("rendering the wiki failed:\n%s"
                         % done.stderr.decode("utf-8", "replace"))
    return json.loads(done.stdout.decode("utf-8"))


def anchored(html):
    """The same HTML with GitHub's own anchor on every heading.

    A document's contents list links to `#its-headings`, and those links are
    written for GitHub. Giving the headings the same anchors here is what makes
    a table of contents work on this site rather than sending every reader to
    the top of the page.
    """
    used = {}

    def one(found):
        level, inner = found.group(1), found.group(2)
        name = docs.slug(TAGS.sub("", inner))
        if not name:
            return found.group(0)
        seen = used.get(name, 0)
        used[name] = seen + 1
        if seen:
            name = "%s-%d" % (name, seen)
        return '<h%s id="%s">%s</h%s>' % (level, name, inner, level)

    return HEADING.sub(one, html)


# An image the wiki points at in the repository's raw content.
#
# The wiki has no other choice: a GitHub wiki is a separate repository and
# cannot reach a file in this one except by absolute URL. A page of this
# website can, and must -- the site loads nothing from a third party, and the
# suite fails a page that tries -- so every one of these is brought home.
RAW_IMAGE = re.compile(
    r'<img src="https://github\.com/[^"/]+/[^"/]+/raw/[^"/]+/(?P<path>[^"]+)"')

# The one `<img>` this rewrites, once it is local.
LOCAL_IMAGE = re.compile(r'<img src="(?P<src>[^"]+)"(?P<rest>[^>]*)>')


def picture_size(path):
    """The width and height of a picture, from the picture.

    PNG carries them in the header. SVG carries a `viewBox`, which is what the
    drawings here use: `width` on the root element is often a percentage or
    missing entirely, and the box is the shape either way.

    A picture whose size cannot be read gets no attributes rather than guessed
    ones, and the site suite then fails on it, which is the right order: an
    invented size moves the page exactly as a missing one does and nothing
    would report it.
    """
    if path.lower().endswith(".png"):
        with open(path, "rb") as handle:
            head = handle.read(33)
        if head[:8] != b"\x89PNG\r\n\x1a\n":
            return None
        width, height = struct.unpack(">II", head[16:24])
        return width, height
    if path.lower().endswith(".gif"):
        with open(path, "rb") as handle:
            head = handle.read(10)
        if head[:6] not in (b"GIF87a", b"GIF89a"):
            return None
        width, height = struct.unpack("<HH", head[6:10])
        return width, height
    if path.lower().endswith(".svg"):
        with io.open(path, encoding="utf-8") as handle:
            head = handle.read(4096)
        box = re.search(r'viewBox="[-\d.]+\s+[-\d.]+\s+([\d.]+)\s+([\d.]+)"', head)
        if box:
            return int(round(float(box.group(1)))), int(round(float(box.group(2))))
        pair = re.search(r'width="(\d+)"[^>]*height="(\d+)"', head)
        if pair:
            return int(pair.group(1)), int(pair.group(2))
    return None


def local_pictures(html, depth):
    """Point every picture at this site's own copy, and say how big it is.

    Two problems in one pass, because they are one problem: a picture served
    from github.com is a third party the page has told a reader it does not
    use, and a picture with no width and height moves everything under it when
    it finally loads. Both are checked by `tools/site-tests/images.test.js`.
    """
    up = "../" * depth
    missing = []

    def home(found):
        path = found.group("path")
        if not os.path.isfile(os.path.join(ROOT, "website", path)):
            missing.append(path)
            return found.group(0)
        return '<img src="%s%s"' % (up, path)

    html = RAW_IMAGE.sub(home, html)
    if missing:
        raise SystemExit(
            "the wiki shows %s, which the website does not carry a copy of.\n"
            "  A page here cannot load it from github.com, so either copy it\n"
            "  into website/ or stop the wiki pointing at it."
            % ", ".join(sorted(set(missing))))

    def sized(found):
        src, rest = found.group("src"), found.group("rest")
        if "width=" in rest:
            return found.group(0)
        if src.startswith("http"):
            return found.group(0)
        path = os.path.join(ROOT, "website", src[len(up):] if up else src)
        size = picture_size(path) if os.path.isfile(path) else None
        if not size:
            return found.group(0)
        return '<img src="%s"%s width="%d" height="%d">' % (src, rest.rstrip(), size[0], size[1])

    return LOCAL_IMAGE.sub(sized, html)


def title_of(name, html, source):
    """The page's own title: its first heading, or its name."""
    found = re.search(r"<h1>(.*?)</h1>", html, re.S)
    if found:
        return TAGS.sub("", found.group(1)).strip()
    return name.replace("-", " ")


def describe(name):
    """One sentence for the page's description, from the wiki's own tables."""
    for source, title, blurb in wikigen.DOCUMENTS:
        if wikigen.page_name(source) == name:
            return "%s. %s." % (title, blurb)
    for page, title, blurb in wikigen.GUIDES:
        if page == name:
            return "%s. %s." % (title, re.sub(r"`", "", blurb))
    return "%s, from the VeilVoice wiki." % name.replace("-", " ")


def contents(sidebar_html):
    """The wiki's own sidebar, as the contents column beside each page."""
    out = ['<nav class="toc" aria-label="Contents">']
    out.append(sidebar_html)
    out.append("</nav>")
    return out


def page_body(name, html, sidebar_html):
    """One wiki page: the sidebar, the text, and where the text comes from."""
    body = ['<div class="wiki-layout">']
    body.extend(contents(sidebar_html))
    body.append("<div>")
    body.append(html)
    body.append(
        '<p style="color:var(--muted);margin-top:40px">This page is also '
        '<a href="https://github.com/%s/wiki/%s" rel="noopener noreferrer">%s '
        'in the GitHub wiki</a>, and both are generated from the same document '
        'in the repository.</p>' % (docs.REPO, name, name))
    body.append("</div>")
    body.append("</div>")
    return body


def landing_body(html, sidebar_html, ours):
    """`wiki.html`: the wiki's own landing page, and the old addresses kept."""
    body = ['<div class="wiki-layout">']
    body.extend(contents(sidebar_html))
    body.append("<div>")
    # Every fragment this page has ever carried, so a published link still
    # lands on the row that leads where it used to. They are empty anchors
    # rather than headings because the headings here belong to the wiki's
    # landing page, which is generated and does not know about them.
    for fragment, page in sorted(LEGACY.items()):
        if page not in ours:
            raise SystemExit(
                "wiki.html used to carry #%s and this sends it to %s, which\n"
                "  is not a page. A published address landing nowhere is the\n"
                "  thing LEGACY exists to prevent." % (fragment, page))
        body.append('<a id="%s" href="%s/%s.html" class="moved"></a>'
                    % (fragment, FOLDER, page))
    body.append(html)
    body.append("</div>")
    body.append("</div>")
    return body


def outputs():
    """Every file this tool owns, as {path under the repository: text}."""
    sources = wiki_sources()
    already = reference_pages()
    ours = our_pages(sources, already)

    markdown = {}
    for name in ours + ["Home"]:
        markdown[name] = resolve_links(sources[name], name, already, ours)
    # The sidebar is drawn on every page, and the pages are at two depths: the
    # landing page at the website's root and everything else a directory down.
    # A link that is right from one is wrong from the other, so it is resolved
    # twice rather than once and hoped over. This was the whole of the first
    # run's broken links.
    markdown["_Sidebar"] = resolve_links(sources["_Sidebar"], "Home", already, ours)
    markdown["_Sidebar-inner"] = resolve_links(sources["_Sidebar"], "_Sidebar",
                                               already, ours)
    html = render(markdown)

    fingerprint = read(os.path.join(ROOT, "website", "assets",
                                    "fingerprint.txt")).strip()

    files = {}
    for name in ours:
        page = local_pictures(anchored(html[name]), 1)
        files["website/%s/%s.html" % (FOLDER, name)] = docs.html_page(
            docs.palette(ROOT), 1, title_of(name, page, sources[name]),
            describe(name), page_body(name, page, html["_Sidebar-inner"]),
            fingerprint)
    files["website/wiki.html"] = docs.html_page(
        docs.palette(ROOT), 0, "VeilVoice &middot; wiki",
        "The whole VeilVoice wiki: what it is, how to install it, how to check "
        "a download, and how it is built.",
        landing_body(local_pictures(anchored(html["Home"]), 0),
                     html["_Sidebar"], ours), fingerprint)
    # The canonical address and the preview tags, the same way every other
    # generator gets them: written into what this is about to write, rather
    # than added to the file afterwards by a tool whose output this would then
    # disagree with on the next `--check`.
    return seo.finished(files)


def existing():
    """Every page this tool has written before, so removals are noticed."""
    found = []
    folder = os.path.join(ROOT, "website", FOLDER)
    if os.path.isdir(folder):
        for name in sorted(os.listdir(folder)):
            if name.endswith(".html"):
                found.append("website/%s/%s" % (FOLDER, name))
    return found


def write():
    files = outputs()
    for relative, text in sorted(files.items()):
        path = os.path.join(ROOT, relative)
        folder = os.path.dirname(path)
        if not os.path.isdir(folder):
            os.makedirs(folder)
        with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
    # A tool that only ever adds is correct about the present and permanent
    # about the past: F-195, in the generator next door, found 218 pages for
    # crates that no longer existed. A wiki page that is renamed leaves one
    # here, so they go in the same pass.
    removed = 0
    for relative in existing():
        if relative not in files:
            os.remove(os.path.join(ROOT, relative))
            removed += 1
    print("  wrote %d wiki page(s) into the website%s"
          % (len(files), ", and removed %d no longer produced" % removed
             if removed else ""))
    return 0


def check():
    files = outputs()
    problems = []
    for relative, text in sorted(files.items()):
        path = os.path.join(ROOT, relative)
        if not os.path.exists(path):
            problems.append("%s is missing" % relative)
        elif read(path) != text:
            problems.append("%s is not what the wiki says" % relative)
    for relative in existing():
        if relative not in files:
            problems.append("%s is no longer produced and is still here" % relative)
    if problems:
        print("the website's copy of the wiki is out of date:")
        for problem in problems:
            print("  %s" % problem)
        print("  Run: python tools/site/wiki_site.py")
        return 1
    print("  the website's wiki matches the wiki (%d pages)" % len(files))
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="verify the pages are current, write nothing")
    args = parser.parse_args()
    return check() if args.check else write()


if __name__ == "__main__":
    sys.exit(main())
