#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Numbers this project states about itself, measured rather than remembered.

Why this exists
---------------

The front page said "354 tests" and "no unsafe code, in any of the nine
crates" while the tree held 881 tests and nineteen crates. Both claims were
true when they were typed.

There *was* a guard. `tools/site-tests/css.test.js` compared the front page's
test count against ``docs/AUDIT.md`` and failed the build if they disagreed --
written after an earlier round of exactly this drift, with a comment saying
"this was the one place claims were hand-typed with nothing watching them".

It passed the whole time, because both numbers were hand-typed and both drifted
together. A check that compares one copy of a claim against another copy is a
check that agrees with itself, which is the failure this repository has now
recorded four separate times (F-61, F-63, and the audit's own note about the
banner).

So the numbers come from the tree. The test count is **measured by running the
tests**, because a static count of ``#[test]`` is not the same number -- it is
903 against a measured 881, since some tests sit behind features that are not
on by default. Counting the attribute would have produced a new wrong number
with a new reason.

What is generated
-----------------

``docs/MEASURED.md``, a small table. Nothing prose-like: it is data, and the
documents that make claims are checked against it rather than rewritten by it.
``docs/AUDIT.md`` is written by a person and stays that way; the site suite
fails the build when what it says disagrees with what is here.

Usage
-----

    python tools/measured/generate.py            # measure and write
    python tools/measured/generate.py --check    # measure and compare
"""

from __future__ import annotations

import io
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
OUTPUT = ROOT / "docs" / "MEASURED.md"

HEADER = """<!-- SPDX-License-Identifier: GPL-3.0-or-later -->
<!-- GENERATED by tools/measured/generate.py. Do not edit by hand. -->

# Measured

Numbers this project states about itself, taken from the tree rather than from
memory. Regenerated and checked by `tools/verify.py`; the documents and the
website that quote them are compared against this file, so a claim that drifts
fails the build instead of ageing quietly.

**The test count is a number about one machine.** Some tests are compiled only
on one operating system, so running the same tree on another gives a different
total: this tree measures 996 on Windows and 988 on Linux. The row below says
which machine produced the number in it, because a count with no platform
beside it reads as a fact about the tree and is a fact about a computer. See
F-77 in `docs/AUDIT.md`.

| What | Measured |
|---|---:|
"""


def workspace_crates() -> int:
    """How many crates the workspace actually contains."""
    manifest = (ROOT / "Cargo.toml").read_text(encoding="utf-8")
    members = re.search(r"members\s*=\s*\[(.*?)\]", manifest, re.S)
    if not members:
        raise SystemExit("Cargo.toml has no workspace members list")
    return len(re.findall(r'"([^"]+)"', members.group(1)))


def site_suites() -> int:
    """How many website suites the runner runs.

    Read out of ``run.js``'s own list rather than by globbing the directory. A
    suite file that exists and is not in the list does not run, and counting it
    would state a number nobody gets -- the same shape of mistake as counting
    ``#[test]`` instead of running the tests.
    """
    runner = (ROOT / "tools" / "site-tests" / "run.js").read_text(encoding="utf-8")
    block = re.search(r"const SUITES\s*=\s*\[(.*?)\]", runner, re.S)
    if not block:
        raise SystemExit("tools/site-tests/run.js has no SUITES list")
    return len(re.findall(r'require\("\./([^"]+\.test\.js)"\)', block.group(1)))


def measured_tests() -> int:
    """Run the suite and total what actually ran.

    Not a count of ``#[test]``. Those two numbers differ, and the one worth
    stating is the one a reader gets when they run `cargo test` themselves.
    """
    environment = dict(os.environ)
    environment.setdefault(
        "CARGO_TARGET_DIR",
        str(Path(os.environ.get("LOCALAPPDATA", ROOT)) / "veilvoice" / "target"),
    )
    finished = subprocess.run(
        ["cargo", "test", "--workspace"],
        cwd=ROOT,
        capture_output=True,
        env=environment,
    )
    # Decoded explicitly as UTF-8. `text=True` uses the console code page on
    # Windows, which turns every em dash into three wrong characters -- a
    # mistake this repository has already made once and has a suite to catch.
    output = finished.stdout.decode("utf-8", errors="replace")
    if finished.returncode != 0:
        stderr = finished.stderr.decode("utf-8", errors="replace")
        raise SystemExit(
            "the tests did not pass, so there is no number to record:\n"
            + (stderr or output)[-2000:]
        )
    totals = [int(n) for n in re.findall(r"^test result: ok\. (\d+) passed", output, re.M)]
    if not totals:
        raise SystemExit("no test results were found in cargo's output")
    return sum(totals)


def host_triple() -> str:
    """The target this machine builds for, as rustc names it.

    Recorded beside the test count because that count is a number about this
    machine rather than about the tree. `rustc -vV` prints it; a compiler that
    will not answer leaves the row saying so rather than guessing, because a
    guessed platform is worse than a missing one.
    """
    try:
        finished = subprocess.run(
            ["rustc", "-vV"], cwd=ROOT, capture_output=True, check=False)
    except OSError:
        return "unknown"
    text = finished.stdout.decode("utf-8", errors="replace")
    found = re.search(r"^host:\s*(\S+)$", text, re.M)
    return found.group(1) if found else "unknown"


def render() -> str:
    rows = [
        ("Tests, measured by running them", measured_tests()),
        ("Crates in the workspace", workspace_crates()),
        ("Website suites", site_suites()),
    ]
    body = "".join(f"| {name} | {value} |\n" for name, value in rows)
    body += f"| Measured on | `{host_triple()}` |\n"
    return HEADER + body


def main() -> int:
    check = "--check" in sys.argv
    fresh = render()
    if check:
        if not OUTPUT.is_file():
            print(f"{OUTPUT.relative_to(ROOT)} is missing", file=sys.stderr)
            return 1
        current = OUTPUT.read_text(encoding="utf-8")
        if current != fresh:
            print(
                f"{OUTPUT.relative_to(ROOT)} is out of date. Regenerate it with:\n"
                "    python tools/measured/generate.py",
                file=sys.stderr,
            )
            return 1
        print("measured numbers match the tree")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with io.open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(fresh)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
