#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Numbers this project states about itself, measured rather than remembered.

Why this exists
---------------

The front page said "354 tests" and "no unsafe code, in any of the nine
crates" while the tree held 881 tests and nineteen crates. Both claims were
true when they were typed.

There *was* a guard. `tools/site-tests/css.test.js` compared the front page's
test count against ``docs/AUDIT.md`` and failed the build if they disagreed --
written after an earlier round of exactly this drift, with a comment saying
"this was the one place claims were hand-typed with nothing watching them".

It passed the whole time, because both numbers were hand-typed and both drifted
together. A check that compares one copy of a claim against another copy is a
check that agrees with itself, which is the failure this repository has now
recorded four separate times (F-61, F-63, and the audit's own note about the
banner).

So the numbers come from the tree. The test count is **measured by running the
tests**, because a static count of ``#[test]`` is not the same number -- it is
903 against a measured 881, since some tests sit behind features that are not
on by default. Counting the attribute would have produced a new wrong number
with a new reason.

What is generated
-----------------

``docs/MEASURED.md``, a small table of the measurements themselves.

And, from it, the ten places in ``README.md``, ``website/index.html`` and
``docs/AUDIT.md`` that state one of those numbers in a sentence. Those used to
be typed, with ``tools/site-tests/css.test.js`` comparing each against this
file and failing the build on a disagreement. The comparison was right and it
stays. The typing was the defect: every change to any Rust file moves the
functional line count, so a commit that touched code and not those ten places
failed a check that had nothing to do with what the commit was for. It happened
four times in round thirty-three alone, which is the measurement that made this
worth doing. Roadmap item 152.

So the writer and the checker read the same anchors, and a claim can now drift
only if this tool is not run -- which ``tools/verify.py`` and CI both do.

``docs/AUDIT.md`` is otherwise written by a person and stays that way. The one
row touched here is the "Test suite" row of its state-of-the-tree table, which
is a description of now rather than a record of the past, and the regular
expression is anchored to that row so that no past number elsewhere in the
document is within reach of it.

Usage
-----

    python tools/measured/generate.py            # measure, write, and rewrite
                                                 # every claim from the result
    python tools/measured/generate.py --check    # measure and compare
"""

from __future__ import annotations

import io
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
OUTPUT = ROOT / "docs" / "MEASURED.md"

# The functional line count comes from the tool that counts it, imported rather
# than reimplemented, for the same reason the test count is measured rather than
# typed: a second implementation is a second answer.
sys.path.insert(0, str(ROOT / "tools" / "loc"))
import count as loc  # noqa: E402

HEADER = """<!-- SPDX-License-Identifier: GPL-3.0-or-later -->
<!-- GENERATED by tools/measured/generate.py. Do not edit by hand. -->

# Measured

Numbers this project states about itself, taken from the tree rather than from
memory. Regenerated and checked by `tools/verify.py`; the documents and the
website that quote them are compared against this file, so a claim that drifts
fails the build instead of ageing quietly.

**The test count is a number about one machine.** Some tests are compiled only
on one operating system, so running the same tree on another gives a different
total: this tree measures 996 on Windows and 988 on Linux. The row below says
which machine produced the number in it, because a count with no platform
beside it reads as a fact about the tree and is a fact about a computer. See
F-77 in `docs/AUDIT.md`.

**Functional lines are a different measure from the per-file line counts** in
the generated pages, the artwork and the reference links. A functional line is
a line holding code, so blank lines and lines holding only a comment are not
counted, and a line with code and a trailing comment counts once. The per-file
counts are the length of the file, blank lines and comments included, and are
left exactly as they are: this project is written with a high comment-to-code
ratio, so the two numbers are far apart, and quietly redefining one to match
the other would alter every page and link that carries it.

The line count covers **28 crates**, one more than the workspace row above:
`fuzz/` is a separate Cargo project at the root holding the fuzzing harnesses,
and it is Rust written and maintained here. `tools/docs/generate.py` documents
it beside the workspace members for the same reason.

| What | Measured |
|---|---:|
"""


def workspace_crates() -> int:
    """How many crates the workspace actually contains."""
    manifest = (ROOT / "Cargo.toml").read_text(encoding="utf-8")
    members = re.search(r"members\s*=\s*\[(.*?)\]", manifest, re.S)
    if not members:
        raise SystemExit("Cargo.toml has no workspace members list")
    return len(re.findall(r'"([^"]+)"', members.group(1)))


def site_suites() -> int:
    """How many website suites the runner runs.

    Read out of ``run.js``'s own list rather than by globbing the directory. A
    suite file that exists and is not in the list does not run, and counting it
    would state a number nobody gets -- the same shape of mistake as counting
    ``#[test]`` instead of running the tests.
    """
    runner = (ROOT / "tools" / "site-tests" / "run.js").read_text(encoding="utf-8")
    block = re.search(r"const SUITES\s*=\s*\[(.*?)\]", runner, re.S)
    if not block:
        raise SystemExit("tools/site-tests/run.js has no SUITES list")
    return len(re.findall(r'require\("\./([^"]+\.test\.js)"\)', block.group(1)))


def measured_tests() -> int:
    """Run the suite and total what actually ran.

    Not a count of ``#[test]``. Those two numbers differ, and the one worth
    stating is the one a reader gets when they run `cargo test` themselves.
    """
    environment = dict(os.environ)
    # On Windows the build goes under %LOCALAPPDATA%, away from a repository
    # that may sit in a synced folder or deep enough to meet the path limit.
    #
    # Everywhere else it goes where it always goes, which is the `target/` at
    # the root of this repository, and the way to ask for that is to say
    # nothing. The line this replaces named `ROOT` as the fallback and so built
    # into `<repo>/veilvoice/target` on every machine that is not Windows: a
    # second complete copy of the workspace build, inside the repository,
    # invisible to `git status` because `.gitignore` matches `target/` at any
    # depth, and never cleaned because nobody knew it was there. It was
    # fifteen gigabytes when it was found, and finding it took a mutation
    # campaign dying for want of disk. F-185.
    if os.name == "nt" and "LOCALAPPDATA" in os.environ:
        environment.setdefault(
            "CARGO_TARGET_DIR",
            str(Path(os.environ["LOCALAPPDATA"]) / "veilvoice" / "target"),
        )
    finished = subprocess.run(
        ["cargo", "test", "--workspace"],
        cwd=ROOT,
        capture_output=True,
        env=environment,
    )
    # Decoded explicitly as UTF-8. `text=True` uses the console code page on
    # Windows, which turns every em dash into three wrong characters -- a
    # mistake this repository has already made once and has a suite to catch.
    output = finished.stdout.decode("utf-8", errors="replace")
    if finished.returncode != 0:
        stderr = finished.stderr.decode("utf-8", errors="replace")
        raise SystemExit(
            "the tests did not pass, so there is no number to record:\n"
            + (stderr or output)[-2000:]
        )
    totals = [int(n) for n in re.findall(r"^test result: ok\. (\d+) passed", output, re.M)]
    if not totals:
        raise SystemExit("no test results were found in cargo's output")
    return sum(totals)


def audit_findings() -> tuple[int, int]:
    """How many findings the audit writes up, and the highest number it uses.

    A finding "exists" here when it has an entry of its own: a line beginning
    `### F-n`, or one beginning `**F-n` followed by a colon or a ` --`. Those
    are the three shapes this document has used for a finding heading over
    nineteen rounds. Anything else that names a finding is a mention, and
    `**F-73 had**: ...` is the one line that reads like a heading and is a
    sentence, so the separator is part of the pattern rather than optional. That distinction is the whole point of the measurement, because
    F-93 and F-94 were fixed in code, described in their commit, referred to by
    a later round, and never given an entry -- so every count taken by grepping
    for `F-\d+` said they were documented and none of them was.

    Two numbers rather than one. The count is what the verdict claims; the
    highest is the last number handed out. They agree only when no number has
    been skipped, so a reader comparing them can see a gap without reading the
    document, and the suite fails when one opens.
    """
    text = (ROOT / "docs" / "AUDIT.md").read_text(encoding="utf-8")
    entries = set()
    for line in text.split("\n"):
        found = re.match(r"^(?:### F-(\d+)\b|\*\*F-(\d+)(?::| --))", line)
        if found:
            entries.add(int(found.group(1) or found.group(2)))
    if not entries:
        raise SystemExit("docs/AUDIT.md has no finding entries; the pattern must have moved")
    return len(entries), max(entries)


def host_triple() -> str:
    """The target this machine builds for, as rustc names it.

    Recorded beside the test count because that count is a number about this
    machine rather than about the tree. `rustc -vV` prints it; a compiler that
    will not answer leaves the row saying so rather than guessing, because a
    guessed platform is worse than a missing one.
    """
    try:
        finished = subprocess.run(
            ["rustc", "-vV"], cwd=ROOT, capture_output=True, check=False)
    except OSError:
        return "unknown"
    text = finished.stdout.decode("utf-8", errors="replace")
    found = re.search(r"^host:\s*(\S+)$", text, re.M)
    return found.group(1) if found else "unknown"


# Every place one of the measured numbers is stated in a sentence, and the
# pattern that finds it. The first capture group is the number, and only that
# group is rewritten: the words around it belong to whoever wrote them.
#
# These are the same anchors `tools/site-tests/css.test.js` checks against
# `docs/MEASURED.md`, deliberately, so that the tool which writes a claim and
# the suite which checks it cannot disagree about where the claim is. If one of
# these patterns stops matching, the suite says so by name before this tool can
# quietly write nothing.
#
# The audit's three are anchored to the "Test suite" row. That document
# discusses past numbers, F-71's own write-up quotes "354 tests across 9
# crates", and a looser pattern reads the history instead of the claim; it did
# exactly that the first time the suite was written.
CLAIMS = [
    ("website/index.html", r"(\d+) tests, and \d+ more suites", "tests"),
    ("website/index.html", r"\d+ tests, and (\d+) more suites", "suites"),
    ("website/index.html", r"in any of the (\d+) crates", "crates"),
    ("docs/AUDIT.md", r"\| Test suite \| (\d+) tests across \d+ crates", "tests"),
    ("docs/AUDIT.md", r"\| Test suite \| \d+ tests across (\d+) crates", "crates"),
    ("docs/AUDIT.md", r"\| Test suite \|[^|]*?and (\d+) site-test suites", "suites"),
    ("README.md", r"\((\d+) tests across \d+\ncrates", "tests"),
    ("README.md", r"\(\d+ tests across (\d+)\ncrates", "crates"),
    ("README.md", r"and (\d+) website suites", "suites"),
    ("README.md", r"\*\*(\d+) functional lines of Rust\*\*", "lines"),
    # The defect count, in the two places that state it outside the audit. Its
    # measurement is `audit_findings`, which counts entries rather than
    # mentions, because F-93 and F-94 were fixed, described in their commits,
    # referred to by a later round, and never given an entry of their own: any
    # count taken by grepping for a finding number said they were documented.
    #
    # The audit's own verdict is not written from here and will not be. It is
    # the sentence the count is taken from, so writing it from the count would
    # be the tool agreeing with itself, which is the failure this file was
    # written after (F-61, F-63, F-71).
    ("README.md", r"\*\*(\d+) defects\*\*", "written_up"),
    ("website/index.html", r"(\d+) defects found and fixed across", "written_up"),
]


def claimed(measurements: dict, check: bool) -> list:
    """Write every claim from the measurements, or report the ones that drifted.

    One file is read, rewritten and written back per claim rather than all at
    once, because replacing a number changes every offset after it and a batch
    of spans taken from one read would land in the wrong places. Ten small
    passes over three files is not a cost worth optimising away.
    """
    problems = []
    for name, pattern, key in CLAIMS:
        path = ROOT / name
        text = path.read_text(encoding="utf-8")
        found = re.search(pattern, text)
        if not found:
            problems.append(
                f"{name}: nothing matches the pattern for the {key} count, "
                "so that claim is no longer being written or watched"
            )
            continue
        want = str(measurements[key])
        if found.group(1) == want:
            continue
        if check:
            problems.append(
                f"{name}: the {key} count says {found.group(1)}, "
                f"the tree measures {want}"
            )
            continue
        start, end = found.span(1)
        with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text[:start] + want + text[end:])
    return problems


def measure() -> dict:
    """Every number, taken once.

    Returned as a mapping rather than rendered straight into the table, because
    the same four values are also written into the sentences that state them and
    measuring twice would be two answers to one question.
    """
    written_up, highest = audit_findings()
    return {
        "tests": measured_tests(),
        "crates": workspace_crates(),
        "suites": site_suites(),
        "lines": sum(loc.per_crate().values()),
        "written_up": written_up,
        "highest": highest,
    }


def render(measurements: dict) -> str:
    rows = [
        ("Tests, measured by running them", measurements["tests"]),
        ("Crates in the workspace", measurements["crates"]),
        ("Website suites", measurements["suites"]),
        ("Functional lines of Rust", measurements["lines"]),
        ("Findings written up in the audit", measurements["written_up"]),
        ("Highest finding number used", measurements["highest"]),
    ]
    body = "".join(f"| {name} | {value} |\n" for name, value in rows)
    body += f"| Measured on | `{host_triple()}` |\n"
    return HEADER + body


def main() -> int:
    check = "--check" in sys.argv
    measurements = measure()
    fresh = render(measurements)

    if check:
        if not OUTPUT.is_file():
            print(f"{OUTPUT.relative_to(ROOT)} is missing", file=sys.stderr)
            return 1
        current = OUTPUT.read_text(encoding="utf-8")
        if current != fresh:
            print(
                f"{OUTPUT.relative_to(ROOT)} is out of date. Regenerate it with:\n"
                "    python tools/measured/generate.py",
                file=sys.stderr,
            )
            return 1
        problems = claimed(measurements, check=True)
        if problems:
            for problem in problems:
                print(problem, file=sys.stderr)
            print(
                "Regenerate them with:\n    python tools/measured/generate.py",
                file=sys.stderr,
            )
            return 1
        print("measured numbers match the tree")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with io.open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(fresh)
    problems = claimed(measurements, check=False)
    if problems:
        # Only a pattern that no longer matches reaches here when writing. That
        # is a claim nothing is writing and nothing is watching, which is the
        # state this tool exists to make impossible, so it fails rather than
        # reporting a successful write of nine out of ten.
        for problem in problems:
            print(problem, file=sys.stderr)
        return 1
    print(f"wrote {OUTPUT.relative_to(ROOT)}, and every claim taken from it")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
