// SPDX-License-Identifier: GPL-3.0-or-later
//! Embed the Windows application icon and version information.
//!
//! Without this, `veilvoice.exe` has no icon: Explorer draws the generic
//! executable glyph, the taskbar shows it, and the shortcut a user pins looks
//! like nothing in particular. The icon was being shipped *beside* the binary
//! as a loose `icon.ico`, which is a file nobody opens and Windows never reads.
//!
//! `assets/icon.ico` already carries all six sizes Windows asks for (16, 32,
//! 48, 64, 128 and 256), generated by `assets/generate.py` from the same pixels
//! as everything else, so this only has to point at it.
//!
//! # Why this fails the build rather than warning
//!
//! A missing icon is invisible to every test and obvious to every user. If the
//! resource compiler is not available, the honest outcome is a build that stops
//! and says so -- not a binary that ships looking unfinished while CI stays
//! green. That is the same reasoning as every other check in this repository.

fn main() {
    // Only Windows has a resource section to put this in. The `cfg` is on the
    // *target*, so a cross-compile to Windows from elsewhere still gets it.
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }

    println!("cargo:rerun-if-changed=../../assets/icon.ico");

    let mut resource = winresource::WindowsResource::new();
    resource.set_icon("../../assets/icon.ico");
    resource.set("ProductName", "VeilVoice");
    resource.set("FileDescription", "VeilVoice command line");
    resource.set("LegalCopyright", "tilas01 — GPL-3.0-or-later");
    resource.set("OriginalFilename", "veilvoice.exe");

    if let Err(error) = resource.compile() {
        panic!(
            "could not embed the Windows icon: {error}\n\
             The icon is part of what ships, so this stops the build rather \
             than producing an executable with no icon and a green CI run."
        );
    }
}
