// SPDX-License-Identifier: GPL-3.0-or-later
//! Linux: `/proc/modules`, cross-checked against `/sys/module`.
//!
//! # Two files, no subprocess
//!
//! The kernel publishes the loaded module list as a file, so this reads it.
//! Nothing is spawned, nothing needs privileges, and the whole operation costs
//! two directory reads, cheap enough to run on a timer without becoming the
//! reason the interface stopped painting.
//!
//! # The format
//!
//! ```text
//! nvidia 56807424 42 nvidia_uvm,nvidia_modeset, Live 0xffffffffc0e00000
//! ```
//!
//! Name, size in bytes, reference count, the modules that depend on it, the
//! state, and the load address. The address is **not** recorded: on most
//! systems `kptr_restrict` makes it read as zeros for an unprivileged reader,
//! and on the rest it changes at every boot, so recording it would make every
//! module look altered after a restart, which is a report nobody reads.
//!
//! # The cross-view check
//!
//! `/sys/module` has a directory per module, and the two lists should agree.
//! A name in one and not the other is worth reporting: unlinking from
//! `/proc/modules` and forgetting `/sys/module` is a mistake real rootkits have
//! made.
//!
//! It catches carelessness only. Both lists come from the same kernel, so
//! anything with the privilege to edit one has the privilege to edit both.
//!
//! One honest wrinkle: `/sys/module` also lists built-in modules and boot
//! parameters, which were never in `/proc/modules` and never will be. Those
//! have no `initstate` file, so only directories that have one are compared,
//! otherwise the check would produce dozens of discrepancies on every machine
//! and be switched off within a day.
//!
//! # In plain words
//!
//! Asks Linux which kernel modules are loaded, by reading two files the system
//! keeps.
//!
//! Nothing is run at all: the answer is already written down. Both files are read
//! and compared, because a module that appears in one and not the other is itself
//! worth reporting.

#[cfg(any(target_os = "linux", test))]
use crate::Module;

/// Parse the contents of `/proc/modules`.
///
/// Ungated so the parser is exercised by the test suite on every platform, not
/// only on the one that can produce the file. Real Linux output is checked in
/// below rather than being generated by the same assumptions the parser makes.
#[cfg(any(target_os = "linux", test))]
pub(crate) fn parse_proc_modules(text: &str) -> Vec<Module> {
    let mut modules = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let mut fields = line.split_whitespace();
        let Some(name) = fields.next() else { continue };
        let size = fields.next().unwrap_or("?");
        let refs = fields.next().unwrap_or("?");
        let used_by = fields.next().unwrap_or("-");
        let state = fields.next().unwrap_or("?");
        // The load address is the next field, and is deliberately dropped.
        let used_by = used_by.trim_end_matches(',');
        let detail = if used_by == "-" || used_by.is_empty() {
            format!("{size} bytes, {refs} refs, {state}")
        } else {
            format!("{size} bytes, {refs} refs, {state}, used by {used_by}")
        };
        modules.push(Module {
            name: name.to_string(),
            detail,
        });
    }
    modules
}

/// Read both views and compare them.
#[cfg(target_os = "linux")]
pub(crate) fn read() -> (Vec<Module>, Vec<String>, Vec<String>) {
    let mut problems = Vec::new();

    let modules = match std::fs::read_to_string("/proc/modules") {
        Ok(text) => parse_proc_modules(&text),
        Err(error) => {
            problems.push(format!("/proc/modules: {error}"));
            Vec::new()
        }
    };

    let (sys_names, sys_problem) = sys_module_names();
    if let Some(problem) = sys_problem {
        problems.push(problem);
        // With only one view there is nothing to cross-check, and reporting a
        // clean cross-check here would be reporting a check that did not run.
        return (modules, problems, Vec::new());
    }

    let proc_names: std::collections::BTreeSet<&str> =
        modules.iter().map(|module| module.name.as_str()).collect();
    let mut discrepancies = Vec::new();
    for name in &sys_names {
        if !proc_names.contains(name.as_str()) {
            discrepancies.push(format!("{name}: in /sys/module and not in /proc/modules"));
        }
    }
    for name in &proc_names {
        if !sys_names.contains(*name) {
            discrepancies.push(format!("{name}: in /proc/modules and not in /sys/module"));
        }
    }
    discrepancies.sort();
    (modules, problems, discrepancies)
}

/// The names under `/sys/module` that correspond to loadable modules.
///
/// Only directories with an `initstate` file. The rest are built-ins and boot
/// parameters, which are never in `/proc/modules`. Including them would report
/// dozens of discrepancies on an ordinary machine, and a check that cries wolf
/// every time is a check somebody turns off.
#[cfg(target_os = "linux")]
fn sys_module_names() -> (std::collections::BTreeSet<String>, Option<String>) {
    let mut names = std::collections::BTreeSet::new();
    let entries = match std::fs::read_dir("/sys/module") {
        Ok(entries) => entries,
        Err(error) => return (names, Some(format!("/sys/module: {error}"))),
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.join("initstate").exists() {
            continue;
        }
        names.insert(entry.file_name().to_string_lossy().into_owned());
    }
    (names, None)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Real `/proc/modules` output, kept verbatim. A parser tested only
    /// against strings written by the person who wrote the parser tests the
    /// assumptions twice and the format never.
    const SAMPLE: &str = "\
nvidia_uvm 1531904 0 - Live 0xffffffffc1200000 (POE)
nvidia_drm 77824 4 - Live 0xffffffffc11e0000 (POE)
nvidia 56807424 42 nvidia_uvm,nvidia_modeset, Live 0xffffffffc0e00000 (POE)
snd_hda_intel 57344 5 - Live 0xffffffffc0d20000
btrfs 1839104 1 - Live 0xffffffffc0000000
";

    #[test]
    fn every_line_becomes_a_module() {
        let modules = parse_proc_modules(SAMPLE);
        assert_eq!(modules.len(), 5);
        assert_eq!(modules[0].name, "nvidia_uvm");
        assert_eq!(modules[4].name, "btrfs");
    }

    #[test]
    fn size_reference_count_and_state_are_kept() {
        let modules = parse_proc_modules(SAMPLE);
        let nvidia = modules.iter().find(|m| m.name == "nvidia").unwrap();
        assert!(
            nvidia.detail.contains("56807424 bytes"),
            "{}",
            nvidia.detail
        );
        assert!(nvidia.detail.contains("42 refs"), "{}", nvidia.detail);
        assert!(nvidia.detail.contains("Live"), "{}", nvidia.detail);
    }

    #[test]
    fn dependants_are_kept_and_the_trailing_comma_is_not() {
        let modules = parse_proc_modules(SAMPLE);
        let nvidia = modules.iter().find(|m| m.name == "nvidia").unwrap();
        assert!(
            nvidia.detail.contains("used by nvidia_uvm,nvidia_modeset"),
            "{}",
            nvidia.detail
        );
        assert!(
            !nvidia.detail.contains("nvidia_modeset,,"),
            "the trailing comma must go: {}",
            nvidia.detail
        );
    }

    /// A dash means nothing depends on it, and must not be printed as though
    /// something called `-` did.
    #[test]
    fn a_module_nothing_depends_on_says_nothing_about_dependants() {
        let modules = parse_proc_modules(SAMPLE);
        let btrfs = modules.iter().find(|m| m.name == "btrfs").unwrap();
        assert!(!btrfs.detail.contains("used by"), "{}", btrfs.detail);
    }

    /// The load address is deliberately dropped: it is zeroed for an
    /// unprivileged reader, and changes at every boot on the machines where it
    /// is not. Recording it would make every module look altered after a
    /// restart.
    #[test]
    fn the_load_address_is_not_recorded() {
        for module in parse_proc_modules(SAMPLE) {
            assert!(
                !module.detail.contains("0xffffffff"),
                "the address leaked into {}: {}",
                module.name,
                module.detail
            );
        }
    }

    #[test]
    fn nothing_and_whitespace_produce_nothing() {
        assert!(parse_proc_modules("").is_empty());
        assert!(parse_proc_modules("\n\n   \n").is_empty());
    }

    /// A truncated line must produce a module rather than panicking: this
    /// parses a file the kernel writes while modules are loading and
    /// unloading, and a short read is a thing that happens.
    #[test]
    fn a_short_line_is_survived() {
        let modules = parse_proc_modules("halfwritten 4096\nfine 1 0 - Live 0x0\n");
        assert_eq!(modules.len(), 2);
        assert_eq!(modules[0].name, "halfwritten");
        assert!(modules[0].detail.contains("4096 bytes"));
    }
}
