// SPDX-License-Identifier: CC-BY-NC-SA-4.0
//
// Every local link in the documentation and the website has to point at
// something that exists.
//
// # Why this is a test
//
// `docs/INSTALL.md` shipped a link to `REPRODUCIBLE-BUILDS.md`. The file is
// called `REPRODUCIBLE_BUILDS.md`. One character, and the link was dead on
// GitHub and on the site -- written by somebody who had just read the real
// filename, in a document whose whole subject is telling people where to go and
// check things for themselves.
//
// That is the same shape as every other defect this repository keeps finding:
// silent, invisible to every existing check, and specifically corrosive to a
// project whose argument is "go and read it yourself". A dead link is not a
// cosmetic problem here. It is the argument failing.
//
// # What counts as a link worth checking
//
// Only links that name something in this repository. External `http(s)` URLs
// are not fetched -- a test suite that reaches the network is a test suite that
// fails when somebody else's server is down, and this project's CI has no
// business making requests anyway. Fragments (`#section`) are checked for the
// file they hang off, not for the anchor: heading anchors are generated
// differently by GitHub, by this site's renderer and by the browser, and
// asserting one of those spellings would fail on the other two.

"use strict";

const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..", "..");

function trackedFiles() {
  return execFileSync("git", ["ls-files", "-z"], { cwd: ROOT, encoding: "buffer" })
    .toString("utf8")
    .split("\0")
    .filter(Boolean);
}

// Generated by `tools/search-index/generate.py` from every other file, so any
// link inside them is a copy of one already checked at its source. Checking
// them again would report the same fault many times over and, worse, would
// report excerpt text that merely *looks* like a link.
const GENERATED = new Set([
  "website/search-index.json",
  "website/nojs/search.html"
]);

const MD_LINK = /\[[^\]]*\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g;
const HREF = /(?:href|src)\s*=\s*["']([^"']+)["']/gi;

/**
 * Remove quoted code before looking for links.
 *
 * Text inside a fence or backticks is an *example of* a link, not a link, and
 * this repository is full of both -- `docs/AUDIT.md` alone quotes a README
 * link to show how it once rendered wrongly, and quotes
 * `src="a&quot;onerror=x"` to explain why a naive scanner called it an attack.
 *
 * The first version of this file reported both as broken links: the
 * documentation describing a bug correctly, flagged as a bug. That is the
 * mistake `docs/AUDIT.md` section 4.4 records, where five of six "findings"
 * were the checker rather than the code. A checker has to read the way the
 * thing it checks is read.
 *
 * Replaced with spaces rather than deleted, so byte offsets -- and therefore
 * any future line reporting -- stay meaningful.
 */
function stripQuotedCode(text, isHtml) {
  const blank = m => " ".repeat(m.length);
  let out = text
    .replace(/```[\s\S]*?```/g, blank)     // fenced, backticks
    .replace(/~~~[\s\S]*?~~~/g, blank);    // fenced, tildes
  if (isHtml) {
    out = out
      .replace(/<pre\b[\s\S]*?<\/pre>/gi, blank)
      .replace(/<code\b[\s\S]*?<\/code>/gi, blank);
  }
  // Inline code last: a fence's own content may contain single backticks.
  return out.replace(/`[^`\n]*`/g, blank);
}

/** Is this a link into this repository, rather than out of it? */
function isLocal(target) {
  if (!target) { return false; }
  if (/^[a-z][a-z0-9+.-]*:/i.test(target)) { return false; }  // http:, mailto:, data:
  if (target.startsWith("//")) { return false; }              // protocol-relative
  if (target.startsWith("#")) { return false; }               // same-page fragment
  return true;
}

/** Where a link resolves to on disk, or null if it leaves the repository. */
function resolveTarget(fromFile, target) {
  const clean = target.split("#")[0].split("?")[0];
  if (!clean) { return null; }

  const base = target.startsWith("/")
    ? ROOT
    : path.dirname(path.join(ROOT, fromFile));

  const resolved = path.resolve(base, target.startsWith("/") ? "." + clean : clean);
  if (!resolved.startsWith(ROOT)) { return null; }
  return resolved;
}

function run() {
  let fails = 0;
  const check = (name, ok) => {
    console.log((ok ? "ok   " : "FAIL ") + name);
    if (!ok) { fails++; }
  };

  const files = trackedFiles().filter(
    f => (/\.(md|html)$/i.test(f)) && !GENERATED.has(f)
  );

  const broken = [];
  let checked = 0;

  for (const rel of files) {
    let text;
    try {
      text = fs.readFileSync(path.join(ROOT, rel), "utf8");
    } catch {
      continue;
    }

    const prose = stripQuotedCode(text, /\.html$/i.test(rel));

    const targets = [];
    for (const m of prose.matchAll(MD_LINK)) { targets.push(m[1]); }
    for (const m of prose.matchAll(HREF)) { targets.push(m[1]); }

    for (const target of targets) {
      if (!isLocal(target)) { continue; }
      const resolved = resolveTarget(rel, target);
      if (resolved === null) {
        broken.push(`${rel} -> ${target} (escapes the repository)`);
        continue;
      }
      checked++;
      if (!fs.existsSync(resolved)) {
        broken.push(`${rel} -> ${target}`);
      }
    }
  }

  check(`every local link in ${files.length} documents resolves ` +
        `(${checked} checked)`, broken.length === 0);
  for (const line of broken.slice(0, 20)) {
    console.log("     broken: " + line);
  }
  if (broken.length > 20) {
    console.log(`     ...and ${broken.length - 20} more`);
  }

  // The check must not be vacuous: if the extraction silently matched nothing,
  // the suite above would pass while testing exactly zero links.
  check("the link extraction actually found links", checked > 50);

  return fails;
}

module.exports = { run, name: "documentation links" };

if (require.main === module) { process.exit(run() ? 1 : 0); }
