#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""
The window captures are of this version of the window.

    python tools/shots/taken.py --check    # they were taken from this version
    python tools/shots/taken.py --record   # only from tools/shots/gui.sh

# The defect this exists to stop coming back

Fifteen pictures of the window are published: on the website, in the
documentation, in the wiki, and as the no-JavaScript edition's whole
demonstration. They are taken by `tools/shots/gui.sh`, which runs the real
program under a headless display and photographs it.

**Nothing compared them against the window they are pictures of.** Every check
around them is about the pictures as pictures: that none carries a capture
border, that none has empty space below its content, that they share one
height, that the tags on the pages state the right sizes. A picture of last
month's window passes all four.

Two of them had gone stale and were found by hand:

  * `gui-about.png` was 7.02% different from what the window draws, because
    roadmap item 165 added a release channel line to the About tab and nobody
    recaptured.
  * The common height moved from 1550 to 1576, because roadmap item 164 made
    the Verify tab taller. `fit.py` fits every capture to one height, so that
    is the whole set out of date, not one of them.

Both landed on `dev` and neither failed anything.

# Why the check is a version and not a comparison

The obvious check is to capture again and compare. That needs the window to
run, which needs a build, a display and `libxkbcommon-x11`, and a fresh
capture differs from a committed one by antialiasing even on the same machine
and the same commit: thirteen of the fifteen reproduce to within 0.1% of
bytes, and two do not. A gate that is right most of the time about a
difference nobody can act on is a gate people learn to ignore.

So this checks the thing that can be known exactly. The captures carry the
version of VeilVoice they were taken from, written by `gui.sh` as part of
capturing, and a release cannot be cut while that is not the version being
released. Retaking becomes an obligation once per release rather than once
per commit, which is what it actually is: the interface changes many times
between releases and is published once.

It is not a claim that the pictures are current between releases. It is a
claim that a release does not ship pictures of an older one, which is the
promise being made to somebody reading the site.

# Why `--record` is not a generator

Every other derived thing here is regenerated by `tools/verify.py` and checked
in the same run. This is not, deliberately: a record that any run can rewrite
records nothing. `--record` is written by `gui.sh` at the end of a successful
capture, so the only way to move the version forward is to take the pictures.
Running it by hand without capturing is writing down something that is not
true, and there is no way to stop somebody doing that beyond saying so here.
"""

from __future__ import annotations

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))

SHOTS = os.path.join(ROOT, "assets", "screenshots")
RECORD = os.path.join(SHOTS, "taken.txt")
RECORD_REL = os.path.join("assets", "screenshots", "taken.txt")

HEADER = [
    "# GENERATED by tools/shots/gui.sh. Do not edit by hand.",
    "#",
    "# The version of VeilVoice the window captures below were taken from, and",
    "# which captures those are. Written at the end of a successful capture, so",
    "# moving the version forward means taking the pictures again.",
    "#",
    "# tools/shots/taken.py --check fails when this is not the version in",
    "# Cargo.toml, which is what stops a release publishing pictures of an",
    "# older window. See the module note in that file for why this is a version",
    "# rather than a comparison against a fresh capture.",
]


def version():
    """The workspace's version, which is the version a release would carry."""
    with open(os.path.join(ROOT, "Cargo.toml"), encoding="utf-8") as handle:
        manifest = handle.read()
    block = re.search(r"\[workspace\.package\]([\s\S]*?)(\n\[|$)", manifest)
    if not block:
        raise SystemExit("Cargo.toml has no [workspace.package] to read a "
                         "version from")
    found = re.search(r'^\s*version\s*=\s*"([^"]+)"', block.group(1), re.M)
    if not found:
        raise SystemExit("[workspace.package] in Cargo.toml declares no version")
    return found.group(1)


def captures():
    """The window captures on disk, by name, sorted."""
    return sorted(name for name in os.listdir(SHOTS)
                  if name.startswith("gui-") and name.endswith(".png"))


def recorded():
    """The version and the captures the record names, or (None, [])."""
    if not os.path.exists(RECORD):
        return (None, [])
    found, names = None, []
    with open(RECORD, encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("version "):
                found = line.split(" ", 1)[1].strip()
                continue
            names.append(line)
    return (found, sorted(names))


def record():
    lines = list(HEADER)
    lines.append("")
    lines.append("version %s" % version())
    lines.append("")
    lines.extend(captures())
    with open(RECORD, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    print("  recorded %d capture(s) as taken from v%s"
          % (len(captures()), version()))
    return 0


def check():
    want = version()
    found, names = recorded()
    here = captures()
    problems = []

    if found is None:
        problems.append(
            "%s does not exist, so nothing says which version of the window "
            "these are pictures of" % RECORD_REL)
    elif found != want:
        problems.append(
            "the captures were taken from v%s and this tree is v%s. The "
            "window has been through a release since they were photographed."
            % (found, want))

    missing = [name for name in names if name not in here]
    extra = [name for name in here if name not in names]
    for name in missing:
        problems.append("%s names %s, which is not there" % (RECORD_REL, name))
    for name in extra:
        problems.append("%s is a capture %s does not name, so it was not "
                        "taken in the run that record describes"
                        % (name, RECORD_REL))

    if problems:
        print("  the window captures do not describe this version:")
        for line in problems:
            print("    %s" % line)
        print()
        print("    Take them again, which writes the record as part of doing")
        print("    it:")
        print()
        print("      cargo build --release -p veilvoice-gui -p veilvoice-cli")
        print("      tools/shots/gui.sh")
        print("      python tools/verify.py --quick")
        print()
        print("    A release that ships pictures of an older window is telling")
        print("    somebody the program looks like something it does not.")
        return 1

    print("  %d window capture(s), taken from v%s, which is this version"
          % (len(here), found))
    return 0


def main():
    if "--record" in sys.argv:
        return record()
    if "--check" in sys.argv:
        return check()
    print(__doc__.strip().split("\n\n")[1].strip())
    return 2


if __name__ == "__main__":
    sys.exit(main())
