#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Pictures of the command line, drawn from its real output.

    python tools/shots/terminal.py --capture   # run the commands, save the text
    python tools/shots/terminal.py             # draw the SVGs from that text
    python tools/shots/terminal.py --check     # verify the SVGs match the text

# Two steps, on purpose

`--capture` runs `veilvoice` and writes what it printed into
`assets/screenshots/cli-<name>.txt`. That step needs a build, a machine, and a
person deciding the output is right; it is not something CI can do.

Everything after that is a pure function of those text files, so the drawings
**are** reproducible and CI checks them exactly the way it checks the banners:
regenerate into memory, compare, fail on a difference. A picture of a command
line that disagrees with the command line is documentation that lies, and this
is the arrangement that makes that impossible to commit by accident.

The text is committed beside the picture and is the thing to read in a diff. An
SVG diff is unreadable; a diff of what the program printed is the review.

# Why SVG and not a screenshot

The same reason the website's banner is text: it follows a palette rather than
being baked in one, it can be selected, searched and read aloud, and it stays
sharp at any size. Finding F-37 was this project's own claims rendered
illegibly inside an image. Claims stay out of images.

# What is captured, and what is deliberately not

Only commands that print the program's own help and its own findings. Nothing
that names this machine's devices, users or paths: a demonstration picture is
published, and a device list is a description of somebody's hardware.

Pure standard library.
"""

import argparse
import io
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
OUT = os.path.join(ROOT, "assets", "screenshots")

# The site serves only what is under `website/`, so every picture has to exist
# there as well. That copy is made *here*, by the tool that owns the pictures,
# and it is checked here too -- including the window captures, which this tool
# does not draw but does keep in step.
#
# Finding F-41 was exactly this: website assets drifting from the generator that
# produced them, silently, with nothing able to tell. A second copy kept by hand
# is a second copy that will be wrong.
WEB = os.path.join(ROOT, "website", "assets", "screenshots")

MARKER = "GENERATED by tools/shots/terminal.py"

# Tokyo Night, the same hexes `website/css/themes.css` declares. Written out
# rather than parsed, exactly as the documentation generator does it, and for
# the same reason: a tool should not need the website on disk to draw a box.
BG = "#16161e"
BG_BAR = "#1f2335"
BORDER = "#2f3549"
FG = "#c0caf5"
MUTED = "#737aa2"
GREEN = "#9ece6a"
BLUE = "#7aa2f7"
YELLOW = "#e0af68"
RED = "#f7768e"

MONO = "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
CHAR_W = 8.04          # one character at 13.4px in this stack, near enough
LINE_H = 19.0
FONT = 13.4
PAD_X = 18.0
PAD_TOP = 46.0         # room for the title bar
PAD_BOTTOM = 16.0

# Nothing here writes a file, starts a device, or names this machine.
COMMANDS = [
    ("help", ["--help"], "what the command line offers"),
    ("anonymise", ["anonymise", "--help"], "veiling one recording"),
    ("live", ["live", "--help"], "scrambling a microphone as it runs"),
    ("conversation", ["conversation", "--help"], "several people in one recording"),
    ("render", ["conversation", "render", "--help"], "a plan, a recording, and a page"),
    ("preview", ["conversation", "preview", "--help"], "what the video will look like"),
    ("companions", ["companions", "--help"], "software VeilVoice can use but never bundles"),
    ("capture", ["capture", "--help"], "which screen recorders are running"),
    ("guard", ["guard", "--help"], "noticing that a file changed"),
    ("clean", ["clean", "--help"], "metadata, EXIF and GPS"),
]

# A line longer than this is cut, with the cut marked. A help screen wraps
# itself; anything past this is a path or a URL, and a picture two thousand
# pixels wide to show the end of one is a worse picture.
MAX_COLUMNS = 96
# A capture longer than this is cut too. These are illustrations, not manuals.
MAX_LINES = 44


def binary():
    """Where the built `veilvoice` is."""
    target = os.environ.get("CARGO_TARGET_DIR") or os.path.join(ROOT, "target")
    name = "veilvoice.exe" if os.name == "nt" else "veilvoice"
    for profile in ("release", "debug"):
        path = os.path.join(target, profile, name)
        if os.path.exists(path):
            return path
    return None


def capture():
    """Run each command and write down what it printed."""
    exe = binary()
    if exe is None:
        print("  no `veilvoice` build found. Run:")
        print("    cargo build --release -p veilvoice-cli")
        return 1
    os.makedirs(OUT, exist_ok=True)
    for name, argv, _ in COMMANDS:
        # `--help` exits non-zero on some argument parsers and zero on others;
        # what is wanted is what it printed either way, so the status is not
        # checked. A command that printed nothing is what fails, below.
        # Bytes, decoded as UTF-8 explicitly. `text=True` decodes with the
        # locale encoding, which on Windows is CP1252 -- and the help screens
        # are full of em dashes. The first capture wrote every one of them as
        # three CP1252 characters instead, and the repository's own
        # stray-character suite is what noticed, three checks after this one
        # ran. Worth the note: the mojibake is invisible in a terminal that
        # is itself CP1252, which is where this was run.
        done = subprocess.run([exe] + argv, capture_output=True, cwd=ROOT, check=False)
        raw = done.stdout or done.stderr
        text = raw.decode("utf-8", "replace")
        if not text.strip():
            print("  %s printed nothing" % " ".join(argv))
            return 1
        path = os.path.join(OUT, "cli-%s.txt" % name)
        with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text.replace("\r\n", "\n"))
        print("  captured %-14s %d lines" % (name, text.count("\n") + 1))
    print()
    print("  now run this again without --capture to draw them")
    return 0


def esc(text):
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def colour_of(line):
    """A colour for one line, from its shape rather than from an escape code.

    The CLI turns colour off when it is not writing to a terminal, which is
    what makes the captured text clean and diffable -- and leaves the drawing
    with no colour information at all. Rather than re-run with colour forced
    and then parse ANSI, the shape of a help screen is read directly: it is a
    small, stable grammar and it is the same one for every subcommand.
    """
    stripped = line.strip()
    if not stripped:
        return FG
    if stripped.endswith(":") and stripped == stripped.upper():
        return BLUE                       # USAGE:, OPTIONS:, COMMANDS:
    if stripped.startswith("Usage:"):
        return BLUE
    if stripped.startswith("-") or stripped.startswith("--"):
        return GREEN                      # a flag
    if stripped.startswith("!"):
        return YELLOW                     # a warning the CLI prints
    if stripped.startswith("x") and stripped[1:2] == " ":
        return RED
    return FG


def draw(name, title, note, text):
    """One terminal window, as SVG."""
    lines = text.replace("\r\n", "\n").rstrip("\n").split("\n")
    cut_lines = len(lines) > MAX_LINES
    if cut_lines:
        lines = lines[:MAX_LINES]
    body = []
    for line in lines:
        line = line.rstrip()
        if len(line) > MAX_COLUMNS:
            line = line[: MAX_COLUMNS - 1] + "…"
        body.append(line)
    if cut_lines:
        body.append("…")

    columns = max([len(line) for line in body] + [len(title) + 4])
    width = PAD_X * 2 + columns * CHAR_W
    height = PAD_TOP + len(body) * LINE_H + PAD_BOTTOM

    out = []
    add = out.append
    add(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %.0f %.0f" '
        'width="%.0f" height="%.0f" style="max-width:100%%;height:auto" '
        'role="img" aria-label="%s">' % (width, height, width, height, esc(note))
    )
    add("<!-- %s from assets/screenshots/cli-%s.txt. Do not edit. -->" % (MARKER, name))
    add("<title>%s</title>" % esc(note))
    add('<rect x="0" y="0" width="%.0f" height="%.0f" rx="9" fill="%s"/>'
        % (width, height, BG))
    add('<rect x="0" y="0" width="%.0f" height="30" rx="9" fill="%s"/>' % (width, BG_BAR))
    add('<rect x="0" y="21" width="%.0f" height="9" fill="%s"/>' % (width, BG_BAR))
    add('<rect x="0.5" y="0.5" width="%.0f" height="%.0f" rx="9" fill="none" '
        'stroke="%s"/>' % (width - 1, height - 1, BORDER))
    # Three dots, because a box with three dots in the corner reads as a
    # terminal without a word being spent saying so.
    for index, colour in enumerate((RED, YELLOW, GREEN)):
        add('<circle cx="%.0f" cy="15" r="4.5" fill="%s"/>' % (18 + index * 16, colour))
    add('<text x="%.0f" y="20" font-family="%s" font-size="12" fill="%s" '
        'text-anchor="middle">%s</text>' % (width / 2.0, MONO, MUTED, esc(title)))

    for number, line in enumerate(body):
        if not line:
            continue
        add('<text x="%.1f" y="%.1f" font-family="%s" font-size="%.1f" '
            'fill="%s" xml:space="preserve">%s</text>'
            % (PAD_X, PAD_TOP + number * LINE_H, MONO, FONT, colour_of(line), esc(line)))
    add("</svg>")
    return "\n".join(out) + "\n"


def outputs():
    """Every drawing this tool owns, as {relative path: text}."""
    files = {}
    missing = []
    for name, argv, note in COMMANDS:
        path = os.path.join(OUT, "cli-%s.txt" % name)
        if not os.path.exists(path):
            missing.append(name)
            continue
        with io.open(path, encoding="utf-8") as handle:
            text = handle.read()
        title = "veilvoice " + " ".join(argv)
        files["assets/screenshots/cli-%s.svg" % name] = draw(name, title, note, text)

    # The website's copies, from the same run rather than by hand.
    for rel in list(files):
        files["website/" + rel] = files[rel]
    return files, missing


def window_captures():
    """The `gui-*.png` files, which this tool copies but does not make.

    Taken by `tools/shots/gui.ps1` against a running application, so they cannot
    be regenerated from anything in the tree. What *can* be kept true is that
    the website's copy is the same file, which is what this returns.
    """
    if not os.path.isdir(OUT):
        return []
    return sorted(
        name
        for name in os.listdir(OUT)
        if name.startswith("gui-") and name.endswith(".png")
    )


def mirror_captures(check):
    """Copy, or verify, the window captures under `website/`."""
    problems = []
    for name in window_captures():
        source = os.path.join(OUT, name)
        target = os.path.join(WEB, name)
        with open(source, "rb") as handle:
            blob = handle.read()
        if check:
            try:
                with open(target, "rb") as handle:
                    if handle.read() != blob:
                        problems.append(
                            "website/assets/screenshots/%s differs from assets/" % name
                        )
            except OSError as error:
                problems.append(
                    "website/assets/screenshots/%s: cannot read (%s)" % (name, error)
                )
        else:
            os.makedirs(WEB, exist_ok=True)
            with open(target, "wb") as handle:
                handle.write(blob)
    return problems


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--capture", action="store_true",
                        help="run the commands and save what they printed")
    parser.add_argument("--check", action="store_true",
                        help="verify the drawings match the captured text")
    args = parser.parse_args()

    if args.capture:
        return capture()

    files, missing = outputs()
    if missing:
        print("  no captured output for: %s" % ", ".join(missing))
        print("  run: python tools/shots/terminal.py --capture")
        return 1

    if args.check:
        problems = mirror_captures(check=True)
        for rel, text in sorted(files.items()):
            path = os.path.join(ROOT, rel.replace("/", os.sep))
            try:
                with io.open(path, encoding="utf-8") as handle:
                    if handle.read() != text:
                        problems.append("%s differs from its captured text" % rel)
            except OSError as error:
                problems.append("%s: cannot read (%s)" % (rel, error))
        if problems:
            for line in problems:
                print("  MISMATCH %s" % line)
            print()
            print("  Run 'python tools/shots/terminal.py' and commit the result.")
            return 1
        print(
            "  %d terminal drawings match their captured text, and %d window "
            "captures match their copies" % (len(files), len(window_captures()))
        )
        return 0

    os.makedirs(OUT, exist_ok=True)
    os.makedirs(WEB, exist_ok=True)
    for rel, text in sorted(files.items()):
        path = os.path.join(ROOT, rel.replace("/", os.sep))
        with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
    mirror_captures(check=False)
    print(
        "  wrote %d terminal drawings and mirrored %d window captures"
        % (len(files), len(window_captures()))
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
