#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Pictures of the command line, drawn from its real output.

    python tools/shots/terminal.py --capture   # run the commands, save the text
    python tools/shots/terminal.py             # draw the SVGs from that text
    python tools/shots/terminal.py --check     # verify the SVGs match the text

# Two steps, on purpose

`--capture` runs `veilvoice` and writes what it printed into
`assets/screenshots/cli-<name>.txt`. That step needs a build, a machine, and a
person deciding the output is right; it is not something CI can do.

Everything after that is a pure function of those text files, so the drawings
**are** reproducible and CI checks them exactly the way it checks the banners:
regenerate into memory, compare, fail on a difference. A picture of a command
line that disagrees with the command line is documentation that lies, and this
is the arrangement that makes that impossible to commit by accident.

The text is committed beside the picture and is the thing to read in a diff. An
SVG diff is unreadable; a diff of what the program printed is the review.

# Why SVG and not a screenshot

The same reason the website's banner is text: it follows a palette rather than
being baked in one, it can be selected, searched and read aloud, and it stays
sharp at any size. Finding F-37 was this project's own claims rendered
illegibly inside an image. Claims stay out of images.

# What is captured, and what is deliberately not

Only commands that print the program's own help and its own findings. Nothing
that names this machine's devices, users or paths: a demonstration picture is
published, and a device list is a description of somebody's hardware.

Pure standard library.
"""

import argparse
import io
import os
import re
import struct
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
OUT = os.path.join(ROOT, "assets", "screenshots")

# The site serves only what is under `website/`, so every picture has to exist
# there as well. That copy is made *here*, by the tool that owns the pictures,
# and it is checked here too -- including the window captures, which this tool
# does not draw but does keep in step.
#
# Finding F-41 was exactly this: website assets drifting from the generator that
# produced them, silently, with nothing able to tell. A second copy kept by hand
# is a second copy that will be wrong.
WEB = os.path.join(ROOT, "website", "assets", "screenshots")

MARKER = "GENERATED by tools/shots/terminal.py"

# Tokyo Night, the same hexes `website/css/themes.css` declares. Written out
# rather than parsed, exactly as the documentation generator does it, and for
# the same reason: a tool should not need the website on disk to draw a box.
BG = "#16161e"
BG_BAR = "#1f2335"
BORDER = "#2f3549"
FG = "#c0caf5"
MUTED = "#737aa2"
GREEN = "#9ece6a"
BLUE = "#7aa2f7"
YELLOW = "#e0af68"
RED = "#f7768e"

MONO = "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
# One character at 13.4px in this stack.
#
# 0.62 of the font size rather than the 0.60 this had, and the difference
# matters: `tools/site-tests/images.test.js` measures the result with 0.62, and
# a generator that lays out with the smaller number produces drawings that
# suite then reports as overflowing by a few pixels. The larger number is also
# the safer one, because the font is whichever of the stack the reader has.
TEXT_RATIO = 0.62
CHAR_W = 13.4 * TEXT_RATIO
LINE_H = 19.0
FONT = 13.4
PAD_X = 18.0
PAD_TOP = 46.0         # room for the title bar
PAD_BOTTOM = 16.0

# Nothing here writes a file, starts a device, or names this machine.
COMMANDS = [
    ("help", ["--help"], "what the command line offers"),
    ("anonymise", ["anonymise", "--help"], "veiling one recording"),
    ("live", ["live", "--help"], "scrambling a microphone as it runs"),
    ("conversation", ["conversation", "--help"], "several people in one recording"),
    ("render", ["conversation", "render", "--help"], "a plan, a recording, and a page"),
    ("preview", ["conversation", "preview", "--help"], "what the video will look like"),
    ("companions", ["companions", "--help"], "software VeilVoice can use but never bundles"),
    ("capture", ["capture", "--help"], "which screen recorders are running"),
    ("guard", ["guard", "--help"], "noticing that a file changed"),
    ("clean", ["clean", "--help"], "metadata, EXIF and GPS"),
]

# The widest a line may be drawn. A line longer than this is **wrapped**, not
# cut.
#
# It used to be cut, with an ellipsis marking the cut, and the reasoning was
# that a picture two thousand pixels wide to show the end of one path is a
# worse picture. That part is still true and it is why the width is bounded at
# all. What was wrong was the other half: a help screen that says
#
#     -o, --output <OUTPUT>   Output device name. Defaults to a virtual cable if one is fo…
#
# has not shown the reader what the flag does. It has shown them that there is
# more and they cannot have it, in a picture whose entire job is explaining the
# flag. Three of the committed drawings ended a sentence mid-word that way.
#
# So the picture gets taller instead of wider, which is the axis a page can
# afford, and the text is all there.
MAX_COLUMNS = 96
# A capture longer than this is cut too. These are illustrations, not manuals.
MAX_LINES = 44


def binary():
    """Where the built `veilvoice` is."""
    target = os.environ.get("CARGO_TARGET_DIR") or os.path.join(ROOT, "target")
    name = "veilvoice.exe" if os.name == "nt" else "veilvoice"
    for profile in ("release", "debug"):
        path = os.path.join(target, profile, name)
        if os.path.exists(path):
            return path
    return None


def capture():
    """Run each command and write down what it printed."""
    exe = binary()
    if exe is None:
        print("  no `veilvoice` build found. Run:")
        print("    cargo build --release -p veilvoice-cli")
        return 1
    os.makedirs(OUT, exist_ok=True)
    for name, argv, _ in COMMANDS:
        # `--help` exits non-zero on some argument parsers and zero on others;
        # what is wanted is what it printed either way, so the status is not
        # checked. A command that printed nothing is what fails, below.
        # Bytes, decoded as UTF-8 explicitly. `text=True` decodes with the
        # locale encoding, which on Windows is CP1252 -- and the help screens
        # are full of em dashes. The first capture wrote every one of them as
        # three CP1252 characters instead, and the repository's own
        # stray-character suite is what noticed, three checks after this one
        # ran. Worth the note: the mojibake is invisible in a terminal that
        # is itself CP1252, which is where this was run.
        done = subprocess.run([exe] + argv, capture_output=True, cwd=ROOT, check=False)
        raw = done.stdout or done.stderr
        text = raw.decode("utf-8", "replace")
        if not text.strip():
            print("  %s printed nothing" % " ".join(argv))
            return 1
        path = os.path.join(OUT, "cli-%s.txt" % name)
        with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text.replace("\r\n", "\n"))
        print("  captured %-14s %d lines" % (name, text.count("\n") + 1))
    print()
    print("  now run this again without --capture to draw them")
    return 0


def esc(text):
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def colour_of(line):
    """A colour for one line, from its shape rather than from an escape code.

    The CLI turns colour off when it is not writing to a terminal, which is
    what makes the captured text clean and diffable -- and leaves the drawing
    with no colour information at all. Rather than re-run with colour forced
    and then parse ANSI, the shape of a help screen is read directly: it is a
    small, stable grammar and it is the same one for every subcommand.
    """
    stripped = line.strip()
    if not stripped:
        return FG
    if stripped.endswith(":") and stripped == stripped.upper():
        return BLUE                       # USAGE:, OPTIONS:, COMMANDS:
    if stripped.startswith("Usage:"):
        return BLUE
    if stripped.startswith("-") or stripped.startswith("--"):
        return GREEN                      # a flag
    if stripped.startswith("!"):
        return YELLOW                     # a warning the CLI prints
    if stripped.startswith("x") and stripped[1:2] == " ":
        return RED
    return FG


# A help screen's second column: leading space, the flag group, a run of two or
# more spaces, then the description.
#
# The flag group is `\S(?:.*?\S)?` rather than one token, and that is the whole
# difficulty. `-o, --output <OUTPUT>` is four tokens separated by single spaces,
# so a pattern that matched one token found `-o,` and then looked for the column
# gap immediately after it, failed, and fell through to the prose branch, which
# collapsed the column and left `-o, --output <OUTPUT> Output device name`. The
# non-greedy form takes everything up to the *first* run of two spaces, which is
# what the column gap actually is.
OPTION_LINE = re.compile(r"^(\s*)(\S(?:.*?\S)?)(\s{2,})(\S.*)$")


def wrap_line(line, width):
    """One captured line as one or more drawn lines, wrapped on words.

    Three things this has to get right, each of which it got wrong first:

    * **The second column stays a column.** A wrapped option indents to where
      its description started, so the flag column is still readable down the
      page. Wrapping to zero turns a tidy help screen into a paragraph.
    * **Nothing comes out wider than `width`.** Including a word that is on its
      own longer than the line, which for these captures means a path or a URL:
      it is broken at the width, because a line that overflows the picture is
      the thing being fixed.
    * **A word is never broken otherwise**, and no line is left blank in the
      middle of a help screen.

    The joining rule is worth stating because it is where the column lives: the
    prefix already ends in the column's spaces, so a word is appended to it
    directly, and a space is added only when the line so far ends in something
    other than a space.
    """
    if len(line) <= width:
        return [line]

    match = OPTION_LINE.match(line)
    if match:
        head = match.group(1) + match.group(2) + match.group(3)
        rest = match.group(4)
    else:
        lead = len(line) - len(line.lstrip(" "))
        head = " " * lead
        rest = line.strip()
    indent = " " * len(head)
    # A column gap wider than the line leaves nothing to wrap into.
    if len(indent) > width // 2:
        indent = " " * min(len(indent), max(2, width // 4))

    out = []
    current = head
    for word in rest.split():
        if len(indent) + len(word) > width:
            # Longer than a line of its own: break it at the width.
            if current.strip():
                out.append(current.rstrip())
                current = indent
            while len(current) + len(word) > width:
                room = width - len(current)
                out.append(current + word[:room])
                word = word[room:]
                current = indent
            current += word
            continue
        joiner = "" if current.endswith(" ") or not current else " "
        if len(current) + len(joiner) + len(word) > width:
            out.append(current.rstrip())
            current = indent + word
        else:
            current = current + joiner + word
    if current.strip():
        out.append(current.rstrip())
    return out or [line[:width]]


def draw(name, title, note, text):
    """One terminal window, as SVG."""
    lines = text.replace("\r\n", "\n").rstrip("\n").split("\n")
    cut_lines = len(lines) > MAX_LINES
    if cut_lines:
        lines = lines[:MAX_LINES]
    body = []
    for line in lines:
        body.extend(wrap_line(line.rstrip(), MAX_COLUMNS))
    if cut_lines:
        body.append("…")

    columns = max([len(line) for line in body] + [len(title) + 4])
    width = PAD_X * 2 + columns * CHAR_W
    height = PAD_TOP + len(body) * LINE_H + PAD_BOTTOM

    out = []
    add = out.append
    add(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %.0f %.0f" '
        'width="%.0f" height="%.0f" style="max-width:100%%;height:auto" '
        'role="img" aria-label="%s">' % (width, height, width, height, esc(note))
    )
    add("<!-- %s from assets/screenshots/cli-%s.txt. Do not edit. -->" % (MARKER, name))
    add("<title>%s</title>" % esc(note))
    add('<rect x="0" y="0" width="%.0f" height="%.0f" rx="9" fill="%s"/>'
        % (width, height, BG))
    add('<rect x="0" y="0" width="%.0f" height="30" rx="9" fill="%s"/>' % (width, BG_BAR))
    add('<rect x="0" y="21" width="%.0f" height="9" fill="%s"/>' % (width, BG_BAR))
    add('<rect x="0.5" y="0.5" width="%.0f" height="%.0f" rx="9" fill="none" '
        'stroke="%s"/>' % (width - 1, height - 1, BORDER))
    # Three dots, because a box with three dots in the corner reads as a
    # terminal without a word being spent saying so.
    for index, colour in enumerate((RED, YELLOW, GREEN)):
        add('<circle cx="%.0f" cy="15" r="4.5" fill="%s"/>' % (18 + index * 16, colour))
    add('<text x="%.0f" y="20" font-family="%s" font-size="12" fill="%s" '
        'text-anchor="middle">%s</text>' % (width / 2.0, MONO, MUTED, esc(title)))

    for number, line in enumerate(body):
        if not line:
            continue
        add('<text x="%.1f" y="%.1f" font-family="%s" font-size="%.1f" '
            'fill="%s" xml:space="preserve">%s</text>'
            % (PAD_X, PAD_TOP + number * LINE_H, MONO, FONT, colour_of(line), esc(line)))
    add("</svg>")
    return "\n".join(out) + "\n"


def outputs():
    """Every drawing this tool owns, as {relative path: text}."""
    files = {}
    missing = []
    for name, argv, note in COMMANDS:
        path = os.path.join(OUT, "cli-%s.txt" % name)
        if not os.path.exists(path):
            missing.append(name)
            continue
        with io.open(path, encoding="utf-8") as handle:
            text = handle.read()
        title = "veilvoice " + " ".join(argv)
        files["assets/screenshots/cli-%s.svg" % name] = draw(name, title, note, text)

    # The website's copies, from the same run rather than by hand.
    for rel in list(files):
        files["website/" + rel] = files[rel]
    return files, missing


def window_captures():
    """The `gui-*.png` files, which this tool copies but does not make.

    Taken by `tools/shots/gui.ps1` against a running application, so they cannot
    be regenerated from anything in the tree. What *can* be kept true is that
    the website's copy is the same file, which is what this returns.
    """
    if not os.path.isdir(OUT):
        return []
    return sorted(
        name
        for name in os.listdir(OUT)
        if name.startswith("gui-") and name.endswith(".png")
    )



def png_size(path):
    """Width and height out of a PNG's header, without a decoder.

    IHDR is always the first chunk and its first eight bytes are the two
    dimensions, big-endian. Sixteen bytes in, eight bytes long -- which is why
    this is four lines rather than a dependency.
    """
    with open(path, "rb") as handle:
        head = handle.read(24)
    if len(head) < 24 or head[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("%s is not a PNG" % path)
    return struct.unpack(">II", head[16:24])


def check_declared_sizes():
    """The gallery declares each capture's size; verify it is the real one.

    `width` and `height` on an `<img>` are what stop the page reflowing as each
    picture arrives -- the browser reserves the right box before the bytes come.
    A declared size that has gone stale is worse than none: the page reserves
    the wrong box and then jumps anyway, under a reader who is mid-sentence.

    It went stale the first time within an hour of being written, because the
    capture window was made taller so a longer tab would fit. Hence a check
    rather than a note asking somebody to remember.
    """
    page = os.path.join(ROOT, "website", "index.html")
    if not os.path.exists(page):
        return []
    with io.open(page, encoding="utf-8") as handle:
        html = handle.read()

    problems = []
    for name in window_captures():
        width, height = png_size(os.path.join(OUT, name))
        found = re.search(
            r'src="assets/screenshots/%s"[^>]*?width="(\d+)" height="(\d+)"' % re.escape(name),
            html,
        )
        if found is None:
            # Not every capture has to be in the gallery; one that is not
            # simply has nothing to check.
            continue
        if (int(found.group(1)), int(found.group(2))) != (width, height):
            problems.append(
                "website/index.html declares %s as %sx%s and it is %dx%d"
                % (name, found.group(1), found.group(2), width, height)
            )
    return problems

def mirror_captures(check):
    """Copy, or verify, the window captures under `website/`."""
    problems = []
    for name in window_captures():
        source = os.path.join(OUT, name)
        target = os.path.join(WEB, name)
        with open(source, "rb") as handle:
            blob = handle.read()
        if check:
            try:
                with open(target, "rb") as handle:
                    if handle.read() != blob:
                        problems.append(
                            "website/assets/screenshots/%s differs from assets/" % name
                        )
            except OSError as error:
                problems.append(
                    "website/assets/screenshots/%s: cannot read (%s)" % (name, error)
                )
        else:
            os.makedirs(WEB, exist_ok=True)
            with open(target, "wb") as handle:
                handle.write(blob)
    return problems


def check_captures_are_current():
    """**F-103.** Do the committed captures still say what the program says?

    Nothing asked this. `--check` compared each drawing against the text file
    beside it, and the text file against nothing at all: it is written by
    `--capture`, which is a separate command nobody runs by accident. So a
    string could be rewritten in `veilvoice-cli` and every check in this
    repository would pass while `assets/screenshots/` went on showing the old
    wording, on the website, in the README and in the gallery.

    That is not hypothetical. It happened during the sweep that took the em
    dashes out of the interface text: the code changed, the whole of
    `tools/verify.py` passed, and `cli-help.txt` still contained a dash the
    program no longer prints. The audit had recorded the re-capture as a manual
    step and this is the half that was missing, which is that nothing said when
    the manual step was due.

    Every command captured here is a `--help` screen, so its output is a
    function of the binary and not of the machine: two people with the same
    commit get the same bytes. That is what makes this checkable at all, and it
    is why the list stays help screens. A capture of something that reads the
    machine -- what is installed, what is plugged in -- could not be checked
    this way and would have to be marked as such.

    Skipped where there is no build, which is the state of the CI job that runs
    the other checks here. It is not skipped where it matters: `verify.py` runs
    after `cargo build`, on the machine where the strings were just edited.
    """
    exe = binary()
    if exe is None:
        return [], False
    problems = []
    for name, argv, _ in COMMANDS:
        path = os.path.join(OUT, "cli-%s.txt" % name)
        if not os.path.exists(path):
            continue
        done = subprocess.run([exe] + argv, capture_output=True, cwd=ROOT, check=False)
        raw = done.stdout or done.stderr
        live = raw.decode("utf-8", "replace").replace("\r\n", "\n")
        with io.open(path, encoding="utf-8") as handle:
            saved = handle.read()
        if live.strip() != saved.strip():
            problems.append(
                "assets/screenshots/cli-%s.txt is not what `veilvoice %s` prints"
                % (name, " ".join(argv))
            )
    return problems, True


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--capture", action="store_true",
                        help="run the commands and save what they printed")
    parser.add_argument("--check", action="store_true",
                        help="verify the drawings match the captured text")
    args = parser.parse_args()

    if args.capture:
        return capture()

    files, missing = outputs()
    if missing:
        print("  no captured output for: %s" % ", ".join(missing))
        print("  run: python tools/shots/terminal.py --capture")
        return 1

    if args.check:
        stale, ran = check_captures_are_current()
        problems = mirror_captures(check=True) + check_declared_sizes() + stale
        for rel, text in sorted(files.items()):
            path = os.path.join(ROOT, rel.replace("/", os.sep))
            try:
                with io.open(path, encoding="utf-8") as handle:
                    if handle.read() != text:
                        problems.append("%s differs from its captured text" % rel)
            except OSError as error:
                problems.append("%s: cannot read (%s)" % (rel, error))
        if problems:
            for line in problems:
                print("  MISMATCH %s" % line)
            print()
            if stale:
                print("  Run 'python tools/shots/terminal.py --capture', then")
                print("  'python tools/shots/terminal.py', and commit the result.")
            else:
                print("  Run 'python tools/shots/terminal.py' and commit the result.")
            return 1
        print(
            "  %d terminal drawings match their captured text, and %d window "
            "captures match their copies" % (len(files), len(window_captures()))
        )
        print(
            "  and the captures %s"
            % ("are what the built program prints" if ran
               else "were not compared against a build: there is none here")
        )
        return 0

    os.makedirs(OUT, exist_ok=True)
    os.makedirs(WEB, exist_ok=True)
    for rel, text in sorted(files.items()):
        path = os.path.join(ROOT, rel.replace("/", os.sep))
        with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
    mirror_captures(check=False)
    print(
        "  wrote %d terminal drawings and mirrored %d window captures"
        % (len(files), len(window_captures()))
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
